### ISSUE TITLE
Bug when copy/move file to drive root without trailing backslash in path

### ISSUE THREAD

**Issue by kek91** [fman-community/fman#105]
**OS**

Windows 10 x64
fman v0.3.6

**Bug description:**

When copying a file to a drive root when there's no backslash at the end of the path, for instance "B:", it shows error message "object of type 'NoneType' has no len()" - see image below.

**How to replicate:**

1: Open GoTo and enter "X:" (replace X with a valid drive), and press ENTER.
The path bar will now say X: without a backslash at the end.
![path on drive root](https://transfer.sh/R7mnc/2017-03-22-12-41-30-re-bug-report-fman-windows-10-norkekgmail.com-gmail.png)

2: Copy a file from the other pane and it will raise an exception.

![exception error](https://transfer.sh/6IeUG/2017-03-22-12-41-15-re-bug-report-fman-windows-10-norkekgmail.com-gmail.png)

**Workaround:**

Simply pressing **TAB** or **\\** before ENTER in the GoTo modal will add the \\ automatically and fix it.

**Comment by mherrmann** [comment]
Fixed. Will be released as part of fman 0.6.3.
