### ISSUE TITLE
Shortcut to deselect all files

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#113]
After selecting files with Ctrl+A there is no way to deselect them all. There should be deselect function, e.g. Ctrl+D.

**Comment by mherrmann** [comment]
@raguay's [DeSelect](https://github.com/raguay/DeSelect) plugin implements this; But you're right it should be a built-in command as well. I agree Ctrl+D (Cmd+D on Mac) would make sense.

**Comment by raguay** [comment]
Also, my [SelectByRegExp](https://github.com/raguay/SelectByRegExp) uses the toggle selection comand. Therefore, you can selectively deselect selected files using a regular expression. I use it that way a whole lot.

**Comment by mherrmann** [comment]
I implemented this as a new command called `Deselect` now. It will go live with release 0.3.7. The shortcut is `Cmd+D` on Mac, `Ctrl+D` on Linux/Windows. I'm afraid it makes your `DeSelect` plugin obsolete, @raguay. But it uses a new API function `DirectoryPane#clear_selection()`, which is potentially much faster than calling `.toggle_selection` on each selected file.

**Comment by mherrmann** [comment]
Fixed in v0.3.7.
