### ISSUE TITLE
Noticable delay when browsing directories

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#114]
Sometimes after pressing Enter key in GoTo dialog, there's noticable delay (~2 seconds) until new directory contents are displayed. Same happens when changing directories.
Only observed on macOS.

**Comment by mherrmann** [comment]
Hm. Could this be caused by a plugin?

**Comment by kek91** [comment]
\*cough\*

If you happen to use [StatusBarExtended](https://github.com/kek91/StatusBarExtended) then it traverse all files in directory to calculate size. For the moment this runs in the same thread as the main window so it freezes the UI. Will definitely prioritize this and get it fixed as soon as possible.

**Comment by mherrmann** [comment]
Does the problem disappear when you remove StatuBarExtended @joshas?

**Comment by macosxguru** [comment]
I was having the same issue. It was slow when I was switching directories. Removing the StatusBarExtended plugin immediately sped it up.

macosxguru

**Comment by ababak** [comment]
I was experiencing very long delays on Windows when browsing UNC paths with many files. The delay stayed on each directory change even after I went away from this folder. 
P.S. No StatuBarExtended plugin present.

**Comment by joshas** [comment]
@mherrmann Tested today without any plugins - no issues. Might be that some background process was doing lots of reading/writing and that slowed down fman.

**Comment by mherrmann** [comment]
Okay, thanks for letting us know @joshas!

But we should probably create a new issue for the UNC path problem, right @ababak?
