### ISSUE TITLE
Can't close the application when the command line/menu is open.

### ISSUE THREAD

**Issue by courtagenjim** [fman-community/fman#115]
On OSX/MacOS when the *command line/menu pop-up* is visible: can't quit the application with Cmd+Q; also can't quit it from the fman main (top of screen) "fman" --> "Quit fman" menu item.

Comment: in my experience it is pretty rare for modern, GUI-hosted application to be so modal; and probably breaks users expectations. 

This behavior will also be problematic if (for whatever reason) the application should get into a hung state when the pop-up is visible (unless a user knows how to 'force quit' an application). Unfortunately, I've experienced file management-related applications get 'stuck' on both OSX and Windows, so I'm admittedly somewhat gun-shy about this possibility.

**Comment by raguay** [comment]
I've noticed this as well.

**Comment by mherrmann** [comment]
Fixed so you can at least use `Cmd+Q`. Will go live with 0.5.0.
