### ISSUE TITLE
GoTo on Steroids becomes slow over time

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#116]
The longer you have fman installed, the slower GoTo on Steroids becomes. This is because its cache of most visited locations fills up. The goal of this issue is to make it faster!

**Comment by mherrmann** [comment]
A temporary workaround is to clear the cache by deleting `Visited Paths.json` in the User plugin.

**Comment by mherrmann** [comment]
You have to do it outside fman though because the file gets re-saved when it closes.

**Comment by raguay** [comment]
Should it be classified as a bug or improvement?

**Comment by mherrmann** [comment]
I would definitely say bug. For a file manager that claims to be fast, this is a no-no.

**Comment by mherrmann** [comment]
Fixed in v0.4.2, which was just released.

**Comment by raguay** [comment]
BTW: I use this feature now that it is fast. Before, it was much too slow to use. Thanks for fixing it.

**Comment by mherrmann** [comment]
That's good to hear :) I also like that it's much faster now in my personal workflows. It's such a useful feature.
