### ISSUE TITLE
Unable to Use installed user plugins in Ubuntu 16.04

### ISSUE THREAD

**Issue by udit7395** [fman-community/fman#123]

**Comment by mherrmann** [comment]
Thank you for asking here. Do I understand correctly that installing plugins simply has no effect for you? Did you restart fman? Where did you place the plugins? Can you show me a screenshot of your [Plugins directory](https://fman.io/docs/data-directory)?

**Comment by udit7395** [comment]
![screenshot from 2017-03-28 16-47-16](https://cloud.githubusercontent.com/assets/12898781/24402471/670411ce-13d6-11e7-9484-bd3df9fafa1c.png)
As you can see from the Screenshot "/home/udit/.config/fman/Local/Plugins"

**Comment by mherrmann** [comment]
This is the wrong folder :) It should be `/home/udit/.config/fman/Plugins`.

**Comment by udit7395** [comment]
Ah!! Dang it. Thanks. Also tested Plugins are working.
