### ISSUE TITLE
Plugin manager

### ISSUE THREAD

**Issue by nblackburn** [fman-community/fman#124]
A plugin manager in the same vein as Sublimes package manager would be awesome (runs inside the command palette).

**Comment by mherrmann** [comment]
Already working on it =) Please see #103

**Comment by nblackburn** [comment]
I saw that but didn't think it was the same reading it. I imagined a plugin manager that would work in the same way as sublime which the discussion wasn't eluding to.

**Comment by mherrmann** [comment]
Ah, sorry. It will be implemented via the Command Palette. I guess it isn't clear in #103.

**Comment by nblackburn** [comment]
Great to hear, thanks for clearing that up for me.
