### ISSUE TITLE
Failed to execute script pyi_rth_qt5plugins

### ISSUE THREAD

**Issue by oddrationale** [fman-community/fman#126]
fman fails to start on Windows 7 with the following error message: Failed to execute script pyi_rth_qt5plugins

![image](https://cloud.githubusercontent.com/assets/80038/24410015/8fdb4b88-1397-11e7-9fa2-b1ad07567c18.png)

The CrashReports folder is empty. Please let me know how else to troublshoot. Thanks!

**Comment by mherrmann** [comment]
Several users have been experiencing this problem and I've never been able to fully figure out why.

Could I ask you to download and unzip [this file](https://www.dropbox.com/s/bkw7hwih08kfvpp/fman_0.3.8-SNAPSHOT.zip?dl=1), then navigate to the extracted folder in a command prompt, type "fman.exe" there and tell me which output you get?

**Comment by oddrationale** [comment]
See the following gist: https://gist.github.com/oddrationale/d8a42fd0b960018d1652fb55eceb5f4f

I see in line 37 there appears to be a path that is hard coded to your development environment?

**Comment by mherrmann** [comment]
Thanks. Do you have the following files in `C:\Windows\System32`?

 * ws2_32.dll
 * mpr.dll
 * api-ms-win-crt-multibyte-l1-1-0.dll

**Comment by oddrationale** [comment]
I have the first two, but not **api-ms-win-crt-multibyte-l1-1-0.dll**.

**Comment by mherrmann** [comment]
Does it work when you copy [the file](https://www.dropbox.com/s/8d4o5vx5cjuhq6l/api-ms-win-crt-multibyte-l1-1-0.dll?dl=1) to `C:\Windows\System32`?

**Comment by oddrationale** [comment]
Tried copying the DLL file to my System32 folder and re-running fman (both my installed version, and the snapshot version you sent). Same issue.

EDIT: Had to also run `regsrvc api-ms-win-crt-multibyte-l1-1-0.dll` and it worked!

**Comment by mherrmann** [comment]
?!? Do you mean `regsvr32`?

**Comment by mherrmann** [comment]
I just released fman 0.3.8 which should hopefully fix the issue :)
