### ISSUE TITLE
Open current directory in external app

### ISSUE THREAD

**Issue by aanton** [fman-community/fman#128]
New command to open "current directory" in a external app

**Comment by mherrmann** [comment]
This is trivial to implement as a plugin. I'd be happy to help you with this. I recommend you follow these steps:

1. Go through the [tutorial](https://fman.io/docs/plugins-introduction) (5 mins).
2. Look at the source code of the [Core plugin](https://fman.io/docs/core-plugin), in particular `OpenTerminal` in `commands.py` and `os_.py`.

What you'll need will most likely look as follows:

```
from fman import DirectoryPaneCommand
from subprocess import Popen

class OpenMyExternalApp(DirectoryPaneCommand):
	def __call__(self):
		Popen(['/path/to/your/external/app'], cwd=self.pane.get_path())
```

If you need help, let me know!

**Comment by aanton** [comment]
Thanks @mherrmann!

I create the plugin extending the class `OpenWithEditor` (tested only in Ubuntu 16.04)

```python
from core.commands import OpenWithEditor
from fman import show_alert
from os.path import exists

class OpenCurrentPathWithEditor(OpenWithEditor):
    def __call__(self):
        path_to_open = self.pane.get_path()

        if exists(path_to_open):
            self._open_with_editor(path_to_open)
        else:
            show_alert('No current path detected!')
```

@mherrmann, could it be useful to publish it in Github or add it to the core?

**Comment by mherrmann** [comment]
Does this plugin let you do what you wanted? Doesn't it have exactly the same effect as F4 already?

**Comment by aanton** [comment]
F4 open the **selected files** in an external editor, but this plugin open the **current path** in an external editor. I know i can navigate to the parent folder (backspace), select the folder (already selected) & use F4 to get the same result, so it **only removes one keystroke**

**Comment by mherrmann** [comment]
I see! Well if it's useful for you, it may also be useful for others, so why not create a plugin? Can I help you to set it up on GitHub? You can for instance look at [StatusBarExtended](https://github.com/kek91/StatusBarExtended) as an example on GitHub. Do add the GitHub _topics_ "fman" and "plugin" please. This will make it possible in the future to discover your plugin via fman's built-in command for installing plugins.

**Comment by aanton** [comment]
Ok! I will do it & update this issue. Any suggestion about the key binding to use (i am currently using F3)?

**Comment by mherrmann** [comment]
Awesome! Since it opens the editor which is usually tied to F4, how about something F4-related? Eg. `Ctrl+F4`?

**Comment by aanton** [comment]
I have created the repository:
https://github.com/aanton/OpenCurrentPathWithEditor

Any suggestions are welcome.

**Comment by mherrmann** [comment]
Looks great! Tiny suggestion: Change the repository's description to `Open the current path in the external editor` (or similar). The reason is that I'm just working on #103, in which your plugin currently looks as follows:

![image](https://cloud.githubusercontent.com/assets/1076393/24561193/204b83da-1646-11e7-8c4f-d1bfea00b55d.png)

It would be more descriptive for people installing the plugin from within fman if you used a different description (like the one above).

**Comment by aanton** [comment]
I have updated the repository description

**Comment by mherrmann** [comment]
Awesome! :)

![image](https://cloud.githubusercontent.com/assets/1076393/24585130/18a0c864-1783-11e7-8fe3-1f8531e5f009.png)

I've added it to the [list of plugins on fman.io](https://fman.io/docs/plugins).

I'll close this issue now.
