### ISSUE TITLE
Plugins will run in threads in the future

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#130]
Hi all,

I just committed a change I'm quite excited about:

![image](https://cloud.githubusercontent.com/assets/1076393/24517269/dc2c8820-157d-11e7-96d2-e1c0c679fba0.png)

In the future (ie. from fman 0.3.9 onwards), plugins will be run in separate threads. This will keep fman responsive. For instance, a few people using @kek91's [StatusBarExtended](https://github.com/kek91/StatusBarExtended) said that it slows down fman. This should no longer be the case in 0.3.9 :)

I also did this because it simplifies the main new feature I'm currently working on: Being able to install plugins from GitHub (#103).

Best,
Michael

**Comment by mherrmann** [comment]
(P.S.: Existing (third-party) plugins should continue to work, without any changes.)

**Comment by macosxguru** [comment]
Sounds good. I am excited about the plugin manager you are working on.

macosxguru

**Comment by mherrmann** [comment]
:-)

**Comment by raguay** [comment]
Great. So I don't need to try to figure out how to run a thread in Python.

**Comment by mherrmann** [comment]
:-D

**Comment by mherrmann** [comment]
This went live with version 0.3.9, which was just released :-) [Changelog](https://fman.io/changelog)

**Comment by macosxguru** [comment]
This is cool. I love the new plugin manager.

macosxguru
