### ISSUE TITLE
"Remember Sort Settings" for each folder

### ISSUE THREAD

**Issue by ghost** [fman-community/fman#134]
Will "Remember Sort Settings" for each folder come soon? I'm missing this...

E.g., to have some folders always sorted by "Modified" — very useful.

How the feature could work: So, basically, if we sort a folder in some way other than the default, that setting is saved... And later restored when we navigate to that folder again.

In fact, I have this in Finder... My "Downloads" folder is always sorted by "Modified", so newly downloaded + changed + `touch`ed files are always on top! It's a great organizational / productivity "trick" I've been using for some years now. 🙂

Thank you, Michael, for fman and for considering this feature.

**Comment by mherrmann** [comment]
Thanks for writing up the feature :) The more people 👍 it, the sooner it will be implemented.

**Comment by cpa2002** [comment]
👍 this as well. Sort is a key recurring task for me

**Comment by mherrmann** [comment]
Implemented in [fman 0.8.3](https://fman.io/changelog#v0.8.3). :)
