### ISSUE TITLE
enhancement: cut/paste for macos

### ISSUE THREAD

**Issue by eostermueller** [fman-community/fman#138]
Seems like a cut/paste is a basic feature and not an advanced, right?
Need this for macos.  The screenshot below says this isn't implemented.
Would like support to: select multiple files, ctrl+x, create/move to a new folder, ctrl+v.

![image](https://cloud.githubusercontent.com/assets/175773/24753757/2eac2464-1a99-11e7-89da-f38dea5c3883.png)

**Comment by mherrmann** [comment]
Hi Erik, I'm afraid it's technically not possible. Version 0.3.9 of fman gives a better message. The [Changelog](https://fman.io/changelog) for that version explains why it isn't possible.

**Comment by eostermueller** [comment]
That's an ok option, thanks Michael.
