### ISSUE TITLE
Release using Snap

### ISSUE THREAD

**Issue by mrfuxi** [fman-community/fman#139]
Consider having 1 release mechanism for all (a log) Linux distros using https://snapcraft.io/

**Comment by mherrmann** [comment]
Thank you for the suggestion. It seems that if I go that route, then fman is always run by / inside Snap(?) I'd rather not introduce that dependency. Instead, I think it would be better if there were "native" packages of fman for the most prominent Linux distributions. The current `.deb` covers Ubuntu-based, Arch Linux has often been requested (see #55).

**Comment by mherrmann** [comment]
I'm wary of introducing the dependency on Snap, so will not implement this for now.
