### ISSUE TITLE
Abstract fman into a tree browser with file-management as default

### ISSUE THREAD

**Issue by bmix** [fman-community/fman#143]
Sooner or later it may be interesting to populate a file-manager's directory-views with arbitrary data. 

The most typical example would be an archive plugin, that gets executed on double-click on an archive-file, entering the archive as it would be a directory. 

Another use may be entering a user's IMAP account, where emails are stored in folders and could be represented as dquivalent to archives, allowing for access to header, body or attachement as they would be files within that archive (one would use this mostly to copy attachements to local disk, without running through a MUA). 

For people who spend a lot of time at a computer, several tools are indispensable. For me this leads to the desire, to do more with the tools, I have learned to master and could command while asleep. One interface, that I can use blindly is better than many, that clutter up my focus.

What if I could use the filemanager to show the process-list? I could use the file-manager's delete action to kill a task ( eq. file) or enter a process-tree (eq. directory) and kill a misbehaving sub-process. 

Chosing an XML or JSON document in fman would enter it as a directory. A quick display of the node-hierarchy in the file-manager. Editing a node would be equivalent to renaming a file. 

And what about comparison tools (dirs, files)? This could be expanded into a sync-utility.

Such an abstraction may come handy, should you ever add ftp-functionality. Or an SSH pseudo-filesystem.

So, my suggestion would be to rethink fman as a frontend for the display and handling of tree-structures, with the filesystem as the frontmost application. If it could display any tree as a file-system structure, then users could write backends, that map the functions of these backends to the file-manager's most sensible command. It's developers we're talking about, no? ;-)

- copy file -> copy node (or what it repesents)
- move file -> move node (or what it repesents)
- rename file -> edit node (or what it repesents)
- delete file -> delete node (or what it repesents)
- up, down, left(back), right(enter) -> up, down, left(back), right(enter)

So you're using the same interface for many more tasks, right from your file-manager.

**Comment by mherrmann** [comment]
You're reading my mind ;) This will come. It requires rewriting fman's file system implementation from scratch, which will take time (read: months). But once done, it will be extremely powerful.

**Comment by bmix** [comment]
That's cool! :-) Power to come! :-)

**Comment by rkhwaja** [comment]
I would like to see the windows registry supported in this way. The keys, at least, behave like a filesystem. The set of values in a key might be more like files.

**Comment by mherrmann** [comment]
That will be possible! The new API will make it easy to [write a plugin](https://fman.io/docs/plugins-introduction) which displays your registry and lets you edit it.

**Comment by raguay** [comment]
I want to do one that shows processes and then allows for killing. Commander One has that and it's very useful.

**Comment by mherrmann** [comment]
This is now implemented in fman 0.8.7. It really was a lot of work and I'm very happy it's finally out there. One of the things you mentioned @bmix is already possible: Managing (sub-)processes and deleting (=killing) them. All the other things are not difficult to do via the new [API](https://fman.io/docs/api#FileSystem). Also @rkhwaja's request for Windows registry support can be implemented now. Check out [today's blog post](https://fman.io/blog/fmans-new-file-system-api/)!

**Comment by mherrmann** [comment]
(Should have mentioned that process management is possible through the [ProcessFS plugin](https://github.com/mherrmann/ProcessFS).)

**Comment by tthomas2n** [comment]
I have the same problem as Thomas Vogelpohl, except my error happens trying to open anaconda-navegator.

**Comment by mherrmann** [comment]
@tthomas2n Thomas Vogelpohl reported that he couldn't start fman (in #583 referenced here). How is that related to not being able to open a terminal?
