### ISSUE TITLE
changed modified date is not detected

### ISSUE THREAD

**Issue by Schobers** [fman-community/fman#150]
**Scenario:**
- Update a file (using an external editor)
- or copy a file in fman from one folder to another overwriting an existing file.

**Expected:**
- The modified date is updated in fman.

**Actual:**
- The modified date is unchanged.
  - Unless you go into another directory and back.

OS: Windows 10
fman: 0.4.1

**Comment by mherrmann** [comment]
Thank you for reporting. This is already captured by #6. I'm closing this issue. If you would like to add further comments, please do so at #6.

Thanks,
Michael
