### ISSUE TITLE
environment variables are not resolved

### ISSUE THREAD

**Issue by Schobers** [fman-community/fman#151]
Feature request: environment variables should be resolved in the "Go to" bar.

E.g. when I type %GOPATH% (on Windows) it should resolve to the configured value for that environment variable.

**Comment by mherrmann** [comment]
Interesting, this was already requested once by @kek91. We discussed this in #118. We couldn't find a good solution back then so the issue was closed. I'll reopen it and close the present issue so we can continue the discussion there.
