### ISSUE TITLE
Add a feature to manage a list of bookmarks

### ISSUE THREAD

**Issue by hpehl** [fman-community/fman#159]
- Similar to bookmarks in your browser 
- Make them part of the command palette
- Add a way to create folder / subfolders for better organisation
- Show them as pop up menu using a short cut

**Comment by mherrmann** [comment]
Hi Harald,

thank you for the suggestion. May I ask if you know about fman's [GoTo on Steroids](https://fman.io/blog/goto-on-steroids/) (`Ctrl+P`)? Normally, it is used instead of bookmarks.

Best,
Michael

**Comment by hpehl** [comment]
GoTo on Steroids is a really useful feature. I was referring to a feature from TotalCommander where you can manage custom bookmarks in (sub)menus. I used it a lot to quickly go to my dev projects.

**Comment by mherrmann** [comment]
I understand. What my question was aimed at is: Doesn't GoTo on Steroids let you go to your dev projects just as quickly - but without the hassle of having to manually add / manage the bookmarks?

**Comment by hpehl** [comment]
It does. One question about the GoTo on Steroids feature: Does it list only the already visited folders? Is there a limit?

**Comment by mherrmann** [comment]
Cool, thanks. Yes, GoTo only lists the already visited folders. There's currently no limit. I find the feature extremely useful!

**Comment by raguay** [comment]
This feature would be useful for moving favorites from one install to the others. I run fman on two Macs, a linux box, and a Windows box. Being able to sync favorites from a common directory point (ie: Dropbox head) would be very useful.

Therefore, set a favorites top folder, then all favorites are relative to that top. Be able to share the favorites between systems and it should work. Since I work out of my Dropbox directory only, this would enable a full sync of bookmarks to work really well.

Maybe I'll work on a plugin like this....hmmmm......

**Comment by mherrmann** [comment]
:) You could use `show_quicksearch` from the API to have a GoTo-like dialog. It's not part of the public API yet, but I can make it so. GoTo itself already uses it.

**Comment by macosxguru** [comment]
When I first started using fman, I noticed that I was missing the convenience of the Sidebar folders in Finder. I have a few folders in the Finder sidebar which I go to often, I was missing them. But over a few months of use, fman now has all of those folders in the GoTo dialog. I don't miss the sidebar anymore.

Isn't that the usual use case for bookmarks? Besides Richard's very particular use case, I am not sure that the feature is all that useful.

macosxguru

**Comment by mherrmann** [comment]
I must admit that I also don't think this feature would give that much additional value, given that we have GoTo. From your comment @hpehl it also sounds like GoTo already lets you do what you want. @raguay's use case could be implemented as a plugin I think.

Having said that, GoTo still needs to improve a lot for the very first use. It only suggests directories you've visited before. So the first time you start it, it offers almost no suggestions. This should change. It should already offer decent suggestions the very first time you use it. I'll create a separate issue for this.

**Comment by mherrmann** [comment]
@raguay has released [his Favorites plugin](https://github.com/raguay/favorites) which implements a bookmark functionality that even works across multiple machines. I'm closing the present issue for now.
