### ISSUE TITLE
Open fman when I select "Open in Finder"

### ISSUE THREAD

**Issue by brodo** [fman-community/fman#160]
Finder replacements like Pathfinder somehow manage it to open when I select "Open in Finder" (for example from my browser). I use this quite often to navigate to just downloaded files. It would be nice if I could open fman this way.

**Comment by macosxguru** [comment]
PathFinder is a complete Finder replacement. fman is progressing in that direction but it is not there yet. At this point, building system hooks into fman might be too hasty. 

I solve this problem by keeping fman open all the time. If I need to go to the download folder, it is always open in one of the panes. Easy switch to it through ⌘+tab. Makes the process quite painless.

I must admit though that the mixture of fman and Alfred makes almost everything I do in Finder possible without the Finder being involved at all.

macosxguru

**Comment by mherrmann** [comment]
It's definitely an interesting suggestion. As fman becomes more powerful, it also becomes more and more appealing. I wouldn't say it's a top priority feature right now, but something to keep in mind.
