### ISSUE TITLE
F9 opens default terminal

### ISSUE THREAD

**Issue by lmamsen** [fman-community/fman#172]
fman version: 0.4.9
OS: Ubuntu Gnome 16.04.2

When I press F9 a Gnome terminal is opened, but I have change my default terminal to be Tilix. I did that via the command update-alternatives and has worked with our issues until now.

**Comment by mherrmann** [comment]
May I ask how / where you configured the default terminal?

**Comment by lmamsen** [comment]
I use update-alternatives like in the screenshot below and choose tilix, form the list.
![image](https://user-images.githubusercontent.com/1493573/26973728-15c53916-4d18-11e7-8ba1-dd6f217a3df5.png)

This also works with the default terminal shortcut "ctrl-alt-t".

**Comment by mherrmann** [comment]
Thanks! - Then the goal of this issue should be to make fman respect the choice of this setting.

**Comment by mherrmann** [comment]
Implemented in [fman 0.8.6](https://fman.io/changelog) :-)
