### ISSUE TITLE
Feature request: GoTo panel should go directly to the file pasted in

### ISSUE THREAD

**Issue by kszcode** [fman-community/fman#174]
The GoTo panel allows to fuzzy search and quickly navigate to the folders that have been recently used.

Still many times I have a path to a file in the clipboard.
It would be natural if when I paste in the path in the goto panel it would navigate me directly to the file or to the folder I've pasted in.
This could handle the absolute paths.

What do you think?

**Comment by mherrmann** [comment]
I think it's a good idea 👍

**Comment by mherrmann** [comment]
Implemented. Will be released with version 0.5.3, hopefully next week.

**Comment by kszcode** [comment]
Thank you, please make sure that if there is an extra white space at the end or in the beginning to trim that.

Sometime the path gets into clipboard with extra whitespacing.

Thanks!

**Comment by mherrmann** [comment]
I'll ensure it works with extra whitespace @kszcode :)

**Comment by mherrmann** [comment]
Version 0.5.3 is live (finally!).
