### ISSUE TITLE
Dock indicator dot not showing when fman is open

### ISSUE THREAD

**Issue by davemac** [fman-community/fman#176]
On OS X Sierra when fman is open, there is no indicator dot below the fman icon in the dock. In the screenshot below, fman is open.
<img width="203" alt="screenshot 2017-06-12 14 00 58" src="https://user-images.githubusercontent.com/498512/27018942-a0881e18-4f77-11e7-8ffe-d81084c7fb90.png">

**Comment by macosxguru** [comment]
Are you sure that fman is launched? Here is my dock on Sierra with fman launched.

![screen shot 5](https://user-images.githubusercontent.com/1103821/27019324-76edde84-4eec-11e7-90ba-867a6b1d5a04.png)

macosxguru

**Comment by mherrmann** [comment]
I also have the dot. Are you sure fman was open?

**Comment by davemac** [comment]
I now have the dot, whereas yesterday I did not and fman _was_ open. Once difference between yesterday and today is that I was on one screen where now I am on two.

Sorry for the false alarm, but I will keep an eye on this and give more information if it happens again.
