### ISSUE TITLE
Script/program should be run from it's working directory

### ISSUE THREAD

**Issue by edporteous** [fman-community/fman#177]
Running a program (eg. exe, bat in Windows) should first change the current working directory.

**Comment by digozzi** [comment]
+1. Any news on this? It would be essential for windows usage.

**Comment by mherrmann** [comment]
Thx for the reminder @digozzi. I'll squeeze this into the next release in the coming days.

**Comment by mherrmann** [comment]
Implemented in [fman 0.8.7](https://fman.io/changelog#v0.8.7) :)

**Comment by digozzi** [comment]
Great! Thanks for the fast fix! You just sold another license.

**Comment by mherrmann** [comment]
That always makes my day. Thanks!!

**Comment by digozzi** [comment]
Hi Michael, looks like this problem is back. Can you please have a look on this? Running fman v1.2.1. Thanks!

**Comment by mherrmann** [comment]
Fixed in [fman 1.2.2](https://fman.io/changelog#v1.2.2).
