### ISSUE TITLE
Setting terminal emulator for F9

### ISSUE THREAD

**Issue by bremenpl** [fman-community/fman#191]
When I first press F9 the program told me to configure it in Core settings.json. The problem was that this file was not generated for me (I am using linux). In the directory /opt/fman/Plugins/Core I only had:

```
lukasz@Latitude5480:/opt/fman/Plugins/Core$ ls -l Core*
-rw-rw-r-- 1 root root 177 lip  3 11:55 Core Settings (Mac).json
-rw-rw-r-- 1 root root 170 cze 14 13:56 Core Settings (Windows).json
```

So I added the Core Settings (Linux).json file by copying the one from mac. In there I have changed the terminal:
```
{
    "terminal": {
        "args": ["/usr/bin/open", "-a", "TerminalEmulator", "{curr_dir}"]
    },
    "native_file_manager": {
        "args": ["/usr/bin/open", "-a", "Finder", "{curr_dir}"]
    }
}
```

My program for terminal emulation in xubuntu is TerminalEmulator. Now when I press F9 I get an exception:

```
Command 'OpenTerminal' raised exception.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 108, in _run_in_thread
  File "/opt/fman/Plugins/Core/core/commands.py", line 344, in __call__
    open_terminal_in_directory(self.pane.get_path())
  File "/opt/fman/Plugins/Core/core/os_.py", line 10, in open_terminal_in_directory
    _run_app_from_setting('terminal', gnome_default, kde_default, dir_path)
  File "/opt/fman/Plugins/Core/core/os_.py", line 36, in _run_app_from_setting
    Popen(**popen_kwargs)
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1282, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/open'
```

Could you please let me know how to fix this, I could not find any explanation on the website.

**Comment by mherrmann** [comment]
Hi,

I already replied to your question via email - did you receive it? Here is my answer again, so others can find it as well:

The correct path for the file "Core Settings" is at `~/.config/fman/Plugins/User/Settings/Core Settings (Linux).json`. This file should be created the first time you edit a file with F4 and pick a default editor. I recommend you move the file you created from /opt/fman/... to this path.

`/usr/bin/open` is only available on Mac I believe, that's why you are getting the error. I suppose the binary for your terminal is xfce4-terminal. So I would try:

    {
        "terminal": {
            "args": ["/usr/bin/xfce4-terminal", "{curr_dir}"]
        },
        "native_file_manager": {
            "args": ["/usr/bin/thunar", "{curr_dir}"]
        }
    }

You may have to adjust these paths with the output of `which xfce-terminal` and `which thunar`, respectively.

**Comment by bremenpl** [comment]
Hello Michael,
The message went to spam for reason, sorry and thanks. I have moved the content of the file from opt to user directory. Now my file `~/.config/fman/Plugins/User/Settings/Core Settings (Linux).json` looks like this:

```
{
    "terminal": {
        "args": ["/usr/bin/xfce4-terminal", "{curr_dir}"]
    },
    "native_file_manager": {
        "args": ["thunar", "{curr_dir}"]
    },
    "editor": {
    	"args": ["/bin/st", "{file}"]
    }
}
```
The editor works, the F9 doesnt raise exception, but doesnt open the terminal as well. Is the file correct? The path to terminal and thunar are good i have checked.

**Comment by mherrmann** [comment]
Does it work when you invoke `/usr/bin/xfce4-terminal ~` from the terminal?

**Comment by bremenpl** [comment]
No, I think there is an other way of providing directory parameter to the xfce4-terminal, like this:
```
xfce4-terminal --working-directory=~
```

**Comment by bremenpl** [comment]
I tried this now:
```
{
    "terminal": {
        "args": ["/usr/bin/xfce4-terminal --working-directory=", "{curr_dir}"]
    },
    "native_file_manager": {
        "args": ["thunar", "{curr_dir}"]
    },
    "editor": {
    	"args": ["/bin/st", "{file}"]
    }
}
```

On F9 I receive exception:
```
Command 'OpenTerminal' raised exception.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 108, in _run_in_thread
  File "/opt/fman/Plugins/Core/core/commands.py", line 344, in __call__
    open_terminal_in_directory(self.pane.get_path())
  File "/opt/fman/Plugins/Core/core/os_.py", line 10, in open_terminal_in_directory
    _run_app_from_setting('terminal', gnome_default, kde_default, dir_path)
  File "/opt/fman/Plugins/Core/core/os_.py", line 36, in _run_app_from_setting
    Popen(**popen_kwargs)
  File "subprocess.py", line 676, in __init__
  File "subprocess.py", line 1282, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/xfce4-terminal --working-directory='
```

**Comment by mherrmann** [comment]
How about:

    "args": ["/usr/bin/xfce4-terminal", "--working-directory={curr_dir}"]

**Comment by bremenpl** [comment]
Yes this is the solution, thank you a lot for support.

**Comment by mherrmann** [comment]
You're welcome! :)
