### ISSUE TITLE
Qt5 version mismatch on Arch Linux

### ISSUE THREAD

**Issue by dlukes** [fman-community/fman#197]
After updating to `0.5.4-1`, the SSL version mismatch (see #189) is gone, but I now get a Qt5 version mismatch:

```sh
$ /opt/fman/fman
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py", line 46, in <module>
  File "/root/dev/fman/venv/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
ImportError: /opt/fman/libQt5Core.so.5: version `Qt_5.9' not found (required by /opt/fman/PyQt5.QtCore.so)
Failed to execute script pyi_rth_qt5plugins
```

I did a clean reinstall of `fman` and `qt5-base`, but the problem persists... Any ideas?

**Comment by mherrmann** [comment]
Hm, `/opm/fman/libQt5Core.so.5` should not be there. Please try completely removing fman (`pacman -R fman && rm -rf /opt/fman`) then try reinstalling fman.

**Comment by dlukes** [comment]
Ah, yes, that helped, thank you very much for the quick response! Sorry, I figured an uninstall would remove `/opt/fman`, so I didn't try removing it by hand :)

At any rate, maybe wiping the directory should be part of the update process, and uninstall as well?

**Comment by mherrmann** [comment]
Glad it worked :)

Dunno if wiping isn't already the default behavior for pacman. Did you ever make manual changes in `/opt/fman`?

**Comment by dlukes** [comment]
I tinkered with `/opt/fman` when trying to figure out what exactly was wrong with the SSL version...

Right, that makes sense, it didn't occur to me that `pacman` wouldn't do a `rm -rf` on the install dir but instead just remove the files that were explicitly installed :) Thanks again!
