### ISSUE TITLE
Exiting rename with Enter opens file

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#199]
Enter file renaming mode with Shift+F6. Do not rename file, press Enter. After pressing Enter file is opened. Same issue occurs with directories.
I think exiting renaming with Enter should not open file.

**Comment by raguay** [comment]
I've been having this issue some also. It doesn't happen every time for me.

**Comment by mherrmann** [comment]
Fixed. Will be released as part of upcoming version 0.6.0.
