### ISSUE TITLE
Cursor issues on top level

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#200]
Quite some time ago similar issue was fixed, but after few versions it have returned.
On Windows 7 navigate to top level directory, e.g. disk C: . Pressing Backspace (or arrow left, if you have ArrowNavigation plugin) cursor disappears. It actually ends up on (in this case) drive C: item (ExplorerProperties opens C: properties when cursor is hidden).
If you "Go back" on first item in the list, cursor does not disappear, but is indicating wrong item. Pressing "Down" revels real cursor, and you have two cursors on screen.
Seems like trivial issue, but might be dangerous when trying to rename or move wrongly selected item (operation might start on disk, not on directory).

**Comment by mherrmann** [comment]
Fixed in fman 0.6.0 :)
