### ISSUE TITLE
Delete permanently error on Windows

### ISSUE THREAD

**Issue by cr101** [fman-community/fman#204]
Trying to delete a folder permanently on Windows 10 Pro produces the error below:
![screenshot_12](https://user-images.githubusercontent.com/4064582/29008456-80a5b860-7b6b-11e7-9f2c-c0770ee8c6c4.jpg)

**Comment by mherrmann** [comment]
Thanks for pointing this out. I'll look into it when I find the time.

**Comment by mherrmann** [comment]
Fixed in fman 0.6.3. I recorded a [YouTube video](https://www.youtube.com/watch?v=uhIj9B2At28) of the fix / release process!
