### ISSUE TITLE
Select only filename when copying or moving files

### ISSUE THREAD

**Issue by volksen** [fman-community/fman#206]
When selecting a single file and using copy or move (F5/F6) the whole filepath is selected in the popup window.

In 99% of all cases, I only want to change the filename in the new directory. The correct directory is already in the second pane I am copying/moving to.

In my opinion it would be best if only the filename (without extension) would be pre-selected and not the whole filepath.

**Comment by joshas** [comment]
Please vote on this issue: #70

**Comment by mherrmann** [comment]
Thank you for pointing this out @joshas. I'm closing the present issue as a duplicate.
