### ISSUE TITLE
F3 - should be a file preview

### ISSUE THREAD

**Issue by gedovkl** [fman-community/fman#215]
If no default viewer is supplied ask user for viewing app

**Comment by mherrmann** [comment]
Thank you for this suggestions as well. Do you think there will be one viewing app for all file types? Or different apps for different file types?

**Comment by brum** [comment]
hi.
maybe like "editor" in CoreSetting.json, for all file types.  

And customization like:

```
{
	"viewer": {
		"args": ["/usr/bin/micro", "{file}"]
	}
}
```

**Comment by mherrmann** [comment]
I've implemented this now, as a new [plugin](https://github.com/mherrmann/Preview). To install it, press `Ctr+Shift+P` (or `Cmd+Shift+P` on Mac), enter `Install Plugin` and choose the `Preview` plugin from the list. Once it's installed, you can press `F3` to preview files.

If you guys ever need similar functionality in the future, I recommend you check out [fman's plugin API](https://fman.io/docs/plugins-introduction) :) It gives you great power to do such things without having to wait for me to implement them. You can also use the [Preview plugin](https://github.com/mherrmann/Preview) as a nice little example.
