### ISSUE TITLE
Error after installing or removing plug-in until reset

### ISSUE THREAD

**Issue by Raguna163** [fman-community/fman#216]
After installing a plugin, any time a directory changes (up or down), I get an error.

Attempted various combinations of:
- Number of plugins installed
- What plugins were installed (tried 6 different ones)
- Using "Reload Plugins"
- Restarting or not restarting between installs/uninstalls

The only fix is restarting after an install.

![fman](https://user-images.githubusercontent.com/31168881/30242281-88566306-9561-11e7-96b9-95966f4e3e8f.PNG)

Using Windows 10

**Comment by mherrmann** [comment]
I have experienced this myself as well, but am unable to reliably reproduce it. However, I believe I was able to find and fix the cause of the problem. Will go live with upcoming version 0.6.4.
