### ISSUE TITLE
Allow copy path from location bar with hotkey

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#222]
If I ~~double~~ triple click on "location bar" (one above navigation pane) to select current path and press copy hotkey (e.g. Ctrl+C on Windows), I get file or folder name which is under cursor. Could location bar functionality be improved to allow copying path to clipboard with common copy hotkeys? Now I have to right click and select "Copy" from context menu.
Alternative path copying methods are welcome too, e.g. dedicated context menu entry "copy path to clipboard".

**Comment by mherrmann** [comment]
Could you press `Backspace` followed by `F11` to achieve what you want?

**Comment by joshas** [comment]
Yes, this works. I should start reading documentation first, before asking.

**Comment by joshas** [comment]
Just to note, that on macOS F11 by default is mapped to "Show desktop" command and copying path doesn't work in fman.
