### ISSUE TITLE
How to view long file names in fman?

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#224]
Sometimes I run into situation, where I have several files with similar long names, that doesn't fit into name column. While searching for correct file I end up either opening file properties (Get Info on macOS) or entering rename mode and scrolling with cursor keys if necessary.
On Total Commander I was used to copying filename to command line with Ctrl+Enter to quickly see full filename. While this solution is not great, I hope fman might offer better one.

**Comment by mherrmann** [comment]
I can see why that would be useful. The easiest from a current perspective would be a plugin that shows the full name of the current file in the status bar. Would that work for you?

**Comment by joshas** [comment]
@mherrmann Plugin sounds good, but what about those cases when there's some operation in progress, e.g. file copy, which uses statusbar for status updates?
How about classic tooltips on hover over file?

**Comment by mherrmann** [comment]
@joshas that's a good idea. How long are these "long files" you are talking about?

**Comment by mherrmann** [comment]
(Reason I'm asking: I don't want to show tooltips "all the time". Ideally, they would only be shown when the name truly is too long for the column. But that's difficult to implement. So for now, I'm thinking of displaying the tooltip only for names longer than `x` characters.)

**Comment by mherrmann** [comment]
Actually, I am able to implement it so that the tooltip is only shown when the column is too narrow :}

**Comment by mherrmann** [comment]
Implemented in fman 0.6.9 :)
