### ISSUE TITLE
Fuzzy search/filter on the main panes

### ISSUE THREAD

**Issue by rogenaro** [fman-community/fman#233]
Let's say you have a directory with the files:
```
wifi.txt
file.txt
somefile.txt
somethingelse.txt
```
Right now, when I type `f`, `file.txt` would be selected.

My request would be to have a key, akin to `/` in Altap Salamander.
When this key is pressed, anything typed thereafter would be used to focus the first match (using fuzzy search) and allow only the files matching the query to be navigated with the arrow keys.

So, if we type `fi` in this mode, the file `wifi.txt` would be focused, and I would be able to press the `Up`/`Down` keys to navigate between `file.txt` and `somefile.txt` (there could be some visual cues to show which files are filtered in or out).

Pressing `l` after that would place focus on `file.txt`, and allow navigation to `somefile.txt`, removing `wifi.txt` from the match list.

Pressing `Esc`, or manually selecting somethig with the mouse would clear the filter and go back to default mode.

**Comment by mherrmann** [comment]
Thank you for the suggestion. What would you think if it were implemented without requiring you to press `/`? Because that's exactly what the existing issue #41 captures.

**Comment by rogenaro** [comment]
Sounds pretty much what I had in mind!
Could I suggest on top of issue #41 to have a way (a setting or hotkey) to toggle between exact and fuzzy matching (or regex)?
It would be a nice way to filter and select multiple files to do some other operations (move/copy/delete/open/etc).
Thank you!

**Comment by mherrmann** [comment]
Cool. I'll close this issue and continue the discussion in #41.
