### ISSUE TITLE
Tutorial on every launch

### ISSUE THREAD

**Issue by MartyBeGood** [fman-community/fman#235]
On one of my Win10 machines, fman launches the tutorial everytime I open fman.

Is there any way to disable the tutorial/set a config entry to keep this from popping up again?

**Comment by MartyBeGood** [comment]
I figured out the cause of this: Instead of creating a folder called 'Local' with a file called 'Settings.json' in it, a file called 'Local' (no extension) was created with the contents of 'Settings.json'.
Deleting the faulty 'Local' file and copying this over from another fman installation (or in fact, another user profile with admin privileges) fixes the problem.

**Comment by mherrmann** [comment]
Interesting. I have no idea why `Local` was created as a file. I'm closing this issue because I hope it was just a one-time thing.
