### ISSUE TITLE
[Bug] fman 0.7.1: Deleting file/dir while finder is not running error

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#249]
If you have the finder program disabled (completely closed and not running) and delete a file or directory, fman shows that file or directory deleted, but the file or directory is really still there. The issue is that fman uses Finder to delete the file or directory, but can't when it isn't running. But, fman is still removing it from it's internal data structure for showing the files and directories.

**Comment by mherrmann** [comment]
You're right it's not how it should be. The reasons why are rather technical. Unfortunately, it's not so easy to change. But I believe I have a way out.

The best solution imho would be to update the [FlexibleTrash](https://github.com/raguay/FlexibleTrash) plugin. It could check if Finder is running, as it already does. Then, it could run either command `MoveToTrash` or `DeletePermanently`:

    if finder_running:
        self.pane.run_command('move_to_trash')
    else:
        self.pane.run_command('delete_permanently')

**Comment by raguay** [comment]
I've already done that. The FlexibleTrash plugin is working fine with the new version now. The only problem is if someone installs it, the two programs in it are not executable. After installing the plugin, you have to manually fix the execution bits to use the plugin. I need to see how to do that in Python.

**Comment by raguay** [comment]
I mostly added this here so that you would know about the issue. It's not a problem with me personally because of my FlexibleTrash work around.

**Comment by mherrmann** [comment]
I see, okay thanks. In that case I'll close the issue, as I'm now aware of it and don't see much I can do at the moment with reasonable effort.

P.S.: I don't know if you've seen yet but #247 gives hints as to how to migrate existing plugins with the new API. I guess I should have written these instructions sooner / more publicly. Hope they might help now.

**Comment by raguay** [comment]
Yes, I saw #247 and copied the information. I'm working on updating all of my plugins. So far, DeSelect, DuplicateFileDir, favorites, FlexibleTrash, and VimNavigation are working on the new version. Those are my most used plugins for me!

**Comment by mherrmann** [comment]
Okay! Sorry for the trouble. I think it really was necessary to make the API changes but I should have given more notice. I just wanted to finally get the new version out the door after two months without a new release.

**Comment by raguay** [comment]
I'm updating my MoveToDir plugin and this same issue is showing it's ugly head. For instance, if I move a file up one directory using this plugin and specifying the `..` directory, it moves the file just fine. But, fman will not show it until I manually run the `Refresh` command from the Command Pilate.

**Comment by mherrmann** [comment]
fman keeps a cache of files for better performance. The behaviour you are describing @raguay is a (buggy) result of this. I just released fman 0.7.3 that (among [other things](https://fman.io/changelog#v0.7.3)) displays the files from the cache, but also reloads them when you enter a directory again. I tested `MoveToDir` with `..` and it seems to fix the problem.

Another solution to the caching issue is to use functions from the new (and - I'm sorry - not yet documented) `fman.fs` module to move files. This moves the files _and_ updates the cache. I created a PR for `MoveToDir` that uses the new functions. I will also begin updating the [API documentation](https://fman.io/docs/api) now.

**Comment by mherrmann** [comment]
I will close this issue in the meantime. Feel free to reopen it again @raguay if you feel something has not yet been resolved.

**Comment by raguay** [comment]
I'm also seeing this issue when I add/delete files from a script (I'm working on a plugin for script execution, along with npm scripts). The directory doesn't get updated with the changes. You could set a process to watch for changes from the OS and update with it. Similar to watchman. Read this article to see how to do it cross-platform wise:  https://stackoverflow.com/questions/5738442/detect-file-change-without-polling

Just set a hook on directory changing to start watching that directory for file changes. Since you just need to check for the currently viewed directories, it shouldn't be too much of an overhead.

**Comment by mherrmann** [comment]
fman already watches directories, in exactly the manner you described. It doesn't use watchman / watchdog but [QFileSystemWatcher](http://doc.qt.io/qt-5/qfilesystemwatcher.html). Apparently though, this does not always notice all changes. I hope that the fix of release 0.7.3 I described [above](https://github.com/fman-users/fman/issues/249#issuecomment-348979714) already brings some alleviation. A next step would be to also reload directories when fman's window (re-)gains focus. I believe Total Command on Windows does not watch directories at all, for instance, but simply reloads them when its window gets focus. It's on my TODO.
