### ISSUE TITLE
Unzipping files does not work on Linux (invalid cross-device link)

### ISSUE THREAD

**Issue by rasmuse** [fman-community/fman#250]
# How to reproduce

I'm on Ubuntu 16.04 and trying out the new zip capability. Browsing zip files works fine but unpacking contents does not.

```bash
rasmus@eom344:~$ rm a
rasmus@eom344:~$ touch contents
rasmus@eom344:~$ zip my-zip-file.zip contents
```

Now I can open fman and browse `my-zip-file.zip`. Trying to unpack `contents` by putting the cursor on it and pushing F5 to copy to the same dir (`/home/rasmus` in this case), I get the following error:

```
Could not copy zip:///home/rasmus/my-zip-file.zip/contents (invalid cross-device link).
```

# Possible explanation and solution

I guess the zip functionality uses the `/tmp` directory. My `/tmp` is on a different partition than `/home` and thus hard-links cannot be made between `/tmp` and `/home`:

```bash
rasmus@eom344:~$ echo something > /tmp/a
rasmus@eom344:~$ ln /tmp/a ~/a-linked
ln: failed to create hard link '/home/rasmus/a-linked' => '/tmp/a': Invalid cross-device link
```

and just to be complete, they are really on different partitions:

```bash
rasmus@eom344:~$ df /tmp
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda3       57542652 15776464  38820140  29% /
rasmus@eom344:~$ df ~
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/sda5      272009688 112965404 145203932  44% /home
```

Possible solution would perhaps be to copy files instead if a hardlink cannot be made.

(By the way, aren't real users a pain in the ass, having all kinds of funny configurations you didn't have on your test systems? ;) )

**Comment by mherrmann** [comment]
Thank you very much. Your detailed explanation was spot-on and let me fix the bug. I'm just releasing version 0.7.2, which should no longer exhibit it.

And you're totally right. I think users should only be allowed to use systems that are exactly identical to my test systems ;-P

Cheers!
