### ISSUE TITLE
Pane cursor position after returning to parent directory

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#254]
A minor "papercut" issue, but it became visible after 0.7.x update. After returning to parent directory cursor is displayed on top position for a few moments, then it is moved to correct directory. Cursor should show up in correct position right away after changing directory.

**Comment by mherrmann** [comment]
Fixed. Will go live with 0.7.4.

**Comment by mherrmann** [comment]
Fixed in 0.7.4.
