### ISSUE TITLE
fman doesn't start on linux/mint

### ISSUE THREAD

**Issue by tstechly** [fman-community/fman#255]
The app doesn't start at all. No message. Starting from command line doesn't provide any info either.

fman 0.7.3
linux mint 17.2

**Comment by mherrmann** [comment]
I think I broke fman on Ubuntu < 16.04. I will release a new version today that should hopefully fix this issue.

**Comment by mherrmann** [comment]
I just released version 0.7.4 that should hopefully fix this issue. You can obtain the new version via `sudo update-fman`.
