### ISSUE TITLE
OpenDirectory raises exception when trying to open directory with limited permissions

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#273]
On Windows trying to open directory, that belongs to "administrator", e.g. "System Volume Information" - exception is raised. Instead a simple dialog should be displayed with error message "Access is denied". Option to "Open as Administrator" might be useful too.

**Comment by mherrmann** [comment]
Implemented at least a nicer message in [fman 0.8.2](https://fman.io/changelog#v0.8.2). Option "Open as Admin" left for a future release.
