### ISSUE TITLE
fman won't start | Address boundary error

### ISSUE THREAD

**Issue by Snuggle** [fman-community/fman#275]
Hey, there! I just freshly installed `fman` and it won't start. I decided to find where the actual binary was, so that I could get any error output. It won't start because of an address boundary error, apparently. Attached is package information etc.

Totally open to any questions, requests for logs, etc. (No clue where I should look)

Any help is appreciated!

![image](https://user-images.githubusercontent.com/26250962/34300611-c05dc4c2-e720-11e7-9a9d-895ea5584d09.png)

![image](https://user-images.githubusercontent.com/26250962/34300673-05814de4-e721-11e7-9904-5bae60343676.png)

![image](https://user-images.githubusercontent.com/26250962/34300771-8f08b142-e721-11e7-9022-564550b02b3d.png)

**Comment by Snuggle** [comment]
![image](https://user-images.githubusercontent.com/26250962/34300903-3fa3e076-e722-11e7-86b7-a0b08fa73b51.png)

Here's the output from running this through gdb.
```
Starting program: /opt/fman/fman 

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7639860 in raise () from /usr/lib/libc.so.6
(gdb) 
```

**Comment by mherrmann** [comment]
Hey there,

sorry for the trouble. This is an issue with the current versions of fman & Manjaro. If you install fman 0.6.9, I think it should work. Arch Linux users recently had the problem that fman versions < 0.7.0 did not start for them, so I updated fman with the latest Arch binaries. This unfortunately broke it for the current Manjaro build, which lags behind Arch's by a few weeks. My hope is that once Manjaro follows Arch's version, the problem should resolve itself.

**Comment by Snuggle** [comment]
Okiedokie! I hope it works soon. I'll close this when/if this gets fixed, and if not within about a month or so, I'll ping you. c:

**Comment by Snuggle** [comment]
This has just been fixed! Thank you! ❤️

**Comment by mherrmann** [comment]
Glad to hear it! Thanks for letting me know.
