### ISSUE TITLE
fman not starting

### ISSUE THREAD

**Issue by d0tfile** [fman-community/fman#277]
Hello! I have fman installed on Arch Linux (4.14.8-1-ARCH, Gnome, x11). After upgrading fman to 0.8.0-1 (I'm using [AUR](https://aur.archlinux.org/packages/fman/)) I'm getting error:
> /opt/fman/fman: relocation error: /opt/fman/PyQt5/Qt/plugins/imageformats/libqico.so: symbol _ZdlPvm, version Qt_5 not defined in file libQt5Core.so.5 with link time reference

Also I tried package from site, but got same error. Can you help me, please?

**Comment by mherrmann** [comment]
I just released [fman 0.8.2](https://fman.io/changelog) that should hopefully fix the problem. Sorry for the trouble! I broke the package in a release on Friday.
