### ISSUE TITLE
Allow switching panes with Left and Right arrow keys

### ISSUE THREAD

**Issue by fox8091** [fman-community/fman#278]

**Comment by raguay** [comment]
Load the plugin "SwapPanels". It flips the panels to left on the right and right on the left. It's binds the shift-p key stroke.

**Comment by fox8091** [comment]
I don't mean flipping the panels, I mean switching _between_ them. You know, what Tab does.

**Comment by mherrmann** [comment]
I just released [fman 0.8.2](https://fman.io/changelog) which makes this possible. To get the behaviour you asked for, please [update fman](https://fman.io/docs/automatic-updates) and install [this plugin](https://github.com/mherrmann/SwitchPanesWithArrowKeys).

**Comment by fox8091** [comment]
Thanks! It works. However, the dialog is still there about it being impossible to change it currently.

**Comment by mherrmann** [comment]
Good point! Thanks. I will update the message in the next release.
