### ISSUE TITLE
Show drive name in drive select window

### ISSUE THREAD

**Issue by fox8091** [fman-community/fman#279]

**Comment by mherrmann** [comment]
I implemented a very rudimentary form of this in [fman 0.8.2](https://fman.io/changelog#v0.8.2). Can I ask you to [update fman](https://fman.io/docs/automatic-updates) and let me know what you think?

**Comment by fox8091** [comment]
Seems to work. Also, one more suggestion that kind of falls under this as well, perhaps hide empty drives by default? (Noticeable when, for example, you plug in an all-in-one media card reader and only have one SD card inserted)

**Comment by mherrmann** [comment]
Thanks. I created a follow-up issue (#283) for hiding empty drives.
