### ISSUE TITLE
MoveToTrash Error

### ISSUE THREAD

**Issue by P1nk13P1** [fman-community/fman#281]
Hello, I am using Fman like 2 months (yesterday buy licence, because like it) and now I am making free space on my external HDDs, wanted to remove in root directory of my one partition on one HDD, wanted to remove empty directory, but I got error while removing called "Command 'MoveToTrash' raised error." 
![snimka](https://user-images.githubusercontent.com/20891196/34467685-c8460d72-eef8-11e7-8e00-0c6b301df968.PNG)
Tried more times, no success, I can remove it why Windows File Explorer, but I need to open another File Explorer, and I dont wanna open another program, if can I give more information (Using: Windows 10, 64 bit) Thanks for help

**Comment by mherrmann** [comment]
Hi Martin,

many thanks for getting a license and sorry for the bug. The error code would normally indicate that you don't have enough rights to delete the file / directory. Are you sure it's working with Explorer?

Best,
Michael

**Comment by P1nk13P1** [comment]
Ou. Yes, thanks for help, I dont mind, that I needed to use administration rights, after it its normally remove the directory, only want to say, if its there way to remove it without administration rights, really thanks for the tip. Martin

**Comment by raguay** [comment]
Should at least give a nicer warning message that you don't have permission instead of an trace dump! Then have a button to switch to super user permissions. That is the way more file managers work it.

**Comment by mherrmann** [comment]
Okay, so if I understand you correctly Martin, then admin rights were required. Then @raguay is right and fman should have given a nicer message "Access denied - try with admin privileges?" instead. That should be the goal of this issue.
