### ISSUE TITLE
Use xdg-open to open the native file manager on Linux

### ISSUE THREAD

**Issue by jhasse** [fman-community/fman#284]
I've just tried fman on Ubuntu MATE 17.10 and pressing F10 won't open my native file manager but tell me to configure it. It would be great if this wasn't required and fman would use `xdg-open {curr_dir}` instead, as that should work for most (if not all) desktop environments.

**Comment by mherrmann** [comment]
Interesting, I did not know this. I just implemented your suggestion. It will be released with the next version of fman (usually in a couple of days). You will be notified of the new version [automatically](https://fman.io/docs/automatic-updates).

**Comment by mherrmann** [comment]
Implemented in [fman 0.8.3](https://fman.io/changelog#v0.8.3). :)

**Comment by jhasse** [comment]
Thanks for the fix :)

Unfortunately it doesn't seem to work for me (just updated fman via apt) - same Popen error message as before. Do I need to reset the settings or something first?

**Comment by mherrmann** [comment]
When you initially encountered the problem, did you fix it by editing the settings?

**Comment by jhasse** [comment]
No (where are the settings btw? Typing "setting" in the command pallet yields no results).

**Comment by mherrmann** [comment]
Here is the revant page of fman's documentation: https://fman.io/docs/terminal. The file you want to look at is `~/.config/fman/Plugins/User/Settings/Core Settings (Linux).json`. Does it contain an entry for `native_file_manager`?

**Comment by mherrmann** [comment]
Re-opening this issue until it's confirmed fixed.

**Comment by jhasse** [comment]
The file doesn't exist:

```
$ tree ~/.config/fman
/home/jhasse/.config/fman
├── Local
│   ├── Cache
│   │   └── Icons
│   ├── Metrics.json
│   └── Session.json
└── Plugins
    └── User
        └── Settings
            ├── Panes (Linux).json
            └── Visited Paths (Linux).json

6 directories, 4 files
```

**Comment by mherrmann** [comment]
Then you have the default settings and for some reason the way fman launches `xdg-open` does not work. Are you still getting the `Please configure` error?

**Comment by mherrmann** [comment]
(Sorry it's not working btw)

**Comment by jhasse** [comment]
> Are you still getting the Please configure error?

Yes, exactly like before with 0.8.2.

> (Sorry it's not working btw)

No problem ;) Must be quite some work for you to support Linux in the first place.

**Comment by mherrmann** [comment]
Ah, I think I know why. Let me fix this for the next version of fman.

**Comment by mherrmann** [comment]
[fman 0.8.6](https://fman.io/changelog) is out. Can you let me know whether it fixes the issue for you @jhasse ?

**Comment by jhasse** [comment]
Yes, works perfectly! Thank you very much :)

**Comment by mherrmann** [comment]
Cool! Thx for letting me know :-)
