### ISSUE TITLE
Plugin 'Core' failed to load - RuntimeError: Font '[...]Open Sans.ttf' could not be loaded.

### ISSUE THREAD

**Issue by mattijskersten** [fman-community/fman#285]
First time fman user. New install on Windows 10 fails to start. The following error message is shown. I have checked and the Open Sans.ttf file is present in the indicated location. When trying to open the ttf file using Windows Font Viewer, I get an error that it's not a valid font file (same for Roboto Bold.ttf)
Have tried to uninstall, re-download and re-install multiple times.

Plugin 'Core' failed to load.

Traceback (most recent call last):
  File "fman\impl\plugins\plugin.py", line 130, in load
  File "fman\impl\plugins\plugin.py", line 138, in _load
  File "fman\impl\plugins\plugin.py", line 151, in _load_font
  File "fman\impl\font_database.py", line 9, in load
RuntimeError: Font 'C:\\Users\\[user]\\AppData\\Local\\fman\\Versions\\0.8.2\\Plugins\\Core\\Open Sans.ttf' could not be loaded.

**Comment by mattijskersten** [comment]
Local issue. I'm not able to open any ttf files.

**Comment by mherrmann** [comment]
Okay. Thanks for the report!

**Comment by mavy0313** [comment]
Facing same issue on Windows 10, @hootanoogie how did you fix it?
