### ISSUE TITLE
Allow sorting of files using keyboard commands/shortcuts

### ISSUE THREAD

**Issue by CameronBanga** [fman-community/fman#288]
Attempted to write a plugin for this, but I'm a very bad programmer, and it doesn't look like there's a way to implement it with current API regardless.

Please feel free to close if a duplicate, I searched and didn't see one, but may have missed.

Would love the ability to change sort order via the Command Palette. Very frequently, I'll want to sort differently based on the directory I'm looking at. From what I can tell, the only way to do this currently is by clicking on a column header, which is no fun. 

If it would be possible via a plugin, if you could point me at right part of the API docs, etc, I'll fiddle with it myself. But from what I found, didn't seem possible without maybe using the PyQt framework, and that seems to be discouraged in the docs.

**Comment by mherrmann** [comment]
Hi Cameron,

everything you said is correct. The API at the moment does not make it possible to do this. It might be possible to hack something together with PyQt, but it would be highly discouraged.

I love your initiative. Let me look into this and get back to you.

M

**Comment by mherrmann** [comment]
I'm adding a command that lets you select the sort column with a quicksearch dialog:

![image](https://user-images.githubusercontent.com/1076393/34648123-0ad194fa-f394-11e7-9a78-15946488efba.png)

If the selected column is already the current sort column, then the order is reversed (ascending <-> descending).

@CameronBanga under which name(s) would you expect to find the command in the Command Palette?

**Comment by macosxguru** [comment]
Wouldn't it make sense to have the command in the Command Palette named **Sort By…** ?

macosxguru

**Comment by mherrmann** [comment]
Released in [fman 0.8.3](https://fman.io/changelog#v0.8.3) as **Sort By Column** :) To sort by the first, second or third column respectively, press `Ctrl/Cmd + F1/F2/F3` :)

**Comment by CameronBanga** [comment]
@mherrmann This is awesome! I think I'd probably expect the command as Sort, at least that was what  I had looked for first personally, and what I had planned to call my plugin. 

Thanks for this, just made fman much more valuable personally. +1

**Comment by mherrmann** [comment]
Glad to hear you like it! I don't think it's a big problem if it's called `SortByColumn` because the Command Palette suggests it anyways as soon as you type "Sort".
Cheers

**Comment by CameronBanga** [comment]
Just saw your release notes for 0.8.3 and that you called it SortByColumn, I think that's great/perfect. Probably a better title than just sort anyways.
