### ISSUE TITLE
[Bug] List Plugins: Dies if Plugin.json is missing.

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#289]
I was editing a plugin and it did not have the Plugin.json file since I was creating it. I happened to run the `list plugins` command (I believe this is an internal command) and it gave an error message saying the file did not exist. This could error more gracefully.

**Comment by mherrmann** [comment]
I just fixed this. Will go live with 0.8.5.

**Comment by mherrmann** [comment]
Fixed in 0.8.5.
