### ISSUE TITLE
Feature request: Copy file name

### ISSUE THREAD

**Issue by nojaf** [fman-community/fman#291]
It be nice to have next to `Copy to clipboard` and `Copy paths to clipboard` a command that copies the file name (without the full path) to the clipboard.

**Comment by raguay** [comment]
The command is `copy_paths_to_clipboard` and it is tied to F11 on the Mac (I think that is the default for all oses actually).

**Comment by nojaf** [comment]
Yes, except I don't want the entire path, only the filename.

**Comment by raguay** [comment]
Okay. Just created a plugin for you. Install the `getfilename` plugin and you will have a command `get file name` that will copy the name of the current file/directory to the clipboard without the path. It should work for all oses. You can bind it to a hotkey by setting the hotkey to the command `get_file_name`. Have fun.

**Comment by nojaf** [comment]
@raguay wow thanks man! What an amazing response time. 
Gratitude!
