### ISSUE TITLE
fman only displays generic file icons on XFCE (Arch)

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#293]
@kek91, didn't you once say you were on Xubuntu?

**Comment by kek91** [comment]
Yes Michael, that's correct. I've since changed to Ubuntu but I can fire up a VM if you need some testing

**Comment by mherrmann** [comment]
Thanks - do you remember if you got proper icons when you were still on XFCE?

**Comment by kek91** [comment]
No I can't remember, sorry. I looked through old screenshots but I could only find from Pantheon/Gnome/Windows environments ofcourse... :)

**Comment by IgorKrupenja** [comment]
Could not reproduce on my Xubuntu setup.

fman: 1.0.2
xfce: 4.12
Xubuntu: 16.04

**Comment by mherrmann** [comment]
Thank you @krupenja! Then I will close this issue for now.

**Comment by cit** [comment]
I have the same issue with archlinux. There are only two icons that are display: folder and generic icon. I'm running fman version 1.5.9 in archlinux. I changed the icons in lxappearance and in qt5ct but without any effect.

![2019-05-08-@09-07-00-scrot](https://user-images.githubusercontent.com/114687/57356577-0d4e7700-7171-11e9-814f-4814550db07d.png)

If you need some more information, I'm happy to help.

**Comment by mherrmann** [comment]
And you're on XFCE @cit?

**Comment by cit** [comment]
@mherrmann I have xfce installed but I mainly use i3.

**Comment by mherrmann** [comment]
And the problem occurs with both?

**Comment by cit** [comment]
Ah it seems to occur only in i3wm and not xfce. See attached.

![2019-05-08-130753_1174x716_scrot](https://user-images.githubusercontent.com/114687/57371276-9e821580-7192-11e9-8e05-1e964b8991a4.png)

**Comment by mherrmann** [comment]
Okay. (I'm on Debian/Xfce myself and am not experiencing the problem either.

I'll open a new issue.
