### ISSUE TITLE
[Request] macOs: Hide to dock (CMD+M) adding

### ISSUE THREAD

**Issue by kolnogorov** [fman-community/fman#295]
Hello! First of all, i want to say thanks for the best file manager tool of all times!
And i wanted to ask, are you going to add CMD+M hide to dock option for macos?
Thank you once again! :)

**Comment by mherrmann** [comment]
Thank you for the kind words :-) It should be easy enough to do this. I'll try to get it into the next release.

**Comment by mherrmann** [comment]
Implemented :-) Will go live with fman 0.8.8.

**Comment by mherrmann** [comment]
Released as part of [fman 0.8.8](https://fman.io/changelog#v0.8.8).
