### ISSUE TITLE
error when attempting to install fman

### ISSUE THREAD

**Issue by wpirtle** [fman-community/fman#299]
I am getting a 404 at this address when installing fman on Windows 10. https://update.fman.io/support/installer/?hl=&product=%7B91F6D922-553C-4E18-8991-53B3A925ACDA%7D&error=2&from_extra_code=1&guver=1.3.99.0&m=0&os=10.0&sp=&iid=&brand=&source=gethelp&testsource=auto

**Comment by mherrmann** [comment]
Sorry for the trouble. You should have also seen a dialog similar to this one:

![image](https://user-images.githubusercontent.com/1076393/35614785-7e8a7f9e-0670-11e8-9487-3a65d111313b.png)

What did it say?

**Comment by wpirtle** [comment]
After rebooting my pc fman installed correctly.

Thanks,

Wayne

**Comment by mherrmann** [comment]
Okay :-) If the issue occurs again, please do let me know.
