### ISSUE TITLE
[Request] Duplicate file

### ISSUE THREAD

**Issue by kolnogorov** [fman-community/fman#303]
Hi, i am sorry if i missed something and gorgeous fman does have this feature yet, but if it doesn't, could you please add it in some future versions?

I mean, duplication file in the current category.

Thank you!

**Comment by mherrmann** [comment]
It's available as a plugin: [DuplicateFileDir](https://github.com/raguay/DuplicateFileDir) :-) For instructions on how to install it, please see [here](https://fman.io/docs/installing-plugins).
