### ISSUE TITLE
Cannot merge directory contents

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#306]
Test scenario:
left pane contents: one directory named "dir1" (/target/dir1/)
right pane contents: one directory named "dir1" containing another directory "dir2" with single file "test.txt" (/source/dir1/dir2/test.txt).
I expect that copying dir1 from source will copy all directories and files to target directory and I'll end up with /target/dir1/dir2/test.txt .
Currently while trying to copy dir1 I get "Could not copy /source/dir1/ (no such file or directory). Do you want to continue?" message, with single "OK" button.
If file is in dir1 - copy operation succeeds.
Tested on macOS and Ubuntu Linux.

I hope you'll be able to reproduce issue. I could make video if my description is not detailed enough.

**Comment by mherrmann** [comment]
> I hope you'll be able to reproduce issue. I could make video if my description is not detailed enough.

The description was perfect. I just implemented a fix for the bug. Will go live with version 0.8.9.

**Comment by mherrmann** [comment]
Fixed in 0.8.9.
