### ISSUE TITLE
Cisco AMP thinks fman is a virus

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#309]
The main reason for this seems to be that fman's installer modifies a system directory: `\WINDOWS\Tasks\fmanUpdateTaskUserS-1-5-21-1202660629-583907252-1801674531-500Core.job`. This is an artifact of the [auto-update mechanism](https://fman.io/docs/automatic-updates) on Windows. The reason this bug is important is because a large corporation reported it, and can't start using fman (potentially on many machines!) until it is fixed.

**Comment by kek91** [comment]
It's been blocked here as well in our Palo Alto firewall.

![2018-02-13 14_49_17-virus_spyware download blocked](https://user-images.githubusercontent.com/1431734/36153002-2ff97f4e-10cd-11e8-8af2-f2ce13e5479b.png)

**Comment by mherrmann** [comment]
Thanks. This is a real pain!

**Comment by nblackburn** [comment]
https://www.virustotal.com/#/file/678edd2dd1b8868aaf5b19edfb9f3ae7332e7fe163e51ced305b0130934b50bc/detection

![image](https://user-images.githubusercontent.com/2931085/36849458-07f4de4e-1d5c-11e8-8639-f98019c82778.png)

**Comment by mherrmann** [comment]
After thinking about this, I will no longer treat antivirus tools (except for Microsoft's) marking fman malware as problems of fman. It's their fault, not mine. I wrote up my thoughts in a [blog post](https://fman.io/blog/fman-and-antivirus/).
