### ISSUE TITLE
Directories not displayed in zip archive

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#311]
Opening this file https://github.com/jquery-validation/jquery-validation/releases/download/1.17.0/jquery-validation-1.17.0.zip in fman shows only files, no directories. Extracting with Finder works as expected.

**Comment by mherrmann** [comment]
Fixed in [fman 0.9.6](https://fman.io/changelog#v0.9.6).

**Comment by jspohr** [comment]
Hi, I think I'm seeing a related issue. In the attached ZIP, there are 4 directories inside the "archive" directory (include, linux, mac, windows). fman only shows 3, "windows" is missing. Using 1.6.4 on Windows. Opening and extracting with WinRAR yields all 4 directories.
The ZIP was created by Jenkins on a Ubuntu server using the "get artifacts in ZIP" feature.
[archive.zip](https://github.com/fman-users/fman/files/3465020/archive.zip)
Thanks for looking into this!

**Comment by mherrmann** [comment]
Sorry for the trouble @jspohr. I've created a new issue for this: #676
