### ISSUE TITLE
Natural sort of numbers within text

### ISSUE THREAD

**Issue by klutchnikoff** [fman-community/fman#321]
Is it possible to sort files with the nutural order as does the "-v" option of "ls"?

**Comment by mherrmann** [comment]
Hi Nicolas,

do you mean like #84?

**Comment by klutchnikoff** [comment]
Hi Michael,

Yes, exactly!

**Comment by mherrmann** [comment]
Okay! That isn't implemented yet, I'm afraid. If it's important to you, you can leave a thumbs-up 👍 on the issue so I can update its priority.

**Comment by mherrmann** [comment]
But I think I just found a way of implementing it :-) Will go live with 0.9.0.

**Comment by klutchnikoff** [comment]
Great to hear ;-)
