### ISSUE TITLE
FuzzySearch plugin error

### ISSUE THREAD

**Issue by DoctorCocoBean** [fman-community/fman#325]
Installed the FuzzySearchFilesInCurrentFolder plugin and I get this error message whenever I try to open a file (windows 8, 64x):

 <img src=https://pre00.deviantart.net/4068/th/pre/i/2018/050/5/9/fman_plugin_error_by_doctorcocobean-dc3qnj4.jpg></img>

Thank you so much if you can help. Love fman btw!

**Comment by raguay** [comment]
Hi, I fixed the plugin and sent a merge request. My fork of the repository has the fixed code if you want to try it out before he merges it in:  https://github.com/raguay/FuzzySearchFilesInCurrentFolder

**Comment by DoctorCocoBean** [comment]
Wow that was fast haha. Thanks!!! It works now.

**Comment by mherrmann** [comment]
Closing this issue :-)

**Comment by kszcode** [comment]
Thank you @raguay, I did merge the pull request

**Comment by raguay** [comment]
No problem. It was an easy fix.
