### ISSUE TITLE
[Windows] Cut moved all the files without the folders

### ISSUE THREAD

**Issue by elsassph** [fman-community/fman#326]
Maybe I did a wrong manipulations, but for my first try of cut&paste of a folder, instead of moving the folder I chose as-is, it started moving each individual file flat in the target folder. 

Is it a "feature" I mistakenly used, or a bug?

**Comment by mherrmann** [comment]
Hi and sorry for the trouble,

so you cut the file in Explorer and pasted into fman?

**Comment by elsassph** [comment]
No, in fman directly - though I've been trying again but it didn't happen. It's entirely possible that I did a wrong manipulation but that was entirely within fman.

**Comment by mherrmann** [comment]
Okay so if I understand correctly, you saw this once but it's not reproducible now?

**Comment by elsassph** [comment]
Yes, I suppose it should be closed but I'm confused how it can even happen.
