### ISSUE TITLE
Cannot quit fman with cmd+Q in macOS.

### ISSUE THREAD

**Issue by ekarious** [fman-community/fman#327]
Hello,

It is been a few release now than i noticed the disabled `quit fman` in mac menu. The shortcut `cmd+Q` does not work either.

I am currently using fman 9.0.
Is this happening to someone else too ?

**Comment by mherrmann** [comment]
I'm only seeing this when the splash screen is shown (the dialog saying "please buy a license"). Do you also experience this once you've closed the dialog?

![untitled](https://user-images.githubusercontent.com/1076393/36524615-debc149e-17a6-11e8-86a8-fd3b2cce82a8.jpg)

**Comment by ekarious** [comment]
I still do not have bought a license. I will soon as i want to truly invest myself in the wonderful app but in the meanwhile, after closing the "buy a license" dialog, the quit menu item still stay disabled.
I can currently close the app with the dock icon.

i may need to reinstall the app from scratch to test.

**Comment by mherrmann** [comment]
Strange, okay. Thank you for letting me know!

**Comment by ekarious** [comment]
You're welcome :)

**Comment by mherrmann** [comment]
I can reproduce this now:

1. Click the fman menu in the top bar while the splash screen is shown
2. Close the splash screen

Now the `Quit` entry in the menu is still disabled and `Cmd+Q` has no effect.

**Comment by mherrmann** [comment]
Seems to be related to [this bug in Qt](https://forum.qt.io/topic/79992/qt-5-8-main-menu-items-disabled-in-osx/15).

**Comment by mherrmann** [comment]
Further research shows that the problem appears whenever _any_ dialog is open. If the user clicks on the menu while this is the case, then the `Quit` entry is disabled. What's more, the entry stays disabled even after the dialog is closed. Then, also `Cmd+Q` has no effect and the only way to close fman is either via the `Quit` command in the Command Palette, or by clicking on the "close window" button in the top left corner of the window. Dialogs where this happens include:

 * the splash screen at startup
 * the Command Palette
 * the prompt asking you where to copy a file 
 * etc.

**Comment by mherrmann** [comment]
![screen1_cropped](https://user-images.githubusercontent.com/1076393/36603606-98cd5d74-18bb-11e8-9ed1-3ef83029f113.png)
![screen2_cropped](https://user-images.githubusercontent.com/1076393/36603607-9900b9c6-18bb-11e8-9bbf-d3f3a5fe57b6.png)

**Comment by mherrmann** [comment]
I will fix this for now by at least making `Cmd+Q` work. I'll open a separate issue for the (Qt-caused) bug that the `Quit fman` menu item is disabled.

**Comment by ekarious** [comment]
Okay, i understand. Thank you for your time :)

**Comment by mherrmann** [comment]
[fman 0.9.1](https://fman.io/changelog#v0.9.1) is out. It makes `Cmd+Q` work again.
