### ISSUE TITLE
Improved activation flow

### ISSUE THREAD

**Issue by nblackburn** [fman-community/fman#333]
The current process of activating the software is tedious and not very user friendly so it would be nice to work on improving this going forward.

One option would be to detect User.json inside the application as a special file and when double clicking on it, registers the application

Alternatively you could register a custom URI protocol allowing for one click activation of the software removing the need to download any license files.

fman://activate/dGhpc2lzYXJlYWxseWxvbmdsaWNlbnNla2V5Zm9yZm1hbg==

**Comment by mherrmann** [comment]
Hi Nathaniel,

thank you for the suggestion.

> One option would be a simple file picker that allows users to select the license file they downloaded which then registers it in the right location for them.

Isn't that pretty much what the `Install license key` command does?

**Comment by nblackburn** [comment]
@mherrmann Not quite because it still makes asssumptions as to where it needs to be for it to work making it counter-intuitive.

Instead because this is a file manager after all, perhaps detect `User.json` inside the application as a special file and when double clicking on it, registers the application.

Obviously this would work better as a file format specific to fman.

**Comment by mherrmann** [comment]
Okay :) I implemented it now so that when you "open" the license key file in fman, it asks whether you want to install it. Further, the `Install License Key` command lets you browse for the file if it isn't present in the current directory. (Previously, the command simply said "license key file not found".)

**Comment by nblackburn** [comment]
Great, thanks for getting this done.

**Comment by mherrmann** [comment]
(Implemented now in [fman 0.9.5](http://fman.io/changelog#v0.9.5).)

**Comment by Akamaozu** [comment]
This is a great improvement.

Really awesome to see fman improve so much. Keep up the good work, @mherrmann!

**Comment by mherrmann** [comment]
Thank you @Akamaozu!! Always great to hear encouraging feedback :-)
