### ISSUE TITLE
fman doesn't open on mac OS High Sierra 10.13.3 (17D102)

### ISSUE THREAD

**Issue by dacarras** [fman-community/fman#334]
Hi Michael, 

I updated Mac OS one day ago, and this morning the application was working fine. Yet, I restarted the machine and the application stopped working.

Hi guess is interacting with the last mac update.
I'm attaching a copy of the crash log.

[mac_log_20180227.txt](https://github.com/fman-users/fman/files/1763347/mac_log_20180227.txt)

**Comment by mherrmann** [comment]
Thank you Diego and sorry for the trouble. Does [the previous fman version](http://download.fman.io/0.9.0/fman.dmg) work? If yes, you may have to [disable fman's automatic updates](https://fman.io/docs/automatic-updates) until I am able to fix the problem.

**Comment by dacarras** [comment]
Partially. I tried to reinstall a previous version, but the "install plugin" command is not working either.
I'm attaching that crash log as well.

[plugin_log_20180227.txt](https://github.com/fman-users/fman/files/1763396/plugin_log_20180227.txt)

**Comment by mherrmann** [comment]
Yes, `Install Plugin` not working is because of a macOS update. The new version (which completely crashes for you now) was meant to fix this problem. The annoying thing is that it does not crash for me (so I cannot reproduce it). Still looking into it...

**Comment by mherrmann** [comment]
@dacarras, I prepared a [snapshot version of fman](https://www.dropbox.com/s/22ng8vwwrdbhmor/fman.dmg?dl=1) with a fix attempt. Does it work for you? I must admit it's a shot in the dark, I'm trying to rule out the cause of the problem.

**Comment by dacarras** [comment]
It doesn't work either.

**Comment by mherrmann** [comment]
Pity, okay. I did two things in 0.9.1 that could be the cause of this issue:

1. I updated fman's Python version from 3.5 to 3.6
2. I updated PyInstaller, the library which is used to turn fman's source code into a standalone executable, to a new version.

The snapshot version reverted 2. Looks like I'll have to revert 1. as well... I'll keep you updated.

**Comment by mherrmann** [comment]
@dacarras I uploaded a [new version](https://www.dropbox.com/s/22ng8vwwrdbhmor/fman.dmg?dl=1). Can you let me know whether it works for you?

**Comment by dacarras** [comment]
Now is working!
Thanks Michael!

**Comment by mherrmann** [comment]
Okay, great. Thanks for letting me know! New release coming up...

**Comment by mherrmann** [comment]
fman 0.9.2 is out and should hopefully fix the problem. You can obtain it (as usual) from https://fman.io/download.
