### ISSUE TITLE
Cannot delete file/folder

### ISSUE THREAD

**Issue by svlcode** [fman-community/fman#336]
It seems that a few seconds after deleting a file or a folder, the file/folder appears again. 
I use fman v 0.9.3 on Windows 10.

**Comment by mherrmann** [comment]
Sorry for the trouble. I fixed this. Will go live with release 0.9.5.

**Comment by mherrmann** [comment]
Fixed in [fman 0.9.5](http://fman.io/changelog#v0.9.5).
