### ISSUE TITLE
fman won't start on Centos

### ISSUE THREAD

**Issue by ababak** [fman-community/fman#337]
After typing "fman" it just exits immediately without any errors and any trails in the logs. "fman --help" works as expected (shows version number and usage info).

Is there anything that can be done to make it work on Centos?

Thanks.

CentOS Linux release 7.4.1708 (Core)
fman version 0.9.5

**Comment by mherrmann** [comment]
First, I'm afraid I need to say that CentOS is currently not supported. So I can't spend much time right now helping with this. Second however, you may be able to get more output by running `/opt/fman/fman`.

**Comment by ababak** [comment]
Here's the output:
```
 babak  ~  /opt/fman/fman
[4511] Error loading Python lib '/opt/fman/libpython3.6m.so.1.0': dlopen: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/fman/libpython3.6m.so.1.0)
 babak  ~  255  ls -la /lib64/libc.so.6
lrwxrwxrwx. 1 root root 12 Dec 15 11:28 /lib64/libc.so.6 -> libc-2.17.so
 babak  ~  

```

**Comment by ababak** [comment]
It's a pity as I had to move from Windows to Centos on my main computer. I was sure it should work with Centos as PyInstaller seems to support it. Hope you'll be able to have a look one day.

**Comment by oskretc** [comment]
@mherrmann , Can we vote on this feature to be implemented?

**Comment by mherrmann** [comment]
Sure, just leave a thumbs-up :+1: on the issue description.

**Comment by mherrmann** [comment]
Does it work now @ababak? In other words, does fman start for you on CentOS and I can close this issue?

**Comment by ababak** [comment]
Yes! Thank you!

**Comment by mherrmann** [comment]
My pleasure :-)
