### ISSUE TITLE
Add option to download fman zipped for Windows

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#338]
In some cases it would be useful to have semi-portable version of fman, without installer and auto updates. Please add download option of fman in a zip.

**Comment by mherrmann** [comment]
Hi, I believe this is a duplicate of #82 so I'm closing this issue. Feel free to re-open if you think it's not a dupe.

**Comment by joshas** [comment]
My issue is that I would like to download fman without installer to run it from any directory I'd like. Currently only option for Windows is to download installer, install fman and only then move it to different directory, and finally uninstall version installed by installer :)

**Comment by mherrmann** [comment]
That's what I understood :-) I updated #82 to make it clear that you'd like a Zip file.

**Comment by tmssngr** [comment]
I agree that it is not a real duplication. Allow to unzip fman to any directory (or move later) but keep the settings at the central settings directory (except fman's directory structure has been modified to form a portable bundle, e.g. by having a settings directory).

**Comment by mherrmann** [comment]
I see. But what would be the use case for that?

**Comment by tmssngr** [comment]
More confidence in fman that it does not store arbitrary stuff somewhere on the system. For me, I prefer "movable" applications very much over those I _need to install_. Maybe too long macOS usage... ;)

**Comment by mherrmann** [comment]
No I understand that. But the scenario you described: portable version of fman as a .zip, which stores settings not in the "installation" dir but in the normal [data directory](https://fman.io/docs/data-directory). What's the advantage of that over a .zip that stores settings in the installation (=unzip) dir?

**Comment by tmssngr** [comment]
It is the same as on macOS: you are free to decide where to "put" the application and even can change your mind later. A portable application is not multi-user-capable, but a "moveable" application is. A portable application is just a special kind of "moveable" application that does not save the settings in a user-specific directory, but in its own directory structure.

**Comment by mherrmann** [comment]
I see! I created a new issue for this now (#423).

**Comment by Akamaozu** [comment]
> My issue is that I would like to download fman without installer to run it from any directory I'd like. Currently only option for Windows is to download installer, install fman and only then move it to different directory, and finally uninstall version installed by installer :)

Wish this info was easier to find. 
Thanks for this, @joshas :)

**Comment by RoyiAvital** [comment]
In the mean time, is there a way to decompress the `exe` file without installing?

**Comment by RoyiAvital** [comment]
I created a fork with that option. See https://github.com/mherrmann/fman/issues/920.
