### ISSUE TITLE
Strange labels ColumnWrapper

### ISSUE THREAD

**Issue by kiddten** [fman-community/fman#339]
![image](https://user-images.githubusercontent.com/9250239/37307305-8ba80e80-264b-11e8-9a51-9bcbe365672d.png)
I've just installed fman, pressed ctrl+shift+p, chosed `sort by column` and getting pic related?
Isn't it should be actual column names name, size, modified?

**Comment by mherrmann** [comment]
Eh, you are right. I will fix this in the next release.

**Comment by mherrmann** [comment]
Fixed in [fman 0.9.6](https://fman.io/changelog#v0.9.6).
