### ISSUE TITLE
Use ~/.config data dir if available on Mac

### ISSUE THREAD

**Issue by mwean** [fman-community/fman#342]
Hi! I was wondering if it would be possible to use `~/.config/fman` as the data directory on Mac if it's available. This would work better with dotfile repos, and I think it fits with the concept of the app. Thanks!

**Comment by mherrmann** [comment]
Hey Matt, couldn't you just symlink `~/.config/fman` to fman's normal data directory `~/Library/Application Support/fman`?

**Comment by mwean** [comment]
Sure, I just thought it would be a nice option to have. I've had some weird things happen when I've symlinked settings for other apps.

**Comment by mherrmann** [comment]
I see :-) In this case, I hope you don't mind if I close this issue as wontfix. It's a pretty special requirement and if the user can solve it with something as simple as creating a symlink, then I consider it out of scope for fman. Don't let this deter you from opening other issues though!

Cheers,
Michael
