### ISSUE TITLE
zip contents not displayed in fman

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#343]
I got some strange zip files, when opened in fman 0.9.8 on macOS they appear empty - no files, nor directories. Extracting with Finder works as expected. zipinfo also displays all files.
Is there any way I could check zip properties, version, etc. to report to you, because I cannot send you that particular zip file.

**Comment by mherrmann** [comment]
Can you describe the rough folder/file structure in the Zip file? You don't have to give the real file names. Eg.:

 * root/
   * subdir/
     * file.txt
   * file2.txt

I suspect that none of the root folders contains a single file.

**Comment by joshas** [comment]
File structure is like this, I just had to redact a few items (changed file names, hide dates and file sizes), hope that won't interfere with investigation.
````
Archive:  archive.zip   XXXXXXXXX   3
-rw----     4.5 fat XXXXXXXX bx stor XXXXXXXXX DIR_V2/01_DIR/file1.mp4
-rw----     4.5 fat XXXXXXXX bx stor XXXXXXXXXX DIR_V2/01_DIR/file2.mp4
-rw----     4.5 fat  XXXXXXXX bx stor XXXXXXXXXXX DIR_V2/01_DIR/file3.mp4
3 files, XXXXXXXXX bytes uncompressed, XXXXXXXXX bytes compressed:  0.0%
````
What I noted after comparing with another zip - this file is missing directory entries, as separate "files".

**Comment by mherrmann** [comment]
> What I noted after comparing with another zip - this file is missing directory entries, as separate "files".

That is precisely the cause of the problem. :-)

**Comment by mherrmann** [comment]
Maybe some more interesting detail: fman internally uses 7-Zip via the command line. If you say "give me all files in archive.zip/dir" it's very slow. The reason for this is that 7-Zip doesn't just give you dir/file.txt but also dir/subdir/subdir/file.txt. You can say "exclude dir/subdir/*" to get around this. But! If dir/subdir doesn't have a directory "entry" like you mentioned, 7-Zip doesn't give it to you.

**Comment by mherrmann** [comment]
I just released [fman 0.9.9](https://fman.io/changelog#v0.9.9) that should fix the issue. If it still doesn't work with your Zip file @joshas, please let me know.

**Comment by joshas** [comment]
Glad to report, that zip contents are displayed correctly in fman 0.9.9

**Comment by mherrmann** [comment]
Great! Thank you for letting me know :-)
