### ISSUE TITLE
libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by WhispersOfJ** [fman-community/fman#345]
It was working when I was on Ubuntu yesterday.

Came back to Arch because I get bored very easily.

Installed it from the FMAN repo and this is the error I get when I try and load it.

`libgcc_s.so.1 must be installed for pthread_cancel to work`

I am sure this is something easy I am overlooking, but for the life of me I cannot think of what to do.

**Comment by mherrmann** [comment]
Hm, I just tested on an up-to-date Arch KDE VM and it works for me:
![image](https://user-images.githubusercontent.com/1076393/37814740-db56810a-2e6b-11e8-8cd8-23e61946c98f.png)

There are a couple of Google results for the error you quoted. Can they help?

**Comment by WhispersOfJ** [comment]
Whatever it was, it was on me and not fman at all. All is well now after a wipe and reinstall.

**Comment by mherrmann** [comment]
Happy to hear it's working for you now :-)
