### ISSUE TITLE
Column 'Modified' raised error

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#346]
Here's a strange one. Got it while messing with Windows 10 network drives. fman version 0.9.8
![error](https://user-images.githubusercontent.com/79141/37929376-81730ba6-3148-11e8-93de-bc2be1f312e1.png)

**Comment by mherrmann** [comment]
I don't think this can happen anymore since [fman 1.0.0](https://fman.io/changelog#v1.0.0). Based on this assumption, I'm closing this issue. If it does occur again for you @joshas, please do reopen!

**Comment by jnsl** [comment]
![image](https://user-images.githubusercontent.com/1777928/56907629-f2ab3c80-6aa4-11e9-84cd-247ed15e6a55.png)

That's in fman 1.5.8. Culprit is a file created by a smart tv on a USB drive, missing the file modified attribute. Attached it for testing.
[cm0013_2.zip](https://github.com/fman-users/fman/files/3128147/cm0013_2.zip)

**Comment by mherrmann** [comment]
Sorry @jnsl I don't understand how this can happen. Did you make any changes to fman's source code (i.e. the Core plugin), or to the screenshot?
