### ISSUE TITLE
[bug] source and destination on install screen should be swiped

### ISSUE THREAD

**Issue by ZuBB** [fman-community/fman#349]
See screen

Most of apps I have installed in Macos have a source (what to install) on the left side and destination (where to install) on the right. 

For fman due to some reason it is swiped..

<img width="598" alt="screen shot 2018-03-31 at 14 10 27" src="https://user-images.githubusercontent.com/597016/38162650-b0072d00-34ed-11e8-9e05-e2d699049151.png">

**Comment by mherrmann** [comment]
Thank you for the suggestion! I'll implement this in the next release.

**Comment by mherrmann** [comment]
Implemented in [fman 1.0.0](https://fman.io/blog/fman-10-ten-times-faster/) :)
