### ISSUE TITLE
Limited functionality since 0.9.9

### ISSUE THREAD

**Issue by MartyBeGood** [fman-community/fman#352]
This is a weird one.

On one of my Win10 machines, fman's functionality is pretty limited since the update to 0.9.9. 
- It won't open non-exe files by pressing enter. However, editing files with the configured editor (via pressing F4) works fine
- It won't open the native explorer via any of the methods (F10 or Ctrl+Shift+P -> open native file manager)
- It won't open the default or a configured terminal (again, tried every method fman gives me)

On the other one, everything works as expected.

I've tried reinstalling fman and deleted the fman directories in AppData/Local and AppData/Roaming before reinstalling.

**Comment by mherrmann** [comment]
Hi Markus,

sorry for the trouble. I browsed through fman's source changes betwen 0.9.8 and 0.9.9 and found nothing that could explain this. Does it also happen when you start fman as admin?

M

**Comment by MartyBeGood** [comment]
No worries :) Thanks for reacting so quickly!

Unfortunately, launching fman as admin doesn't help.

TBH, I noticed this behaviour on 0.9.9, but maybe this problem has been there a bit longer because I haven't used that particular machine in a while.

Is there any way I can provide you with additional data so you can get a better look into what's going on?

**Comment by mherrmann** [comment]
Sorry I've been out of touch. I've been busy finishing version 1.0.0.

Do <kbd>F9</kbd> and <kbd>F10</kbd> also not work when you are at `C:\`?

**Comment by MartyBeGood** [comment]
Not a problem ;) I really appreciate all the work you put into fman!

Correct, when I'm at C:\ in either pane and press <kbd>F9</kbd> or <kbd>F10</kbd>, nothing happens

**Comment by MartyBeGood** [comment]
Whoops, this one's on me (or rather something I did to my PC).

I installed [clink](https://mridgers.github.io/clink/), and activated the autorun capabilities of that. Essentially it adds bash-style completion to the cmd. And apparently it interferes with fman's way of interacting with the cmd, because all of the issues I had with fman disappeared the second I deactivated clink autorun.

**Comment by mherrmann** [comment]
Happy to hear it, thank you for letting me know Markus. I had looked at this issue again last week but couldn't make any further sense of it. Glad to hear it's resolved!
