### ISSUE TITLE
Filter and Change address

### ISSUE THREAD

**Issue by oskretc** [fman-community/fman#353]
Hi,

Just started with fman, let me first say that I really like it.

There are a couple of things that will love to have.

1. Filter: Assume that you are in a folder with lots of folders and files and you dont remember the whole file/folder name, you start typying and a regex will filter out to your search. 
2. When Ctrl+P The default text should be the current panel address, that way you can change some parts of the address and go quickly to another folder. e.g. c:\2016\04\01,  you can change only 2016 to 2015 to get to the same mont and day but on another year.

**Comment by mherrmann** [comment]
Hi,

thank you for the feedback and the kind words. I'm happy to hear you like it!

1. is #41. You can leave a :+1: there to affect its priority.
2. I can see why you prefer it that way but am worried about the following: When you open GoTo, the current implementation shows the most visited directories. With your suggestion, it would show the folders in the current directory instead. My suspicion is that the former is more often useful. 

You can get what you want for 2. in the following ways:

1. Click on the location bar with the mouse.
2. Write a small plugin that does it. If you want me to show you how, just let me know :-)

**Comment by oskretc** [comment]
Just +1 on #41 

The 1 solution for 2 works like a charm. Is there any key binding instead of a mouse click. Alt+D is very commonly used in other "explorers"

**Comment by mherrmann** [comment]
I'm sorry there's no keyboard shortcut for #1. You'd have to write a plugin for that. If you want me to help you do this, let me know!

**Comment by mherrmann** [comment]
I published a [plugin](https://github.com/mherrmann/ChangeLocation) now that lets you do 2. with <kbd>Alt/Cmd+D</kbd>. For instructions how to install it, see [here](https://fman.io/docs/installing-plugins). Enjoy!

**Comment by oskretc** [comment]
Great, I'm going to make it my default Ctrl+P   its easier to backspace and then you are like normal Ctrl+P

**Comment by ianxtreem** [comment]
This is another must have for me.  fman has great potential, but seriously, if typing is used to select something filtering is a must.   it is issues like this that make me always close fman and go back to explorer, it has a filter field at least

**Comment by mherrmann** [comment]
@ianxtreem I understand, thank you for the feedback. I believe the feature you are mentioning is actually this issue: #41. I am aware that this would be useful (I'd also like to have it myself). Because it's one of the most-requested features, it will likely be implemented in the coming months.
