### ISSUE TITLE
Empty zip in macOS

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#356]
When I try opening this zip with fonts ( https://www.fontsquirrel.com/fonts/neris , click on "Download OTF" ) on macOS I only get empty pane.
Finder extracts its contents correctly, zipinfo shows correct file structure. Same archive works with same version on fman in Linux. Probably some issue specific to macOS?

**Comment by mherrmann** [comment]
I cannot reproduce this but think know what causes the problem. I just implemented a fix. Will go live with 1.0.2.

**Comment by mherrmann** [comment]
Should be fixed in [fman 1.0.2](https://fman.io/changelog#v1.0.2). Can you please confirm this @joshas?

**Comment by joshas** [comment]
@mherrmann Yes, I can see zip contents with fman 1.0.2. Thank you.
