### ISSUE TITLE
When creating new folder, prefill it's name dialog with currently selected folder.

### ISSUE THREAD

**Issue by MikiGrit** [fman-community/fman#358]
As described in the title. Same behaviour as in Total Commander.

**Comment by mherrmann** [comment]
Thank you for the good suggestion. I implemented this now. Will go live with the next release. I will post here again once it's available.

**Comment by MikiGrit** [comment]
Great, thanks for such a fast response. I thought this shouldn't be very difficult :).

**Comment by mherrmann** [comment]
Yup, it isn't. Always happy to increase the usefulness of fman :)

**Comment by mherrmann** [comment]
Released as part of [fman 1.0.0](https://fman.io/blog/fman-10-ten-times-faster/) :)
