### ISSUE TITLE
Archive created using pack command not shown until refresh

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#367]
Setup:
fman v1.0.0 running as Administrator on Windows 10 Home x64, build 16299.371.

Steps:
1.  Create an archive using "Pack to archive" command (Alt+F5).

Result:
The archive is created correctly. However, the archive is not shown in the other pane until you send a Refresh command (Ctrl+R). No such issue with copying/moving files.

**Comment by mherrmann** [comment]
Thank you for reporting this. The bug does not seem to appear on Linux. But I can reproduce it on Windows.

**Comment by mherrmann** [comment]
Fixed. Will go live with version 1.0.1.

**Comment by mherrmann** [comment]
Fixed in [fman 1.0.1](https://fman.io/changelog#v1.0.1).
