### ISSUE TITLE
[Question] custom data location / selection behavior 

### ISSUE THREAD

**Issue by kwonoj** [fman-community/fman#368]
Not sure if here's an appropriate place for questions, let me know if I need to move to somewhere else.

I purchased fman and trying to customize few behaviors, and currently hitting below 2, may I get some helps?

1. File selection behavior via spacebar
: Spacebar does toggle selection currently - Is there way to configure it to `select next` files? For example, keep pressing spacebar will select files in dir from where it started.

2. Data location customization
: This is mostly cause I have multiple machines on different platforms, but would like to share some common configs (i.e fonts, or some plugins etcs) but I couldn't think of simple way to sync those between. Is there way to specify data location separately, and I can keep single configurations across machines?

Thanks in advance.

**Comment by mherrmann** [comment]
Hi OJ,

Here is fine. Thanks for purchasing a license!

1. You can assign a keyboard shortcut to the `move_cursor_down` command with parameter `toggle_selection`. If you need help with this, let me know.

2. Other users have achieved this with symbolic links. So you could symlink fman's data directory (or your Settings plugin) into (say) your Dropbox folder.

Hope that helps?

**Comment by kwonoj** [comment]
Thanks. For 2, I'd like to avoid symlink as it is bit flaky on windows systems. If there's way without symlink it'd be much appreciated.

**Comment by raguay** [comment]
I use my Favorites plugin to access the same subdirectory structures on different systems. For example, Dropbox folder on one system is at a different location on another system. But, the same favorite is shareable across the systems to get to the store locations quickly.

**Comment by kwonoj** [comment]
@mherrmann @raguay not sure if I understood correctly. My q was about portable config / data - does favorite plugin you mentioned is for those?

**Comment by raguay** [comment]
It's a portable bookmarking plugin. Not really application configuration,
but the bookmarks of most used locations that is portable across different
systems. I use four computers on my desktop (three Macs and a Linux system)
using a shared keyboard and mouse. All of them have the same directory
structure under Dropbox, but the top levels are of course different.
Favorites allows you to save named bookmarks of locations to got to easily.
With the setting of base directories, but bookmarks are easily synced
across systems and used everywhere.

But, no, it's not for application config files and plugins sharing. That
would be more involved.

**Comment by kwonoj** [comment]
For me bookmark is not a really specific concern.

**Comment by kwonoj** [comment]
@mherrmann Mind if I can get some help for 1 meanwhile? I did try to setup in `Key Bindings.json`
```
[
  {
    "keys": [
      "space"
    ],
    "command": "move_cursor_down"
  }
]
```
but this was just overriding toggle selection to down, instead of combination of select -> move next.

**Comment by mherrmann** [comment]
@kwonoj please try

    [
      {
        "keys": [
          "space"
        ],
        "command": "move_cursor_down",
        "args": {"toggle_selection": true}
      }
    ]

**Comment by mherrmann** [comment]
In the interest of clarity, I am closing this issue and creating a new one for just 2.
