### ISSUE TITLE
cmd.exe opens when trying to open a file with spaces in the filename.

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#369]
Setup:
fman 1.0.1, Windows 10 x64 Home

Steps:
1. Open fman.
2. Navigate to a folder containing a file with spaces in its name (e.g. `C:\te st.pdf`).
3. Try opening that file (either by double-clicking or pressing Enter).

Result:
The file will not open. Instead, it opens a command prompt window.

![image](https://user-images.githubusercontent.com/26354715/39077597-decb057a-450b-11e8-8489-a0fa01e4496b.png)

**Comment by mherrmann** [comment]
I cannot reproduce this but have a good idea what could be causing it for you. I just implemented a fix. Will go live with 1.0.2.

**Comment by oskretc** [comment]
I'm able to reproduce it, and if you use my sublime helper plugin you get something like this.

![image](https://user-images.githubusercontent.com/4963991/39123956-ef10b58e-46f9-11e8-8d46-a847d22e9f26.png)

**Comment by vovcacik** [comment]
This is caused by fman when calling `start "te st.pdf"` instead of `start "" "te st.pdf"`. The extra quotes are documented as optional but they are not. This is well known [bug][] in cmd.exe.

[fman#369 calling cmd-start without extra quotes.zip](https://github.com/fman-users/fman/files/1938597/fman.369.calling.cmd-start.without.extra.quotes.zip)

[bug]: https://ss64.com/nt/start.html

**Comment by mherrmann** [comment]
@vovcacik yes, that was the cause of the bug. The fix I mentioned above, which I already implemented, is to add the empty quotes you mention. Looking at your #372 though, it may turn out that I won't be able to use `start` after all. We'll see.

**Comment by mherrmann** [comment]
I just released [fman 1.0.2](https://fman.io/changelog#v1.0.2) that fixes this problem. I still have to tackle #372.

**Comment by vovcacik** [comment]
It does, thanks.

**Comment by mherrmann** [comment]
Happy to hear it's fixed :)
