### ISSUE TITLE
Copy to removable drive returns access denied

### ISSUE THREAD

**Issue by ianxtreem** [fman-community/fman#375]
When trying to copy a file to a flash drive the error access denied is returned.  File can be copied using either File Explorer or TeraCopy without problem.
- Windows 10
- Occurs when running fman at user level and as administrator

**Comment by IgorKrupenja** [comment]
can confirm: reproducible on Win 10 x64 Home with fman 1.0.2

**Comment by IgorKrupenja** [comment]
Upon some more research I think the problem is a bit more general. I get this problem when I try to copy the file to *the root of any drive*, even C:\ and even if fman is run as an Administrator. I can easily copy files to directories though, even on removable drives and even if fman is *not* run as an Administrator.

**Comment by mherrmann** [comment]
Wow you are right. Thank you for reporting this and the great triaging @krupenja and @ianxtreem. I will fix this in the next release in the coming days.

**Comment by mherrmann** [comment]
Fixed in [fman 1.0.3](https://fman.io/changelog#v1.0.3) :)

**Comment by IgorKrupenja** [comment]
This has re-appeared in f-man 1.0.9 but only for external (non-C) drives. Just try to copy a file *to the root of* an external drive. I can reproduce this with a micro-SD card and a virtual VeraCrypt volume. Copying files to non-root directories works. Interestingly, copying a *folder* to the root of an external drive works fine.

**Comment by mherrmann** [comment]
Reopening...

Which error do you get @krupenja?

**Comment by IgorKrupenja** [comment]
This:
![image](https://user-images.githubusercontent.com/26354715/40974142-55755be4-68cf-11e8-90e0-4df0ab87b7dd.png)

**Comment by mherrmann** [comment]
Thanks! I'll take a look.

**Comment by mherrmann** [comment]
Fixed. Will go live with fman 1.1.1.

**Comment by mherrmann** [comment]
Fixed in [fman 1.1.1](https://fman.io/changelog#v1.1.1).
