### ISSUE TITLE
fman incorrectly decodes URL-encoded characters in file names

### ISSUE THREAD

**Issue by matangover** [fman-community/fman#376]
When a filename contains a URL-encoded character such as `%2F` or `%20`, fman incorrectly decodes it, and any operation on that file fails. To reproduce, create a file named "test%2F" and try to open it, copy it, or move it.

And yes, there really are files which contain these characters in the wild, I didn't just try to find bugs in fman. 😄

**Comment by matangover** [comment]
This creates very confusing and "dangerous" situations. E.g. I have a file named `test%2Fhello` and a folder named `test` with a file named `hello` in it. Trying to open/copy/move `test%2Fhello` will actually operate on `test/hello`.

**Comment by mherrmann** [comment]
This was a bug in fman 1.0.0 and was mean to be fixed in [fman 1.0.1](https://fman.io/changelog#v1.0.1). Which version are you on? You can find out by running "About" via the Command Palette.

**Comment by matangover** [comment]
Whoops thanks! I was using 0.9.9.
