### ISSUE TITLE
Bottom rows of pixels of a filename obscured when editing the name

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#378]
Steps:
1. Press Shift + F6 to rename a file.
2. Try entering a name with underscores.

Result:
The bottom rows (perhaps one or two) of pixels are obscured. Not a big deal but gets slightly confusing if you start entering underscores as they remain completely obscured:

![image](https://user-images.githubusercontent.com/26354715/39319785-c6464306-498a-11e8-84c0-50022c46fff6.png)

This is on Windows 10 Home x64, fman 1.0.2. Not reproducible on my Xubuntu system.

**Comment by mherrmann** [comment]
Thank you for reporting this Igor. God, the screenshot you sent would look so much better without the "NOT REGISTERED" in the window title ;-)

**Comment by IgorKrupenja** [comment]
yep, I get the idea ;) will buy as soon as get my Paypa problem sorted - thank you so much for your app :)

**Comment by mherrmann** [comment]
;) My pleasure :-) I fixed this issue now in [fman 1.0.3](https://fman.io/changelog#v1.0.3) :)
