### ISSUE TITLE
Avast thinks fman is a virus

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#379]
The reason given is `Win32:Malware-gen`.

**Comment by amartens181** [comment]
Might it be Omaha 🤔

**Comment by mherrmann** [comment]
Yes, probably. But the main reason isn't fman's(/Omaha's) binary per-se. It's that anti virus software ... [sucks](https://www.theregister.co.uk/2017/01/27/gag_free_ex_mozilla_dev_joins_antivirus_roasting_chorus_its_poison/). It's in the interest of antivirus vendors to flag (especially non-widespread) software as "potential malware". Not because it is; But because then the antivirus tool can say "look how many threats I just saved you from!".

The only solution really I think is for fman users who experience this problem to mark fman as safe in the respective antivirus tool. Then it becomes "known" and antivirus vendors eventually trust it.

**Comment by amartens181** [comment]
Yeah. Avast scans every file for 15 seconds when my app downloads them... I can't imagine anyone actually using Avast...

**Comment by amartens181** [comment]
@mherrmann  Just today Windows Defender started classifying my Omaha CrashHandler.exe as a Trojan:Win32/Ditertag.B

**Comment by mherrmann** [comment]
You mean fman's CrashHandler.exe? Or are you using Omaha for one of your own projects?

**Comment by amartens181** [comment]
@mherrmann The Omaha one. Yesterday I scanned GoogleCrashHandler and the [history](https://www.virustotal.com/#/file/617def10fb5cd04434532e2803f07489a82494f76dc177e0ce7e8c70f66729c0/relations) shows that it isn't doing too well in the actual tests.

**Comment by jwedel** [comment]
Today Symantec flagged fman.exe as malware, found „Trojan.Gen 2“

**Comment by mherrmann** [comment]
Thanks @jwedel.

After thinking about this, I will no longer treat antivirus tools (except for Microsoft's) marking fman malware as problems of fman. It's their fault, not mine. I wrote up my thoughts in a [blog post](https://fman.io/blog/fman-and-antivirus/).

Closing this issue.
