### ISSUE TITLE
[Blocker] Cannot install fman on Windows 10

### ISSUE THREAD

**Issue by svlcode** [fman-community/fman#380]
I had fman 1.0.0 installed for a while, without updating it. Then I uninstalled it and tried to install the latest version (1.0.3). During the installation I receive the following error: https://i.imgur.com/AO2XE85.png

**Comment by mherrmann** [comment]
I wonder if this wasn't just an intermittent issue. Does the problem still occur when you try installing now @svlcode?

**Comment by svlcode** [comment]
Unfortunately this problem still occur.

2018-04-30 16:46 GMT+03:00 Michael Herrmann <notifications@github.com>:

**Comment by svlcode** [comment]
In managed to install version 1.0.7 without issues. Problem seems fixed!

**Comment by mherrmann** [comment]
Happy to hear it! :)
