### ISSUE TITLE
"Open terminal in current directory" poses security breach

### ISSUE THREAD

**Issue by disco-fella** [fman-community/fman#382]
"Open terminal in current directory" command runs cmd.exe using relative path. This approach poses security breach: if current working directory a contains malicious cmd.exe file (hidden one likely), the command runs this malicious file instead of running Windows' cmd.exe in C:\System\.

**Comment by mherrmann** [comment]
Great catch, thank you. I fixed this now. Will go live with release 1.0.4.

**Comment by mherrmann** [comment]
Fixed in [fman 1.0.4](https://fman.io/changelog#v1.0.4).
