### ISSUE TITLE
fman 1.0.3: Current directory being deleted

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#383]
I was rebuilding my web application when fman sent up an error message. Fman was sitting in the dist directory of the project. But, when you do a complete recompile, it deletes that directory. Fman should just calmly move up a directory like other file managers.

fman version 1.0.3 will give the following error message:

FileSystem 'LocalFileSystem' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/plugin.py", line 386, in iterdir
  File "/Applications/fman.app/Contents/Resources/Plugins/Core/core/fs/local/__init__.py", line 39, in iterdir
    for entry in Path(self._url_to_os_path(path)).iterdir():
  File "pathlib.py", line 1049, in iterdir
  File "pathlib.py", line 371, in wrapped
FileNotFoundError: [Errno 2] No such file or directory: '/Users/raguay/Dropbox (Personal)/Richard/rag/JavaScript/NotePad/dist'

**Comment by raguay** [comment]
This also is happening if the fman panel is in the parent directory and the child is deleted. For example, fman is sitting in the project directory that has the dist directory in one panel and in the dist directory on the other panel. Both panels start opening error alerts for the dist directory being deleted during the build process.

In this case, fman should just remove the directory from the list in the panel without complaining.

**Comment by mherrmann** [comment]
Thanks for the report Richard. I fixed this now. Will go live with 1.0.4.

**Comment by mherrmann** [comment]
Fixed in [fman 1.0.4](https://fman.io/changelog#v1.0.4).

**Comment by mherrmann** [comment]
(Will be live in a few minutes.)
