### ISSUE TITLE
[BUG] Fman Crashes after browsing a plugins folder and Uninstall that plugin

### ISSUE THREAD

**Issue by oskretc** [fman-community/fman#386]
fman v1.0.4

OS: Windows 7

Ctrl+Shift+P  -> List Plugins
- Select any plugin
Ctrl+Shift+P -> Uninstall Plugin
- Select same plugin as step before.

fman crashes.

**Comment by mherrmann** [comment]
Thank you for reporting this. I was only able to reliably reproduce the issue with the DropboxConnect plugin. The bug is now fixed in [fman 1.0.5](https://fman.io/changelog#v1.0.5).
