### ISSUE TITLE
API Function to handle "Per Folder Location Settings"

### ISSUE THREAD

**Issue by oskretc** [fman-community/fman#393]
Fman and some plugins use (or could benefit from using) per folder settings.

e.g. Visited Paths.json

Functions to read and write to that file in the easiest way. 

A standard settings format will also be useful, something like the following:

```json
{
  "[path]": [
    {
      "key1": "value"
    },
    {
      "key2": "value"
    }    
  ]
}
```

DirectoryPane class could have functions like:

* DirectoryPane.get_path_settings()
    * should return a dictionary with settings associated with the particular path
* DirectoryPane.set_path_settings(dict)
    * Should update the values in the settings file for the current directory

**Comment by mherrmann** [comment]
Thank you for the suggestion. Can't you just very easily implement this yourself with fman's built-in [`load_json(...)`](https://fman.io/docs/api#load_json) and [`save_json(...)`](https://fman.io/docs/api#save_json) command?

**Comment by oskretc** [comment]
Yes, but isn't it the purpose of the API to make it easy for the developers to implement use cases instead of handling data, also, instead of every developer implementing such code in different ways, the API can implement it once and make it super efficient and fast.

**Comment by mherrmann** [comment]
There are many many different use cases. If I implement them all in the API, it will become very complex. So complex in fact that it will be more difficult for new developers to learn, thus missing the whole point of being simple.

Speed and efficiency for storing path-associated properties should not be an issue, it's a very easy computation.

You agreed that it would be easy to implement the functionality yourself with the existing API. In light of this, I'll take the liberty and close this issue. Do feel free to comment again and we can re-open if necessary. But if it already is possible and easy, then I think my time is better spent on other, more important issues.

**Comment by oskretc** [comment]
I'll give you no benefit and close it myself. :simple_smile:

**Comment by mherrmann** [comment]
:laughing: thanks!
