### ISSUE TITLE
No padding between rows on Windows 10

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#395]
In fman v1.0.8 on Windows 10 rows have no padding between them.

![windows10](https://user-images.githubusercontent.com/79141/40575435-b142065a-60ed-11e8-9a25-d2a88f3777a5.png)

**Comment by mherrmann** [comment]
I don't fully understand this issue. The screenshot you sent looks okay to me. Is this something that changed with 1.0.8 (compared to eg. 1.0.7)? Or did you install fman on a new machine and find it looks different there? If yes, that may be to do with High DPI displays, not exactly Windows 10.

**Comment by joshas** [comment]
Take a closer look at folder icons - there are no space between them. List would look much better if there would be at least two pixels margin between icons.
Windows scaling is set to 100%, so it is probably not High DPI issue. Using latest Windows 10 1803, might have been some changes there though.

**Comment by IgorKrupenja** [comment]
I was able to reproduce this with 1.0.8. However, I see this problem *only if* after launching the fman window opens on a monitor with *100% scaling* (i.e. non-HiDPI). Reproducible on both single- and dual-monitor setups.

If fman window opens on a monitor with different scaling (tried 125% and 150%), then the spacing between folders/files looks ok:
![image](https://user-images.githubusercontent.com/26354715/40626705-ef4c1b94-62c2-11e8-96eb-f134d8ebf222.png)
I hope the screenshot is helpful. Note that there are several lines of background pixels between the folder icons. Again, this applies to both single- and dual-monitor setups.

Not sure how it worked pre-1.0.8 as I haven't used a 100% scaling monitor in months until today.

Note that there is a workaround *but only if you have several monitors and one of them is >100% scaling*:
1. Launch fman.
2. If fman opens on a monitor with 100% scaling (and there is no spacing then), move the fman window to the monitor with >100% scaling (125%, 150%, etc.).
3. Then, you can move the fman window back to your monitor with 100% and there will be spacing between folders/files.
Sounds weird but works :)

EDIT: non-reproducible on Linux.

**Comment by mherrmann** [comment]
> Take a closer look at folder icons - there are no space between them.

Now I get it, thanks!

Also thank you for your research @krupenja. Very interesting how it changes with the scaling. And that the workaround works!

**Comment by mherrmann** [comment]
Fixed in [fman 1.0.9](https://fman.io/changelog#v1.0.9).
