### ISSUE TITLE
File selection on space not working

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#396]
Steps:
1. Open fman 1.0.8 on Windows.
2. Press space on a file or folder.

Result:
Nothing happens, file/folder is not selected.

**Comment by mherrmann** [comment]
I cannot reproduce this. Perhaps there is a problem with your local configuration? You can test this by closing fman, renaming your [data directory](https://fman.io/docs/data-directory), then starting fman again.

**Comment by IgorKrupenja** [comment]
Yep, renaming the data directory did the trick. I reinstalled all my plug-ins and added all my custom settings and hotkeys to the new config but do not have this problem anymore. Weird, but I think this can be closed then :)

**Comment by mherrmann** [comment]
Happy to hear it's working :-)
