### ISSUE TITLE
Exception when trying to open a remote directory (SharePoint)

### ISSUE THREAD

**Issue by ghost** [fman-community/fman#397]
When trying to open a remote folder on a Sharepoint, I get the following error:
```
Command 'GoTo' raised error.

Traceback (most recent call last):
  File "fman\impl\plugins\command_registry.py", line 97, in _execute_command
  File "C:\Users\XXX\AppData\Local\fman\Versions\1.0.8\Plugins\Core\core\commands\__init__.py", line 935, in __call__
    self.pane.set_path(url)
  File "fman\__init__.py", line 122, in set_path
  File "fman\impl\widgets.py", line 108, in set_location
  File "fman\impl\model\__init__.py", line 33, in set_location
  File "fman\impl\plugins\mother_fs.py", line 105, in resolve
  File "C:\Users\XXX\AppData\Local\fman\Versions\1.0.8\Plugins\Core\core\fs\local\__init__.py", line 96, in resolve
    return as_url(Path(path).resolve())
  File "pathlib.py", line 1109, in resolve
  File "pathlib.py", line 186, in resolve
OSError: [WinError 1] Incorrect function: '\\\\my.sharepoint.com\\sites\\folders\\docs
```

This issue is surely linked to a previous one (#320). I am able to apply a workaround by changing the resolve function in `fman\Versions\1.0.8\Plugins\Core\core\fs\local\__init__.py` to:
```
def resolve(self, path):
	if not path:
		raise filenotfounderror(path)
	path = self._url_to_os_path(path)
	if PLATFORM == 'Windows':
		is_unc_server = path.startswith(r'\\') and not '\\' in path[2:]
		if is_unc_server:
			# Python can handle \\server\folder but not \\server. Defer to
			# the network:// file system.
			return 'network://' + path[2:]
	return as_url(path) # Changed from as_url(Path(path).resolve())
```

OS: Windows7 SP1 x64
Fman version: 1.0.8, but issue has occurred on earlier versions

**Comment by mherrmann** [comment]
Thank you for the detailed report. Why are you so sure it's linked to #320? The error is different. Also, the present issue is about a remote folder, whereas #320 is about a virtual drive.

**Comment by ghost** [comment]
I 'm not sure at all, I just thought that because the error appears at the same place and the same change solved both issue.

**Comment by mherrmann** [comment]
I see, thanks for clarifying :) The change you made to the code effectively disables the `resolve(...)` functionality, that's I believe why it fixes both cases. I will look into this.

**Comment by mherrmann** [comment]
Can I ask you for a favor @Orokh? I don't have access to SharePoint. Can you
 1. Download and install [Python 3.6](https://www.python.org/downloads/release/python-365/).
 2. Start the Python console from the start menu
 3. Type the following commands:

```
from pathlib import Path
Path(r'\\my.sharepoint.com\sites\folders\docs').resolve())
```

What do you see?

**Comment by ghost** [comment]
Sure, here's the output:
```
>>> Path(r'\\my.sharepoint.com\sites\folders\docs').resolve()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\pathlib.py", line 1139, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python36-32\lib\pathlib.py", line 193, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 1] Incorrect function: '\\\\my.sharepoint.com\\sites\\folders\\docs'
```

**Comment by mherrmann** [comment]
Great, many thanks. So the error is the same. I was hoping it would go away with Python 3.6. fman currently uses 3.5 and I know that #320 is fixed by Python 3.6. Your comment shows that the same fix won't work for this issue. Thanks!

**Comment by ghost** [comment]
Hey,

I came back to fman after a few months. To me, it looks like the issue is solved: I've tried several Sharepoints sites / folders, and got no error at all. Even the delays when opening the folders are much better than they were, and fman is a breeze to use for me now :)

So closing this issue now.

Thanks for all !

**Comment by mherrmann** [comment]
Happy to hear it! :)
