### ISSUE TITLE
Custom keyboard shortcuts don't seem to work

### ISSUE THREAD

**Issue by nojaf** [fman-community/fman#398]
Hi, I've create the following file at `C:\Users\nojaf\AppData\Roaming\fman\Plugins\User\Settings\​Key Bindings.json`

```json
[
	{ "keys": ["Ctrl+N"], "command": "go_to" },
	{ "keys": ["Ctrl+Shift+A"], "command": "command_palette" }
]
```

But it is not getting picked up, what could I be missing here?

**Comment by mherrmann** [comment]
Did you restart fman or use the Command Palette to invoke the command `Reload plugins`?

**Comment by nojaf** [comment]
Tried both, no luck

**Comment by mherrmann** [comment]
I just tried on both Windows and Linux and the key bindings you posted worked there. Are you sure the file is at the location you posted?

**Comment by nojaf** [comment]
Yes, 
![image](https://user-images.githubusercontent.com/2621499/40622859-e621549a-62a3-11e8-83f0-dd785e2e0af9.png)

**Comment by mherrmann** [comment]
And when you edit `C:\Users\nojaf\AppData\Local\fman\Versions\1.0.8\Plugins\Core\Key Bindings (Windows).json` instead and restart fman?

**Comment by nojaf** [comment]
No luck, any logs I can check?

**Comment by mherrmann** [comment]
> any logs I can check?

Not for this I'm afraid, no.

Maybe the keys are being caught by another application and never reach fman? What happens when you use a different shortcut, eg. "Ctrl+O" instead of "Ctrl+N"?

**Comment by nojaf** [comment]
Hmm, there was something weird with my file, the file `C:\Users\nojaf\AppData\Local\fman\Versions\1.0.8\Plugins\Core\Key Bindings (Windows).json` existed twice in that folder. Really unsure how that is even possible.
I ended up removing my file and modified the original file.
It works now.

**Comment by mherrmann** [comment]
Happy to hear it :-) I'm not sure what you mean by the "original". If you mean the one in fman's installation directory, be careful: That gets automatically overwritten when fman is updated to a new version.

**Comment by nojaf** [comment]
I do mean the one in the fman installation directory, thanks for the heads up.
