### ISSUE TITLE
"Could Not Delete" file or folder on Linux / Ubuntu

### ISSUE THREAD

**Issue by slybridges** [fman-community/fman#399]
Using latest version (1.0.9), as well as previous ones, I cannot delete anything via fman on Ubuntu (18.04).

![fman-cannot-delete](https://user-images.githubusercontent.com/5409148/40842549-89df01ec-65ae-11e8-8ed6-71e4b8158587.png)

Deleting the same file through the default file explorer or via the command line works as expected.

Any hint?

**Comment by mherrmann** [comment]
Does Delete Permanently (<kbd>Shift+Delete</kbd>) work?

**Comment by slybridges** [comment]
Oh yes, that one does work.

**Comment by slybridges** [comment]
After looking into it, the problem was on my side. Even deleting a file in the file explorer would mention the problem (but I guess I never took the time to read it :smile:):

`Unable to find or create trash directory`

For some reason the Trash folder had the wrong permissions.

`sudo chown -R <user>:<user> ~/.local/share/Trash/` fixed the problem for me.

Sorry about that Michael. Closing!

**Comment by mherrmann** [comment]
Heh, happy it's resolved ;) Bugs that "fix" themselves are my favorite kind of bug ;)
