### ISSUE TITLE
Provide menu bar so it gets easier to find features

### ISSUE THREAD

**Issue by tmssngr** [fman-community/fman#405]

**Comment by oskretc** [comment]
Give Ctrl+Shift+p a try, you will love it

**Comment by tmssngr** [comment]
I've did and it has justification as an addition to the menu, especially because the popup is quite small and it is not resizable.

**Comment by mherrmann** [comment]
fman's approach is to use the Command Palette (<kbd>Ctrl+Shift+P</kbd>) instead of a menu. The reasoning for this is explained in [this blog post](https://fman.io/blog/drag-and-drop/). Thank you for the suggestion, I appreciate it, but I'm closing this issue.

**Comment by tmssngr** [comment]
I don't agree with you. Maybe you find menus horrible to use and a waste of time, but I'm sure that they are a very good solution for other people, e.g., to learn the available features. At least some people also are spatial orientated and hence can remember "somewhere near the bottom of the next-to-left-most menu" easier than to remember an exact name.

**Comment by mherrmann** [comment]
I get that. It's an individual preference. But if fman tried to make everybody happy, it would become a bloated, complicated mess. So it's opinionated instead. I understand that that doesn't make it for everyone.

**Comment by tmssngr** [comment]
I don't think that adding a menu bar would make fman to a bloated, complicated mess - but rather to an easier to use application. If for the hard-core users this would be overkill, why not add an option to the settings file to hide the menu bar? But if you don't want to get a larger user base, it's also OK.
