### ISSUE TITLE
Can't open zip files if they have a different extension

### ISSUE THREAD

**Issue by tmssngr** [fman-community/fman#409]

**Comment by mherrmann** [comment]
What extension(s) should also be opened as Zip archives?

**Comment by tmssngr** [comment]
That should be configurable or - even better - detected automatically by the content (start with "PK"). For example, LibreOffice files (.odt, .ods) are zip files.

**Comment by mherrmann** [comment]
It is configurable :) Create the file `Core Settings.json` in the `Plugins/User/Settings` subdirectory of your [data directory](https://fman.io/docs/data-directory):

```
{
	"archive_handlers": {
		".odt": "zip://",
		".ods": "zip://"
	}
}
```

**Comment by tmssngr** [comment]
Does this make a difference between **opening** these files and diving into the archive?

**Comment by mherrmann** [comment]
Yes. The above dives into them. If you want to open them after the above configuration, you'd have to use the Open With command. I know it's not ideal but it is how it is currently.
