### ISSUE TITLE
Optionally remember sorting mode for opened directories

### ISSUE THREAD

**Issue by tmssngr** [fman-community/fman#411]
Usually, my directories are sorted by name or extension, but my downloads directory I prefer to have sorted by file time, so the new items occur at the top of the list.

**Comment by mherrmann** [comment]
fman does this when you sort using the keyboard (<kbd>Ctrl+F3</kbd>). It doesn't work when you sort with the mouse. I'll close this issue as a duplicate of #301.

**Comment by tmssngr** [comment]
Does fman really remember different sorting modes for different directories?

**Comment by mherrmann** [comment]
As I said - when you change the sort order via the keyboard (<kbd>Ctrl+F1/F2/F3</kbd>) then yes. It should remember it.

**Comment by tmssngr** [comment]
So using the mouse is only temporarily where as using the keyboard is permanently? Is this by design or a bug?

**Comment by mherrmann** [comment]
Yes. It's a bug.
