### ISSUE TITLE
Compressing should accept different extensions

### ISSUE THREAD

**Issue by tmssngr** [fman-community/fman#415]
Sometimes .zip files have different extensions, too. Of course, I could first create the .zip file, then rename it, but why not doing both in one step?

**Comment by mherrmann** [comment]
> why not doing both in one step?

fman is all about minimalism. The answer to this question is that it would complicate fman. My intuition is that this is a rare use case, and even if it arises it's easy to work around by first creating the .zip file, then renaming as you pointed out.

**Comment by tmssngr** [comment]
Why then allow to give the archive an arbitrary name?

**Comment by mherrmann** [comment]
Because it's an easy way to let you supply the extension and thus the compression method as well (`.zip` vs `.7z` for instance).

**Comment by mherrmann** [comment]
(Closing this issue. Feel free to comment further.)
