### ISSUE TITLE
Opening archive, going back -> sorting is lost

### ISSUE THREAD

**Issue by tmssngr** [fman-community/fman#416]
I have sorted my directory view by file time and dive into an archive. Pressing Backspace and the sorting is reset.

**Comment by mherrmann** [comment]
I assume this is because of bug #301, that fman currently does not remember sort settings chosen with the mouse.

**Comment by tmssngr** [comment]
This bug is not about not saving the sort mode on exit, but about keeping the sort mode while changing the directory.

**Comment by mherrmann** [comment]
I understand. But (at least in my tests just now) fman does keep the sort order _if you have set it via the keyboard <kbd>Ctrl+F1/F2/F3</kbd>, not the mouse._
