### ISSUE TITLE
Show the number of the selected file somewhere

### ISSUE THREAD

**Issue by tmssngr** [fman-community/fman#418]

**Comment by mherrmann** [comment]
You mean along the lines of "The 5th file is selected"? Or do you mean _how many_ files are selected? Have you seen [StatusBarExtended](https://github.com/kek91/StatusBarExtended)?

**Comment by oskretc** [comment]
StatusBarExtended is broken and has been broken for a while

**Comment by tmssngr** [comment]
I want to see how many files are selected to quickly detect the file count in a directory. Summing up the file sizes also would be nice.

**Comment by mherrmann** [comment]
Then I would consider this a duplicate of #292. Closing this issue.
