### ISSUE TITLE
Default keyboard shortcuts for "Open in other pane" don't work on Mac

### ISSUE THREAD

**Issue by matangover** [fman-community/fman#426]
The keyboard shortcuts Ctrl+Right / Ctrl+Left are used by macOS to switch spaces (desktops). I assume that the key presses are thus not delivered to fman, so the fman functionality for "open in other pane" isn't triggered. I suggest changing the default shortcut on Mac, e.g. to Option+Right / Option+Left.

**Comment by mherrmann** [comment]
Good suggestion, thanks. Will go live with fman 1.1.1.

**Comment by mherrmann** [comment]
Implemented in [fman 1.1.1](https://fman.io/changelog#v1.1.1).
