### ISSUE TITLE
Navigating "back" to a renamed/moved directory causes exception

### ISSUE THREAD

**Issue by jorbas** [fman-community/fman#427]
When navigating "back" to a directory which no longer exists (i.e. has been moved or renamed), fman raises an exception.

<img width="420" alt="screen shot 2018-06-18 at 11 04 58" src="https://user-images.githubusercontent.com/1732497/41551095-ba1e4364-7322-11e8-8e2c-8a4aaab93323.png">

Suggest fman should instead travel "up" from the directory which it attempted to access until it finds a directory which does exist and open that instead.

**Comment by mherrmann** [comment]
Thank you for reporting this. I fixed it per your suggestion. Will go live with fman 1.1.1.

**Comment by mherrmann** [comment]
Fixed in [fman 1.1.1](https://fman.io/changelog#v1.1.1).
