### ISSUE TITLE
Opening files with "&" symbol in Windows

### ISSUE THREAD

**Issue by ndcooke** [fman-community/fman#434]
Files with an ampersand in them cannot be opened on Windows 7 x64.
![image](https://user-images.githubusercontent.com/14249205/41998899-84e28ef2-7a21-11e8-985d-3ab204725b81.png)

**Comment by ndcooke** [comment]
To clarify, the file name does not have the circumflex (^) character in it.

This happens on less complex file names, for instance: "PT CON & CON-X.sql" has the same problem:
![image](https://user-images.githubusercontent.com/14249205/41999000-cdc0e970-7a21-11e8-8d91-6fc1c8a4ae50.png)
![image](https://user-images.githubusercontent.com/14249205/41999027-e87f74f2-7a21-11e8-989c-8618e6271009.png)

**Comment by kek91** [comment]
Reproducible on Windows 10 x64 as well. Never noticed this before, but I can't remember using a file with `&` in the name either so who knows... :)

![image](https://user-images.githubusercontent.com/1431734/42052686-c703e7ce-7b0f-11e8-8797-88b35729014f.png)

**Comment by mherrmann** [comment]
I presume this is related to #372.

**Comment by mherrmann** [comment]
Fixed in [fman 1.1.4](https://fman.io/changelog#v1.1.4).
