### ISSUE TITLE
Make it possible to define keyboard shortcuts for "Open With" a specific app

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#436]
Requested by @divenyijanos in #61.

**Comment by mherrmann** [comment]
Implemented. Will go live with fman 1.1.3.

To define a shortcut for opening with a specific app, add eg. the followig to `Key Bindings.json` in your [Settings plugin](https://fman.io/docs/plugins-architecture).

```
[
	{"keys": ["Ctrl+Enter"], "command": "open_with", "args": {"app": "Gimp"}}
]
```

You can find the available "app" names in `Apps.json` in the same directory.

**Comment by mherrmann** [comment]
Released as part of [fman 1.1.3](https://fman.io/changelog#v1.1.3).

**Comment by macosxguru** [comment]
Where is the Apps.json document in the Settings directory?

Do I have to create it? How does one do that?

![screen shot](https://user-images.githubusercontent.com/1103821/42639924-fe06f702-85a5-11e8-86dc-4635aa5e03b1.png)

macosxguru

**Comment by mherrmann** [comment]
It's created the first time you launch the Open With command. I need to make that clearer, sorry.

**Comment by macosxguru** [comment]
Cool. Thanks. It has some weirdnesses in the way it behaves. I am going to work on it for a while and then post a write-up on how it is behaving.

macosxguru

**Comment by divenyijanos** [comment]
Cool. Thanks.
My main use case was to open multiple images (.png, .pdf, etc.) at once within one Preview window. It is kind of random whether `Open with...` opens them together, or in separate windows (or just 2 images in one window, other 3 images in another). Any idea how to fix this behavior?

**Comment by mherrmann** [comment]
I'm sorry, I don't know. By the way, I only just realised that you are talking about macOS's QuickLook feature? If yes, you can also launch that with <kbd>Cmd+Space</kbd>.

**Comment by divenyijanos** [comment]
You mean, right from `fman`? For `Cmd+Space` I get the standard Spotlight Search.

**Comment by mherrmann** [comment]
Sorry Shift+Space.

**Comment by divenyijanos** [comment]
`Shift+Space` indeed opens the image, but I cannot make it open multiple images at once, so that I can change between them with the arrow keys.

**Comment by mherrmann** [comment]
Okay! I just implemented support for multiple files with Shift+Space (#448). Will go live with fman 1.1.4.

**Comment by mherrmann** [comment]
[fman 1.1.4](https://fman.io/changelog#v1.1.4) is live.

**Comment by divenyijanos** [comment]
Cool, you won me :)

**Comment by mherrmann** [comment]
:pray:

**Comment by mareksamec** [comment]
Thank you for this awesome feature! I just discovered it here by Googling, would it be possible to add this new possibility to the documentation here? :
https://fman.io/docs/custom-shortcuts
