### ISSUE TITLE
Slow opening and 100% CPU usage with folders containing over 1000 files

### ISSUE THREAD

**Issue by halega** [fman-community/fman#439]
**Version**
- fman 1.1.1
- Windows 10 1803

**Steps to reproduce**
1. Open folder `C:\Windows\System32` in fman. It contains over 1000 files & subdirectories.

**Expected**
Folder opens instantly. 

**Actual**
fman uses 100% CPU during 5 seconds for openning this folder.

**Comment by mherrmann** [comment]
You're right fman is too slow for large numbers of files, sorry. I will be improving this throughout the coming months. This problem has been mentioned several times (eg. #220, #362). So I'm closing this issue.
