### ISSUE TITLE
UnsupportedOperation Error class no longer in the API?

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#445]
I just upgraded to the 1.1.2 version of fman and it caused the DropboxConnect plugin to die since the UnsupportedOperation error class is no longer in the Core. Is this an over-site or do I need to change the plugin?

**Comment by mherrmann** [comment]
UnsupportedOperation is actually a Python exception. You should be able to simply replace

    from fman.fs import UnsupportedOperation

by

    from io import UnsupportedOperation

**Comment by raguay** [comment]
Oh. I thought it was one you made. Okay. Thanks.

**Comment by mherrmann** [comment]
I'll update the API docs to make this clearer. Sorry for the confusion.

**Comment by mherrmann** [comment]
(Docs updated.)
