### ISSUE TITLE
Cancelling file open dialog in Windows gives "ugly" error

### ISSUE THREAD

**Issue by ndcooke** [fman-community/fman#449]
Opening an exe file that produces a security dialog:
![snag_19874a00](https://user-images.githubusercontent.com/14249205/42904559-f40cfe3a-8ac4-11e8-9f35-26b86fdbce52.png)

And then clicking cancel gives a dialog like:
![snag_1987a559](https://user-images.githubusercontent.com/14249205/42904582-024112e8-8ac5-11e8-84a0-bead7e88738c.png)

Not really a bug, just don't know if an error message is required for a user-cancelled return code.

**Comment by mherrmann** [comment]
Fixed. Will go live with 1.1.5. Thank you!

**Comment by mherrmann** [comment]
Fixed in [fman 1.1.5](https://fman.io/changelog#v1.1.5).
