### ISSUE TITLE
Windows shortcut links still open windows explorer

### ISSUE THREAD

**Issue by JayBeeDe** [fman-community/fman#452]
When opening a _windows shortcut_ link (.lnk file), it opens the target but still in the normal Windows Explorer.
**Expected feature**: the target shall be open in the current panel in fman

Note: an implementation in a plugin could be great.

**Comment by JayBeeDe** [comment]
Hi,

According [https://stackoverflow.com/questions/397125/reading-the-target-of-a-lnk-file-in-python](https://stackoverflow.com/questions/397125/reading-the-target-of-a-lnk-file-in-python):


Create a shortcut using Python (via WSH)

```
import sys
import win32com.client 

shell = win32com.client.Dispatch("WScript.Shell")
shortcut = shell.CreateShortCut("t:\\test.lnk")
shortcut.Targetpath = "t:\\ftemp"
shortcut.save()
```


Read the Target of a Shortcut using Python (via WSH)

```
import sys
import win32com.client 

shell = win32com.client.Dispatch("WScript.Shell")
shortcut = shell.CreateShortCut("t:\\test.lnk")
print(shortcut.Targetpath)
```


@mherrmann  Shall I develop the plugin for that? Or does it already exist?

**Comment by mherrmann** [comment]
@JayBeeDe I'll implement this.

**Comment by mherrmann** [comment]
(P.S.: Thanks!)

**Comment by mherrmann** [comment]
Implemented in [fman 1.5.6](https://fman.io/changelog#v1.5.6). If you're interested in the relevant code, it's [here](https://github.com/fman-users/Core/commit/c1277c417095c1328f8cb20d7878ca735b487338#diff-ed33704a5c5c66cc38db8db32136cc0dR337).

**Comment by JayBeeDe** [comment]
Great, thank you :)

**Comment by mherrmann** [comment]
My pleasure :-)
