### ISSUE TITLE
OAuth setting on repo

### ISSUE THREAD

**Issue by gingerbeardman** [fman-community/fman#455]
This will enable third party GitHub apps to work. I'm using GitHawk. 

![GitHawk Upload by gingerbeardman](https://i.imgur.com/qxMahbZ.jpg)

**Comment by mherrmann** [comment]
Sorry, I'm afraid of the security implications when relaxing the access restrictions. Closing this issue.

**Comment by gingerbeardman** [comment]
Slight misunderstanding, I'm not asking for you to relax access restrictions. Just to approve/allow GitHawk as a client.

**Comment by gingerbeardman** [comment]
FWIW, a workaround for this issue is to generate a Personal Access Token and use that to login to GitHawk etc.
