### ISSUE TITLE
Cannot launch executable files that are special folders (macOS)

### ISSUE THREAD

**Issue by gingerbeardman** [fman-community/fman#461]
What I did:
- Double click .app/.pkg

What I expected to happen:
- Launch selection

What actually happened:
- Opens as folder

**Comment by mherrmann** [comment]
Not sure about this one. I understand your expectation. But technically, these "files" are folders. Other people have experienced this as well; But I can't find a related issue at the moment.

**Comment by gingerbeardman** [comment]
Sure, they are special folders, but (most?) users will not know that. They will just expect the thing to launch as it does in Finder?

**Comment by mherrmann** [comment]
The purist in me revolts, but you are probably right.

**Comment by gingerbeardman** [comment]
I just checked what Nimble does, and it offers both (yay, compromise!)

- Double click opens as folder
- Context menu "Open" launches executable

👌 

Finder:
- Double click launches executable
- Context menu "Show Package Contents" opens as folder

**Comment by gingerbeardman** [comment]
Personally I'd prefer Finder behaviour, but can understand that somebody using a custom dual pane file manager may know more about app structure than most.

**Comment by gingerbeardman** [comment]
I saw your solution to this. Not sure I agree 100%.

But feel free to close.
