### ISSUE TITLE
Feature request: Zoom in/out

### ISSUE THREAD

**Issue by jonaskello** [fman-community/fman#465]
Support zoom in/out in order to make the text more legible. Same function as zoom in chrome, vscode and terminal with cmd+plus/minus.

**Comment by mherrmann** [comment]
Thanks! This already captured by #359 I believe.

**Comment by jonaskello** [comment]
Aha, yes that would be the same, sorry for the duplicate. I searched for "zoom" and came up empty. Might want to update the title of #359 to include the word "zoom" somewhere.

**Comment by mherrmann** [comment]
Good point. I updated the issue title. Thanks.
