### ISSUE TITLE
fman (Windows up to and incl. 1.1.7) doen't work (well) with AppLocker and Software Restriction Policy

### ISSUE THREAD

**Issue by kernal64** [fman-community/fman#476]
When _AppLocker_ or _Software Restriction Policy (SRP)_ is used, _fman_ doesn't start, because it installs in CSIDL_LOCAL_APPDATA (%AppData%), which should be used for APPlication specific DATA and not for the executables. I moved the folder manually to  CSIDL_PROGRAM_FILES  (%ProgramFiles%). Now it starts but automatic updates are broken.

**Comment by mherrmann** [comment]
You're the second user to report this recently (the other report was by email). I will have to take a look... My problem is, I don't want to require admin rights for installation.

**Comment by kernal64** [comment]
It was me, who reported by E-Mail. At that time I had no github-account. As you can see, I have some more issues with fman (on Windows). So I decided to sign up to github and report the issues "officially . I thought it would  be good to have this issue here as well.

I think Google handles this topic smart with Chrome. If Chrome-Setup has write permissions to %ProgramFiles%, it installs there for everyone,  otherwise AFAIR it installs in %AppData%, too.

**Comment by mherrmann** [comment]
Ah, I see! Thank you for clarifying - and the additional insight regarding Chrome. fman [uses the same technology as Chrome](https://fman.io/blog/google-omaha-tutorial) for auto-updating and installing on Windows. It's just that fman's installation is explicitly configured to be a "user install" by default. Maybe I can change this to achive the behaviour you described about Chrome.

**Comment by dcsoft4** [comment]
Do Chrome updates work when it is installed to %ProgramFiles%?

**Comment by kek91** [comment]
This is one of the things I like about fman. Software asking for admin access (while not really needing it) really grinds my gears.

Would an idea be to install fman executables to %LocalAppData% and keep data/cache/plugins in %AppData% ? 
Most corporate GPO's typically sync %AppData% to the user profile, but not %localappdata%. 

If I remember correctly %localappdata% points to `C:\Users\user\AppData\Local` and %appdata% points to `C:\Users\user\AppData\Roaming`

**Comment by mherrmann** [comment]
> Would an idea be to install fman executables to %LocalAppData% and keep data/cache/plugins in %AppData% ?

That's how fman [does it](https://fman.io/docs/data-directory)?

**Comment by kernal64** [comment]
> Do Chrome updates work when it is installed to %ProgramFiles%?

Yes, when you install Chrome as an admin under %ProgramFiles%, Google installs an update-service for it.

**Comment by kek91** [comment]
> > Would an idea be to install fman executables to %LocalAppData% and keep data/cache/plugins in %AppData% ?
> 
> That's how fman [does it](https://fman.io/docs/data-directory)?

Oh haha I'm sorry! Then I think the company's a little strict on the AppLocker rules, alot of software installs to %LocalAppData%.

**Comment by kernal64** [comment]
> This is one of the things I like about fman. Software asking for admin access (while not really needing it) really grinds my gears.

It's NOT the software asking for admin access. It's just the installer asking only once! And that's how it should be. Ordinary users shouldn't be allowed to install anything without knowledge of his/her admin. Otherwise the admin has to cope with huge amounts of infested PCs and lots of lost data (ransomware).

> Would an idea be to install fman executables to %LocalAppData% and keep data/cache/plugins in %AppData% ?

Please read my initial post. Per definition, %(Local)App**DATA**% is for application **DATA** and not for executables. Every ordinary user (and malware) can write to this location. If the admin allows executables to start from here, s/he gives up control completely.

> Most corporate GPO's typically sync %AppData% to the user profile, but not %localappdata%.
> 
> If I remember correctly %localappdata% points to `C:\Users\user\AppData\Local` and %appdata% points to `C:\Users\user\AppData\Roaming`

Roaming is not the point. It's security.

**Comment by kernal64** [comment]
> > > Would an idea be to install fman executables to %LocalAppData% and keep data/cache/plugins in %AppData% ?
> > 
> > 
> > That's how fman [does it](https://fman.io/docs/data-directory)?
> 
> Oh haha I'm sorry! Then I think the company's a little strict on the AppLocker rules, alot of software installs to %LocalAppData%.

Not alot, but some software indeed install into %(Local)AppData%, ignoring Windows program developer guidelines (some from MicroSoft itself \<sic\>).
