### ISSUE TITLE
7z archives are not treated like directories

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#477]
fman: 1.1.8
OS: Manjaro Linux 17.1.11, Gnome 3.26

1. Try opening a 7z archive.

Right now the default OS archive manager will launch. Would be great if 7z were treated like ZIP and RAR are now

**Comment by mherrmann** [comment]
That shouldn't happen. What's the exact name of the 7z archive? (In particular, the extension?)

**Comment by IgorKrupenja** [comment]
Strangely enough, I cannot reproduce this anymore with any 7z archives. Closing for now.
