### ISSUE TITLE
Right alt key (alt gr, bound to ISO_Level5_Shift) incorrectly executes whatever the first key binding is.

### ISSUE THREAD

**Issue by rmgk** [fman-community/fman#478]
Fman 1.1.8 on Ubuntu using neo2 keyboard layout.

# Short summary

When I press the right alt key (alt gr, bound to ISO_Level5_Shift) the first key binding in the user key bindings is incorrectly executed.

The expectation is that no key binding is executed.

# Details

I use the neo2 keyboard layout (https://www.neo-layout.org/) which has some additional modifier keys, the one in question is the `alt gr` key on German keyboards (same position as right alt key, i.e. directly right of space). xev (https://www.x.org/archive/X11R7.7/doc/man/man1/xev.1.xhtml) detects a key press as follows:

```
KeyPress event, serial 30, synthetic NO, window 0x4a00001,
    root 0x194, subw 0x0, time 179288584, (419,390), root:(1381,557),
    state 0x0, keycode 108 (keysym 0xfe11, ISO_Level5_Shift), same_screen YES,
    XKeysymToKeycode returns keycode: 94
    XLookupString gives 0 bytes: 
    XFilterEvent returns: False
```

When this key is pressed the first key binding in the users `Key Bindings.json` is executed, i.e., if the file looks like this:
```
[
	{ "keys": ["????"], "command": "noop", "args": {} },
	{ "keys": ["Alt+Shift+g"], "command": "command_palette", "args": {} },
	{ "keys": ["Ctrl+g"], "command": "go_to", "args": {} }
]
```
then pressing that key will trigger the `noop` command (I added that command as a workaround to not trigger problematic keys. 

It does not matter what the key in the key binding is. Any arbitrary string works.
If there is no user defined `Key Bindings.json` then a key binding from an installed plug in is triggered, I suspect this is because of the internal order of key bindings, and that binding being the first or last.
Using `alt gr` as a modifier (when the noop workaround is in place) works.

**Comment by mherrmann** [comment]
Please install Python 3 (if it's not installed already). Then `cd` to a temporary directory in a terminal and do:

    python3 -m venv venv
    source venv/bin/activate
    pip install PyQt5==5.9.2
    python

Then, paste the following:

    from PyQt5.QtWidgets import QApplication
    app = QApplication([])
    from PyQt5.QtWidgets import QMainWindow
    class MainWindow(QMainWindow):
        def keyPressEvent(self, e):
            print('%r|%d' % (e.key(), e.modifiers()))
    
    m = MainWindow()
    m.show()
    app.exec_()

This opens a window. Which output do you see in the terminal when you press `AltGr` while the window has focus?

**Comment by rmgk** [comment]
`AltGr` prints `0|0` on key down. 


### Some more details: 

`0|0` is printed for `AltGr` on both the neo2 layout, as well as default en-US qwerty.
With the default German keyboard `AltGr` prints: `16781571|1073741824`.
Similar holds true for the `<` key on German layouts (immediately right of the left shift key) which also does not exist on English keyboards. (Similar means: `0|0` on both neo2 and English layout, but `60|0` on German layout)

There are a couple “unmapped” key combinations in neo2 which also produce `0|0` and trigger the same behavior in fman.

### Some random observations:

None of the additional modifier keys of neo2 seem to be picked up by QT, (`e.modifiers()` is always 0), but all combinations do produce different (and seemingly correct) `e.key()` values.

The rest of the behavior seems to be more or less consistent between layouts, e.g., `shift+a` is always the same key as just `a` but with a modifier value, while `shift+1`  and just `1` are different keys and different modifiers.

**Comment by mherrmann** [comment]
Thank you. I think I was able to fix this. Will go live with fman 1.1.9.

**Comment by mherrmann** [comment]
[fman 1.1.9](https://fman.io/changelog#v1.1.9) is live.

**Comment by rmgk** [comment]
I can confirm that the problem is solved.

Thank you for the quick fix. This made made me confident to buy fman. Please keep up the good work :-)

**Comment by mherrmann** [comment]
Thanks for letting me know! I will :-)
