### ISSUE TITLE
Add the ability to save favourite locations

### ISSUE THREAD

**Issue by grandfso** [fman-community/fman#479]
I have some network shares that I can access in fman by manually typing the network path, but when I go to CTRL+P menu, I can't see these visited network locations.

I would like to propose, to have the ability to save current local/network location as a favorite. Then be able to pick it up from CTRL+SHIFT+P menu maybe?

**Comment by mherrmann** [comment]
Can the [favorites plugin](https://github.com/raguay/favorites) help you? :-)

**Comment by raguay** [comment]
Ah, you beat me to it.

**Comment by mherrmann** [comment]
;-)

**Comment by grandfso** [comment]
Judging from the name, this will definitely help XD
Thanks for the suggestion !
