### ISSUE TITLE
Windows 10 Installation Error

### ISSUE THREAD

**Issue by ckm47** [fman-community/fman#480]
I'm seeing the following error message after install of fman on Windows 10 Enterprise:

> Plugin 'Core' failed to load.
> 
> Traceback (most recent call last):
>   File "fman\impl\plugins\plugin.py", line 124, in load
>   File "fman\impl\plugins\plugin.py", line 133, in _load
>   File "fman\impl\plugins\plugin.py", line 150, in _load_font
>   File "fman\impl\util\qt\thread.py", line 11, in result
>   File "fman\impl\util\qt\thread.py", line 64, in run_in_thread
>   File "fman\impl\font_database.py", line 11, in load
> RuntimeError: Font 'C:\\Users\\cmui\\AppData\\Local\\fman\\Versions\\1.1.8\\Plugins\\Core\\Open Sans.ttf' could not be loaded.

Both panes of fman have 'null' written on the dropdown bar and none of the keyboard shortcuts work.

**Comment by mherrmann** [comment]
Hm, sorry for the trouble. Does this problem persist when you re-install fman?

**Comment by ckm47** [comment]
Yes, tried uninstall and install a couple of times. Same error message each time.

**Comment by mherrmann** [comment]
I see. Can you upload the file `C:\Users\cmui\AppData\Local\fman\Versions\1.1.8\Plugins\Core\Open Sans.ttf` here so I can check its contents?

**Comment by ckm47** [comment]
[Open Sans.zip](https://github.com/fman-users/fman/files/2312121/Open.Sans.zip)

**Comment by mherrmann** [comment]
Thank you. I think I was able to implement a fix. Will go live with fman 1.2.4.

**Comment by ckm47** [comment]
Great, thanks!

**Comment by mherrmann** [comment]
Fixed in [fman 1.2.4](https://fman.io/changelog#v1.2.4).
