### ISSUE TITLE
fman 1.2.3: The SwapPanel command now hangs

### ISSUE THREAD

**Issue by raguay** [fman-community/fman#488]
My swappanel plugin will swap one panel and then hangs on swapping the other panel. It happened all the time with 1.2.1, but it just updated to 1.2.3 and it happens every second time? I don't see anything in the code that would cause an infinite loop, but that is how it is behaving. I have to kill fman each time.

Running from the command line doesn't show any output about what is happening.  It seems to crash on the execution of line 48 which is setting the left panel path, but before it executes the callback function (I put in several print statements to see where it is dying). Therefore, it is dying inside of fman's set_path function. Maybe something with the changes to the goto?

**Comment by mherrmann** [comment]
I'm able to reproduce this and am working on a fix. Already spent a few hours on it. It's subtle. Will post back again here when I know more.

**Comment by raguay** [comment]
Okay. Thanks.

**Comment by mherrmann** [comment]
Fixed in [fman 1.2.4](https://fman.io/changelog#v1.2.4).
