### ISSUE TITLE
Command 'OpenWithEditor' raised error.

### ISSUE THREAD

**Issue by TrailHacker** [fman-community/fman#489]
I've recently started getting this error with the latest release (**v1.2.3**):

![image](https://user-images.githubusercontent.com/181444/44535426-f8f04a00-a6c7-11e8-8b68-faefabf36204.png)

Here are the steps to reproduce:
1. Navigate to a directory with a text file.
1. With a text file highlighted, press the `[F4]` key.
1. Error: **Command 'OpenWithEditor' raised error.** ☹️ 

I've uninstalled fman and reinstalled it, but still get the same error. Is this a known issue or is it something I have configured wrong?

Here are the plugins I'm using:
![image](https://user-images.githubusercontent.com/181444/44535546-48cf1100-a6c8-11e8-9e15-8337c2e74c55.png)

Any help would be greatly appreciated.

**Comment by mherrmann** [comment]
Could it be that the text editor you used to have is no longer installed on your system? You can delete / edit the file `Core Settings.json` in the Settings plugin to check for / reset this. (To get to the Settings plugin, press <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>, type `List plugins` and select the Settings plugin.)

**Comment by TrailHacker** [comment]
You nailed it!! 👊 Thanks!!

In hind-sight, I updated my version of VSCode at the same time to the _USER_ install location. The editor was no longer located at the original location, defined in my `Core Settings.json` file. I didn't think to check there because my **OpenFolderInVSCode** plugin still worked. 

:man_facepalming:

**Comment by mherrmann** [comment]
I see, okay! I changed it now so you get a nicer message when that happens:

![image](https://user-images.githubusercontent.com/1076393/44569560-19c5a780-a77b-11e8-897d-4f7e39528378.png)
