### ISSUE TITLE
"Yes to all" doesn't dismiss all errors during copy

### ISSUE THREAD

**Issue by matangover** [fman-community/fman#492]
I copied a very large directory to an external hard drive and got many errors on various files. (Most of the files did succeed though.)

Clicking `Yes to all` didn't help - I had to click it for every error (at least there was a keyboard shortcut ;). Clicking `Yes` had the same result.

Platform: macOS High Sierra 10.13.5
fman version: 1.2.5

Note: I don't think the errors themselves are an issue in fman, only the 'Yes to all'. See below.

----

Example errors:

![image](https://user-images.githubusercontent.com/5028956/44597237-f14ea500-a79c-11e8-88c1-8595f70023d0.png)

![image](https://user-images.githubusercontent.com/5028956/44597470-b9942d00-a79d-11e8-96ce-d4f11977bb50.png)

----
Doing the same copy using Finder also fails (and aborts on the first error without option to continue, so fman is better than Finder!)

![image](https://user-images.githubusercontent.com/5028956/44598045-b26e1e80-a79f-11e8-8cb0-c83c894b7f7d.png)

Doing the same copy using `cp -R` gives the same errors that fman gave.

Maybe it's a file system thing -

Source disk: APPLE SSD SM0512L
Source file system: Apple_APFS
Destination disk: WD My Passport Ultra
Destination file system: Windows_NTFS
I mounted the NTFS disk read-write using:
```sudo mount -t ntfs -o rw,auto,nobrowse /dev/disk2s1 ~/ntfs-volume```

**Comment by mherrmann** [comment]
Should be fixed in [fman 1.2.6](https://fman.io/changelog#v1.2.6).

**Comment by mherrmann** [comment]
(And thank you for the nice bug report!)
