### ISSUE TITLE
Windows 10 Dialog Box Scaling Error

### ISSUE THREAD

**Issue by peterreibel** [fman-community/fman#494]
Hi Michael,

Thanks for making fman so great!

My Windows 10 (latest release) notebook scales to 125% and seems to crash the copy dialog box.

See screenshot
![fman dialog error](https://user-images.githubusercontent.com/42697505/44619171-6e077f00-a882-11e8-8951-183d8ff40ef2.png)
 
Best,
Peter

**Comment by mherrmann** [comment]
Hi Peter, thank you for the kind words and sorry for the bug.

What do you mean when you say "it scales to 125%"? Is there a setting in Windows somewhere that lets you set this "scale"? If yes, where?

**Comment by peterreibel** [comment]
Hi Michael,

Sorry for not clarifying, please see screenshot below (source: Google):
![display-custom-scaling-on-windows-10-image-3-1](https://user-images.githubusercontent.com/42697505/44650409-cd7e9f80-a9e6-11e8-8d15-5c68268e8a15.png)

Mine is set to 125%.

Many thanks for taking the time to reply.

Best,
Peter

Am Mo., 27. Aug. 2018 um 08:08 Uhr schrieb Michael Herrmann <
notifications@github.com>:

**Comment by mherrmann** [comment]
The image isn't shown. But from the image name, I believe you mean the setting described in [this article](https://www.howto-connect.com/enable-display-custom-scaling-windows-10/)?

**Comment by peterreibel** [comment]
Yes, thanks. That's the picture I added. I edited my comment.

**Comment by oskretc** [comment]
I believe this is related to #444 
I realize that I have 150% scale. once I stepped back to 100% works ok

**Comment by mherrmann** [comment]
Yes, I also think it's the same issue. I believe I already have a fix. Will release it as part of fman 1.2.6.

**Comment by mherrmann** [comment]
Should be fixed in [fman 1.2.6](https://fman.io/changelog#v1.2.6).

**Comment by peterreibel** [comment]
You are the greatest! Thanks!

![fman_workin_dialog](https://user-images.githubusercontent.com/42697505/44663092-cf108d80-aa0f-11e8-897d-330d61a14122.png)

**Comment by mherrmann** [comment]
Great to hear it works. Thanks! :-)
