### ISSUE TITLE
URLs are invisible on Windows

### ISSUE THREAD

**Issue by blokeley** [fman-community/fman#495]
Windows has the concept of shortcuts (.URL files).

They do not appear in the fman DirectoryPane at all.  They are apparently invisible.

fman version 1.2.8
Windows 10 Pro version 1803 OS build 17134.228

**Comment by Arty2** [comment]
Cannot replicate in v1.7.2, probably fixed?

**Comment by blokeley** [comment]
URLs appear and seem to open from fman v1.7.2
