### ISSUE TITLE
'CTRL-C' and 'Right-click -> Copy' also copy filename, clobbering clipboard contents

### ISSUE THREAD

**Issue by sullyj3** [fman-community/fman#496]
I'm actually not sure whether this is intended behavior.

Often I get into situations like this:

1. Copy intended filename "some really long filename" from elsewhere
2. Switch to fman, ctrl-c on foo.txt I want to duplicate. I've forgotten that this will overwrite my clipboard.
3. ctrl-v in same directory, prompt for new filename for duplicate file appears
4. select "foo" in dialogue, press ctrl-v expecting to paste in intended "some really long filename"
5. end up with "foo.txt.txt" in the rename dialogue, I have to go off and re-copy the intended filename

This is quite frustrating, and copying the filename is pretty unexpected, and can be destructive if you're not expecting it (you might not be able to re-access you clipboard contents easily). I feel like files and text should be separate magesteria, and copying a file should not copy its filename.

**Comment by mherrmann** [comment]
Fair point. I implemented this now. Will go live with fman 1.2.9.

**Comment by mherrmann** [comment]
Implemented in [fman 1.2.9](https://fman.io/changelog#v1.2.9).
