### ISSUE TITLE
Files moved to trash using fman cannot be restored on Arch or Manjaro Linux

### ISSUE THREAD

**Issue by IgorKrupenja** [fman-community/fman#499]
1. Install fman on Arch/Manjaro (with GNOME as DE).
2. Delete a file to Trash.
3. Open Nautilus.
4. Select the file just deleted from fman.
5. Click restore.

Result:
![image](https://user-images.githubusercontent.com/26354715/44943826-5e81bc00-add5-11e8-82a8-9330ca7e0e21.png)

I am having this on one Manjaro physical machine and one Arch VM.

Also note that Nautilus does not show anything in Original Location and Moved to Trash On fields for files deleted from fman:

![image](https://user-images.githubusercontent.com/26354715/44943875-29c23480-add6-11e8-9964-f6b17bc73288.png)

Strangely though, when I do `cat /home/igor/.local/share/Trash/info/deleted\ from\ fman.trashinfo` the data seems to be there:

```
[Trash Info]
Path=/home/igor/Downloads/deleted%20from%20fman
DeletionDate=2018-09-01T10:47:34
```

**Comment by IgorKrupenja** [comment]
Cannot reproduce this on Ubuntu 18.04 though.

**Comment by mherrmann** [comment]
The data you posted above, is it the same as when you delete the file in Nautilus?

**Comment by IgorKrupenja** [comment]
I did some more testing with empty configuration and cannot reproduce this anymore with my Manjaro or Arch machines too on fman 1.3.2. Could have been some problem with previous local configuration :) I will close this for now.

**Comment by mherrmann** [comment]
Okay :) Thanks for letting me know.
