### ISSUE TITLE
Amend registeration instructions

### ISSUE THREAD

**Issue by jonaskello** [fman-community/fman#502]
In the email you get when registering fman it says you should "Download the license key to a folder on your computer. Navigate to this folder in fman. Open the license key with Enter or a double-click.". I did this, however it did not work. In the end  I realised that the file actually has to be named `User.json`. When I saved it from the mail I renamed it `fman-license.json`. Perhaps it could be added to the instructions that only the file name `User.json` will work and it will save some time for the next person :-).

**Comment by mherrmann** [comment]
I've now updated the instructions as follows:

1. Save the license key as `User.json` to a folder on your computer.
2. Navigate to this folder in fman.
3. Open the license key with `Enter` or a double-click.

(It used to be "1. Download the license key to a folder on your computer.")

Do you think that's clearer (/clear enough)?

**Comment by mherrmann** [comment]
(and thanks!)

**Comment by mherrmann** [comment]
Actually, I think I have a better phrasing:

1. Download the license key. Ensure it's named `User.json`.
2. Navigate to your downloads folder in fman.
3. Open `User.json` with `Enter` or a double-click.

**Comment by jonaskello** [comment]
Yes, the last phrasing seems very clear to me 👍

**Comment by mherrmann** [comment]
Great. Thanks!
