### ISSUE TITLE
Symlinks to folders are opened externally in fman 1.2.9 (linux)

### ISSUE THREAD

**Issue by rmgk** [fman-community/fman#505]
Since 1.2.9 fman seems to treat symbolic links to folders the same as regular files:
* Sorted together with regular files (folders are usually sorted first before files)
* They have sizes (different for each symlink).
* Hitting enter or clicking causes the linked folder to be opened in an external file manager (the default application configured for folders)

**Comment by mherrmann** [comment]
Fixed in [fman 1.3.0](https://fman.io/changelog#v1.3.0).
