### ISSUE TITLE
Airgap Network - Won't Install on Windows 7

### ISSUE THREAD

**Issue by RobWWW** [fman-community/fman#507]
Hello, By running fmanSetup.exe, I'm unable to install fman on an airgap network, i.e., no internet connection.  I get the following error message:

"Unable to connect to the Internet.  If you use a firewall, please whitelist fmanUpdate.exe."

Is there a way to obtain a standalone install file that I can transfer to my airgap network and install on Windows 7 (x64)?

Thanks,

-Rob

**Comment by mherrmann** [comment]
Yes. The Download - Thank You page mentions this. [Here](http://download.fman.io/1.2.9/fmanSetup.exe) is the latest offline installer.

**Comment by RobWWW** [comment]
Thanks Michael.  Got it working now.

**Comment by mherrmann** [comment]
Happy to hear it :-)
