### ISSUE TITLE
Don't require "installation" of license file

### ISSUE THREAD

**Issue by mwean** [fman-community/fman#509]
I just set up a new machine, and I have a bunch of settings files that all get symlinked to their correct locations. This doesn't seem to work for fman, because it shows as unregistered. I had to delete the `User.json` file and re-install it. It would be great if it could just check for the existence of the file. Thanks!

**Comment by mherrmann** [comment]
Hi Matt, are you sure you set up the symlink correctly? Because I just tried and it worked for me. I did:

    mv ~/Library/Application\ Support/fman/Local/User.json .
    ln -s `pwd`/User.json ~/Library/Application\ Support/fman/Local

**Comment by mwean** [comment]
Yeah, I'm sure it was there because when I tried to open it, I got an error saying the file was already there. Do you store the fact that it's licensed anywhere else, or just check for the file?

**Comment by mherrmann** [comment]
fman just checks for the file.

**Comment by mherrmann** [comment]
Did you restart fman?

**Comment by mwean** [comment]
Hmm that's weird. I noticed the unregistered prompt after my laptop restarted. There might be something weird with the link because I'm linking from a Keybase volume, which uses FUSE. I'll keep an eye on it. Thanks!
