### ISSUE TITLE
Visual indication that files are still being filtered

### ISSUE THREAD

**Issue by mherrmann** [fman-community/fman#511]
When you start typing file names to filter them and press <kbd>Escape</kbd> (or other non-character keys), the text field for filtering disappears from fman. But the files remain filtered until you press <kbd>Escape</kbd> again. (The reason for this is that the search bar captures certain keys such as <kbd>End</kbd>. By not clearing the filter until you press <kbd>Escape</kbd> _twice_, you can use those keys while the files are still filtered.)

Several users said that this simple disappearing of the search bar made it difficult (/impossible) to see whether files were still being filtered. This issue is about (maybe) improving this. It should be pointed out that Total Command can filter files as well and does _not_ give any visual indication either.

**Comment by oskretc** [comment]
This is how its done in Unreal Commander

First before typing
Second, while typing
Third, After first Esc.

The only visual clue is the Search Results string in the address bar.


![image](https://user-images.githubusercontent.com/4963991/45471796-7a208700-b732-11e8-8890-d5976a43e7a2.png)

**Comment by mherrmann** [comment]
Thank you @oskretc.

Another user pointed out another "shortcoming" of the current implementation: On Windows, when files are filtered and the filter bar is visible, pressing Arrow-Up/Down hides it. Would be better if it remained.

Generally, I am getting the feeling that it would be better if there were always some visual indication when the files are being filtered. I just need to think of a way that's clear, yet unobtrusive. Maybe always show the filter bar but position it in the lower right corner (instead of the lower left one), so it doesn't obscure the file names.

**Comment by oskretc** [comment]
Yes, a number of file explorers have some sort of filter bar. I'm not a fan though, takes space, and as soon as you have that always there bar, you are tempted to use the mouse instead of the keyboard. So something more subtle will be nice.

**Comment by mherrmann** [comment]
Makes sense. The nicest solution I can think of: Don't have a search bar but highlight _in the file names_ what's currently matched by the filter. Similar to Sublime Text's multi-select:
![image](https://user-images.githubusercontent.com/1076393/45548424-8f75de00-b824-11e8-91d9-852d72187055.png)

**Comment by oskretc** [comment]
Don't think that will work nice, once you have filter something you could: up/down to move through the list, select some files, clicks, right clicks.. etc. I don't think having something highlighted will be nice to the eye. I was thinking more like a slight change in the background color of the panel or the column headers. IMHO

**Comment by mherrmann** [comment]
I think it could work:
![image](https://user-images.githubusercontent.com/1076393/45550288-ba633080-b82a-11e8-83d8-8b7bd4fc6bc4.png)

**Comment by kalons7** [comment]
I don't like the double Esc.  Is it not possible to support typing to filter, arrow keys/home/end/etc while filtering to change selection, and a single Esc to cancel the filter?

For showing the filter, I think your idea of highlighting the match in the filename would be great.  XYplorer adds a "Live Filter: typedtext" status bar right above the file list, which also works -- see https://www.xyplorer.com/release_17.90.php#LF

**Comment by mherrmann** [comment]
> Is it not possible to support typing to filter, arrow keys/home/end/etc while filtering to change selection, and a single Esc to cancel the filter?

Yes, it would be. But then you wouldn't be able to use those keys (eg. <kbd>Home</kbd>) in the filter bar. But you're right, it's probably not really necessary anyways.

**Comment by eandmsz** [comment]
1. If you implement [#35](https://github.com/fman-users/fman/issues/35) to show ".." entry, and the user choses to use it, then the absence of ".." could be one indication of using a filtered view.

2. I think the ultimate solution would be to have an orange (or whatever) colored border or changed background color for the filtered pane:
![fman_filtered_view](https://user-images.githubusercontent.com/34283919/45825943-ab312680-bcf3-11e8-84a2-197feb3b6022.png)

**Comment by mherrmann** [comment]
Thank you for the screenshot. In an ideal world, my preferred solution would:
 1. Not let you "filter out" all files. That is, if you type an extra character for which no matching files exist, then this character simply isn't added to the filter. This way, it can never happen that all files disappear. TC does this.
 2. Not have a filter bar but highlight matched characters as in my screenshot above:
![image](https://user-images.githubusercontent.com/1076393/45861120-46b1ae00-bd6b-11e8-807a-29930d86e777.png)
 3. Filter both files starting with the given pattern and files _containing_ it (see #512). It would re-order files to show those that start with the pattern at the top, then those merely containing it at the bottom.

Unfortunately, each of these things is difficult to implement:
 1. To display a directory, fman uses a "model" and a "view". The former reads and maintains the list of files in a directory. It also does the filtering. The latter displays them. The problem is, the view contains the search bar and tells the model "filter out files not containing *pattern*". It currently cannot "preview" what happens when characters are added to the pattern. So it cannot decide if files would remain visible once it's expanded. Implementing 1. requires changing the implementation so the view does the filtering, not the model.
 2. Currently, fman uses Qt's [QTableView](http://doc.qt.io/qt-5/qtableview.html) to render the files. This doesn't support "drawing around" characters as in the screenshot. fman would have to implement its own rendering engine to be able to do that. Eventually, it's something that will have to be done. But it's a big task, especially taking into consideration that performance needs to be good.
 3. The current implementation filters out files, but does not change their order. 3. however would require also doing this. Again, not trivial.

A more trivial first solution for this issue would be to always display the filter bar when files are being filtered. Maybe at the bottom right instead of the bottom left so it doesn't obscure the file names. This way, there would also always be a visual indication that files are still being filtered. I'm not a huge fan of adding a visual indication that isn't 100% at-a-glance obvious. Your colouring is space-efficient. But if you only show someone a screenshot with the colouring applied, they will have no idea that it means that the files are being filtered.

**Comment by kalons7** [comment]
Don't overcomplicate it.  Definitely don't need 1, 2, or reordering mentioned in 3.  It is simple to just match what was typed anywhere in the filename (start, middle or end).

**Comment by keith-hall** [comment]
I also don't think it's necessary to reorder anything based on the filter matches - the existing sort order applied to whichever column (i.e. name ascending, modified date descending) should remain in effect when filtering files, otherwise filtering wouldn't be as useful if we want to, say, find the most recently modified file which matches the specified glob pattern etc.

**Comment by mherrmann** [comment]
Not overcomplicating it is a fair point imho. I'm looking at simply displaying the search bar in the lower right corner (instead of the left one), make it always visible (as visual indication), never to "steal" focus and only to require one press of <kbd>Escape</kbd> to dismiss.

Whether file names are filtered from the beginning, or the middle will be configurable.

**Comment by mherrmann** [comment]
Implemented in [fman 1.3.2](https://fman.io/changelog#v1.3.2).

**Comment by mherrmann** [comment]
(Actually, not the "Whether file names are filtered from the beginning, or the middle will be configurable." part. I simply went with substring matches `*str*` without making it configurable.)
