### ISSUE TITLE
Can't remove read-only file permanently

### ISSUE THREAD

**Issue by OmarWKH** [fman-community/fman#517]
Just encountered an error removing a file.
Message: "Error deleting file.txt: Access is denied."
![image](https://user-images.githubusercontent.com/10570290/45912774-6f9b7700-be2f-11e8-9351-19762c787121.png)

- It happens if the file is read-only (Properties > Attributes > Read-only).
- It happens if I permanently remove the file (`shift+del`).
- It doesn't happen if I remove it normally (just `del`).
- It happens even if I run fman as administrator.
- Explorer can delete the file.
- del command in cmd gives "Access is denied." too (even if run as administrator).

fman version: 1.3.1
Windows version: 10.0.17134.285

Could be the same issue as #281. Wasn't sure if I should post there or create a new issue.

**Comment by mherrmann** [comment]
Thank you for reporting this. I fixed it now. Will go live with fman version 1.3.2.

**Comment by mherrmann** [comment]
Fixed in [fman 1.3.2](https://fman.io/changelog#v1.3.2).
