### ISSUE TITLE
Command/shortcut to go to root of current drive

### ISSUE THREAD

**Issue by kalons7** [fman-community/fman#520]
would be handy.

**Comment by mherrmann** [comment]
Hi, is that on Windows?

**Comment by kalons7** [comment]
I am currently, but I would think it would be useful on all platforms.

**Comment by mherrmann** [comment]
I've implemented this now on Windows, with shortcut <kbd>Ctrl</kbd>+<kbd>\\</kbd>. Will go live with fman 1.3.3.

**Comment by kalons7** [comment]
Thanks.  I'm used to Alt+Backspace, but I guess I can customize that.

**Comment by mherrmann** [comment]
Where does Alt+Backspace come from? I took the shortcut from Total Commander.

**Comment by kalons7** [comment]
XYplorer.

**Comment by mherrmann** [comment]
I see. fman takes most of its inspiration from TC, so will leave it at <kbd>Ctrl</kbd>+<kbd>\</kbd> for now.

Implemented in [fman 1.3.3](https://fman.io/changelog#v1.3.3).
