### ISSUE TITLE
Slow populating of file list pane

### ISSUE THREAD

**Issue by kalons7** [fman-community/fman#529]
If a folder has a lots of files or several executables (or maybe files with different icons, not sure), or is on a network share, it can take several seconds for the list to show any files.  Can it be changed to incrementally load the list (start showing the first files right away) or sped up in some way?  Thanks.

**Comment by kalons7** [comment]
Also there is no indication of when it's done or a way to tell if the folder is actually empty or not done loading yet.  It should show something like 'No files found.' in the list area if there aren't any, and maybe a progress indicator if it takes more than a second to load.

**Comment by keith-hall** [comment]
related:

- https://github.com/fman-users/fman/issues/220
- https://github.com/fman-users/fman/issues/362#issuecomment-415670580

**Comment by mherrmann** [comment]
Let's use #220 and #362 (as @keith-hall suggested, thank you) for improving fman's performance please.

What is new here is to give some visual indication that allows you to distinguish between there being no files, and the folder still being loaded. I'll create a separate issue for this.

**Comment by mherrmann** [comment]
New issue created: #535.
