### ISSUE TITLE
GoTo dialog matching

### ISSUE THREAD

**Issue by kalons7** [fman-community/fman#537]
I don't like the way the goto dialog matches.  In the attached screen shot, it should match on strings containing the word Staging, but not strings with all those letters anywhere in the path.  This would be much more useful and also consistent with the command palette, list filtering, etc.  It should also prefer recently visited, matching folders.

![shot](https://user-images.githubusercontent.com/29680916/46375061-989de200-c64f-11e8-8e56-b51759ca52ba.png)

**Comment by mherrmann** [comment]
Implemented. Will go live with fman 1.3.3.

**Comment by mherrmann** [comment]
Implemented in [fman 1.3.3](https://fman.io/changelog#v1.3.3).
