### ISSUE TITLE
TortoiseGit/SVN in context menu support

### ISSUE THREAD

**Issue by omisys** [fman-community/fman#540]
Would be nice to have the context menu in fman as well. Currently I have to open my explorer to right-click a folder and check for modifications/show log etc.

**Comment by mherrmann** [comment]
This is outside the scope of fman for now. The [TortoiseSVN plugin](https://github.com/oskretc/fman-tortoisesvnhelper) could probably be extended to add the context menu entries (cc @oskretc). Closing this issue for now.
