### ISSUE TITLE
Copying folders with overwrite - Abort doesn't abort

### ISSUE THREAD

**Issue by ndcooke** [fman-community/fman#541]
If you are copying a folder into a directory which already contains that folder, fman prompts you with a dialog box like this: 
![image](https://user-images.githubusercontent.com/14249205/46627381-ead37d00-caff-11e8-9905-716e5dfeb32d.png)
for each file in subfolders that will be overwritten.  Choosing Abort does not abort the operation and the user receives this dialog for each file that could be overwritten:
![image](https://user-images.githubusercontent.com/14249205/46627449-21a99300-cb00-11e8-998b-51f26ae6a386.png)
![image](https://user-images.githubusercontent.com/14249205/46627475-2cfcbe80-cb00-11e8-8002-44acc3cbea26.png)
and so on...

**Comment by mherrmann** [comment]
Fixed in [fman 1.3.5](https://fman.io/changelog#v1.3.5).
