### ISSUE TITLE
Losing selected items when searching with typing

### ISSUE THREAD

**Issue by franksands** [fman-community/fman#544]
On earlier versions, when I started typing, the focus would just go to the first file that matched what I was typing. Now, it appears that only what I type is displayed in the tab. 
This is causing fman to lose the selected items if they do not match my new search.
For example: a folder has the files:
A.txt
B.txt

if I type `a`, only `A.txt` is displayed. When I press `space`, A.txt file is selected. If now I type `b`, only `B.txt` is displayed. When I press `esc`, all the files are displayed, but `A.txt` is no longer selected.

**Comment by mherrmann** [comment]
Thank you for the feedback. This is kind of by design. Otherwise, operations you perform such as copying or deleting might be applied to "invisible but selected" file. This could cause unexpected - and potentially irreversible! - changes.

**Comment by franksands** [comment]
Is there any way to disable this? I would prefer always seeing all files
and keeping my selections.

Em qui, 11 de out de 2018 11:56, Michael Herrmann <notifications@github.com>
escreveu:

**Comment by mherrmann** [comment]
Not at the moment, I'm afraid. I'd be curious: Is it a general preference of yours, or is there a particular use case where seeing all files is much better for you?

**Comment by franksands** [comment]
My current case is that I have a folder full of files and I have to copy a
few to another folder. Scrolling and selecting is horrible, so I type the
beginning of each file name. But when I type the second file name, I lost
the selection.

Em qui, 11 de out de 2018 13:45, Michael Herrmann <notifications@github.com>
escreveu:

**Comment by mherrmann** [comment]
I see, thanks for clarifying. Makes sense. I guess for now the workaround would be to copy (<kbd>F5</kbd>) each file immediately after selecting it.

**Comment by franksands** [comment]
Yeaah... but it would take more time to do this every time. Giving a bit
more of detail, the case is actually to update a bin folder with debug
files I've compiled. It's an embedded application, it's difficult to remote
debug it, so I've found easier to just test each change and see what's
going on. Because of this, I would have to copy 2 or 3 files several times
and I don't want to select them every time.
If there was a config to just go back to the previous behavior, or to keep
the selections, it would be great.

Em sex, 12 de out de 2018 03:28, Michael Herrmann <notifications@github.com>
escreveu:

**Comment by raguay** [comment]
If you load my SelectByRegExp plugin, you can select multiple files using a regular expression that is very flexible. Then over look the selected packages by scrolling or just copy them over to the other pane. I use this a lot with the use case you are mentioning above.

The plugin also saves previous regular expressions for easy selection.

**Comment by franksands** [comment]
Yeah, thanks for the suggestion. I'll think about it. It's not the ideal
solution for me.

Em sex, 12 de out de 2018 07:28, Richard Guay <notifications@github.com>
escreveu:

**Comment by franksands** [comment]
Hi, this really does not work for me. Is there no way to disable the filtering? This is becoming a deal breaker for me

**Comment by mherrmann** [comment]
As I said above, there is no existing way at the moment, sorry. You could solve this with a plugin that "remembers" the files you select, then gives you a shortcut to restore that selection. This way, you could select the files with the filter, then press <kbd>Escape</kbd> to clear the filter, followed by the shortcut to restore the selection. If that would be bearable for you let me know?

**Comment by franksands** [comment]
Thanks for the suggestion and all time spent here. I'll think about it.
Would it be possible to write a plug-in to disable filtering?

Thanks,
Francisco

Em seg, 15 de out de 2018 14:28, Michael Herrmann <notifications@github.com>
escreveu:

**Comment by mherrmann** [comment]
No, sorry, also plugins can't disable filtering at the moment.

**Comment by franksands** [comment]
Thanks for your time

Em seg, 15 de out de 2018 14:50, Michael Herrmann <notifications@github.com>
escreveu:
