### ISSUE TITLE
Symbolic links creation

### ISSUE THREAD

**Issue by zhartus** [fman-community/fman#546]
Fman is an excellent file manager, but it clearly lacks such a simple function as creating symlinks. Or maybe I just did not find this feature? I'm Linux user and before Fman I used Double Commander. And there it was enough to press "Shift+Ctrl+F5" to create a symbolic link to a file or folder under the cursor (it was created on opposite panel).

**Comment by mherrmann** [comment]
Implemented in [fman 1.7.3](https://fman.io/changelog#v1.7.3).
