### ISSUE TITLE
Add escape character for spaces when using Copy Paths to Clipboard

### ISSUE THREAD

**Issue by harritaylor** [fman-community/fman#547]
I use TaskPaper as my project management tool, and it would be great to copy paths of files with spaces in them as a link that is clickable. For example, currently if I use F11 (on Mac) with a file with a space in it, the pasted path looks like `/Example/Path/To/File I am interested.in`. As this is not a valid path, I cannot directly reach the file I want to from TaskPaper. 

An option to turn on escape characters when using CopyToClipboard would be great so that the example would look like `/Example/Path/To/File\ I\ am\ interested.in`. 
Thanks.

**Comment by so-lost** [comment]
just don't use spaces in your file names?

**Comment by harritaylor** [comment]
Ideally, yes - but I am dealing with 100s of PDF files in a shared folder, using spaces with file names keeps things organised much better within the team.

**Comment by raguay** [comment]
The problem is, changing this would mess up my use case. It would be best
to have a different command (which can be done with a plugin) than changing
a default.

**Comment by mherrmann** [comment]
I think this is too rare a use case to justify an extra setting. Please just [write a new plugin](https://fman.io/docs/plugins-introduction), copying and adapting the [source code of CopyPathsToClipboard](https://github.com/fman-users/Core/blob/13d5b4394ec1f2b3af0a9f75f782fd7e2cda60c3/core/commands/__init__.py#L820-L836) to suit your needs. If you need help with doing this, let me know.

**Comment by harritaylor** [comment]
Very happy to do so. Thanks for the resources.

**Comment by bridgeythegeek** [comment]
Similarly, on Windows, paths with spaces cause a problem when pasting into a terminal.
@harritaylor, did you ever write that plugin?

**Comment by harritaylor** [comment]
@bridgeythegeek Yes, I did, but I appear to have lost it. It didn't take long to make. If you're interested I'll write it again for you and submit to fman repo.
