### ISSUE TITLE
More of a help item than an issue

### ISSUE THREAD

**Issue by biffbaxter** [fman-community/fman#548]
Struggled slightly to get termite terminal to open in the current DIR with a light i3wm desktop (read only i3 installed) on Arch. finally figured it out for anyone who might need it. 

Its a slightly different command than xfce term or others you might find. To get it to launch in the current dir correctly use the syntax below. 
`"terminal": {
		"args": ["/usr/bin/termite", "--directory={curr_dir}"]
	}`

**Comment by mherrmann** [comment]
Thanks! I updated the [docs](fman.io/docs/terminal).
