### ISSUE TITLE
Invalid key for ubuntu repo

### ISSUE THREAD

**Issue by akissinger** [fman-community/fman#556]
My initial install of fman worked fine some months ago, following these instructions:
https://fman.io/download/thank-you?os=Linux&distribution=Ubuntu

But now I get this when running "apt update":

Err:8 https://fman.io/updates/ubuntu stable InRelease
  The following signatures were invalid: 45BCC825BC281C06D2A7F912B015FE599CFAF7EB
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://fman.io/updates/ubuntu stable InRelease: The following signatures were invalid: 45BCC825BC281C06D2A7F912B015FE599CFAF7EB

I've tried deleting and reinstalling the key, but that didn't help.

I'm running Ubuntu 18.04. I believe I originally installed fman under 17.10 and have done a dist-upgrade since (though I don't expect this affects anything).

**Comment by mherrmann** [comment]
Thanks for letting me know and sorry for the trouble. I'll look at this straight away.

**Comment by mherrmann** [comment]
> The following signatures were invalid

**Comment by mherrmann** [comment]
(Closed this accidentally - sorry.)

**Comment by mherrmann** [comment]
Does `apt-get update` work for you now (in the sense that it doesn't give any errors)?

**Comment by mherrmann** [comment]
(I restored a backup of the previous version of the repository.)

**Comment by akissinger** [comment]
yes, it works now. it also said fman needs an upgrade, which I did. Now I have this version installed:

$ apt-cache showpkg fman
Package: fman
Versions: 
1.3.7 (/var/lib/apt/lists/fman.io_updates_ubuntu_dists_stable_main_binary-amd64_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/fman.io_updates_ubuntu_dists_stable_main_binary-amd64_Packages
                  MD5: 1eafbc3b533276316da456fc07899c08


Reverse Depends: 
Dependencies: 
1.3.7 - 
Provides: 
1.3.7 - 
Reverse Provides:

**Comment by mherrmann** [comment]
:+1: thanks. I released 1.3.8 today, which apparently broke the repo. Will try to fix; Can I ask you later to see if it works then?

**Comment by mherrmann** [comment]
Should work now, to update to fman 1.3.9. If it doesn't, please let me know @akissinger.
