### ISSUE TITLE
Fuzzy match

### ISSUE THREAD

**Issue by jrappen** [fman-community/fman#557]
since you've been tinkering with fuzzy match the last few releases, compare:

* <https://github.com/forrestthewoods/lib_fts>
* <https://github.com/farzher/fuzzysort>

**Comment by mherrmann** [comment]
I'll take a look. Thanks!

**Comment by jrappen** [comment]
If you have a question for Jon Skinner (the SublimeHQ owner), it's easiest to catch him on Discord at:

<https://discord.gg/D43Pecu>
