### ISSUE TITLE
unbinding key sequences

### ISSUE THREAD

**Issue by thyresias** [fman-community/fman#560]
fman binds "ctrl+." to toggle_hidden_files
But this is not a possible shortcut for me (French keyboard), so I bound it to "ctrl+;", and I would like to remove the binding for "ctrl+.", so that it does not appear anymore as a shortcut in the command palette: is there a way to do so?

**Comment by mherrmann** [comment]
Thank you for the suggestion. I implemented this now in fman 1.4.1. For more information, please see the [Changelog](https://fman.io/changelog#v1.4.1).

**Comment by thyresias** [comment]
Great, thanks.
