### ISSUE TITLE
After creating new directory cursor is not placed on it

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#565]
Noticed a strange issue on 1.4.3, not sure if it was in earlier versions.
When creating new directory on one pane cursor does not move to it. While on another pane after creating new directory cursor is placed on that directory.
Problematic directory had this path: /Volumes/Mac OS/Users/{username}/Downloads , but if I open it on another pane with following route /Users/{username}/Downloads - it works correctly.

**Comment by mherrmann** [comment]
Fixed in [fman 1.4.4](https://fman.io/changelog#v1.4.4).
