### ISSUE TITLE
Jump to bottom

### ISSUE THREAD

**Issue by so-lost** [fman-community/fman#566]
Super simple question just looking for a way to jump to the bottom of a list of files? For example my folder with screenshots contains a bunch of files called "Screen Shot 2018-10-26 at 21.47.03" and so on and there must be a quicker way than just to scroll to the bottom? I would type search but since the file names are inconvenient I need another solution, is there a way to add a keybind for it?

thanks for any tips!

**Comment by mherrmann** [comment]
Have you tried the <kbd>End</kbd> key?

**Comment by so-lost** [comment]
> Have you tried the End key?

Thanks, lifesaver! If any1 else is wondering on mac it is `Fn + Right/Left Arrow`
