### ISSUE TITLE
Traps thinks fman is a threat

### ISSUE THREAD

**Issue by oskretc** [fman-community/fman#567]
I know you will not do anything, but just want to log it here for completeness.

This happened after 1.4.4 update.

![image](https://user-images.githubusercontent.com/4963991/48350581-f595aa80-e687-11e8-9f29-939a05dbd38f.png)

**Comment by mherrmann** [comment]
Thank you! I appreciate the report.

For others finding this on Google, please see [this post](https://fman.io/blog/fman-and-antivirus/).

**Comment by oskretc** [comment]
And again.

![image](https://user-images.githubusercontent.com/4963991/49083305-7b9b1f00-f24c-11e8-91b4-9230b80c44ec.png)


Any way to mitigate this? 

I have to go through my IT department with all the bureaucracy involved to fix it.

**Comment by mherrmann** [comment]
Sorry, there's nothing I can do. If the AV misclassifies fman, you have to
tell it's vendor to correct - their - mistake.
