### ISSUE TITLE
Version 1.4.4 seen as malware in Windows 10

### ISSUE THREAD

**Issue by amakowiecki** [fman-community/fman#568]
After updating to version 1.4.4. Windows Defender claims that fman exe (AppData\Local\fman\Versions\1.4.4\fman.exe) contains a malware (Trojan:Win32/Tiggre!plock).
Reinstalling gives the same results.

**Comment by mherrmann** [comment]
@amakowiecki which [definition version](https://docs.microsoft.com/en-us/windows/security/threat-protection/windows-defender-antivirus/windows-defender-security-center-antivirus#definition-version) do you have?

**Comment by amakowiecki** [comment]
Threat definition version: 1.128.53.0

**Comment by mherrmann** [comment]
Thank you!

**Comment by blokeley** [comment]
Windows Defender has removed something in fman so it does not run any more.

I'm assuming that the fix will come in the form of an update but, as I understand it, the updates are enacted by running fman (which I cannot do).

How can I get the update when it is released?

**Comment by mherrmann** [comment]
@amakowiecki could it be that you have definitions 1.281.53.0 not 1.128.53.0? Because that's the one I have and it's eerily similar to yours.

**Comment by mherrmann** [comment]
I have [submitted fman as a false positive](https://www.microsoft.com/en-us/wdsi/filesubmission) on Windows Defender's web site. I am hoping that Microsoft will be able to update their definitions to fix this problem. It's really annoying :roll_eyes:

The only way to get fman working again in the meantime is to tell Windows Defender not to quarantine it. You can do this either when the "threat" is detected. Or later in the history of actions it's taken.

**Comment by blokeley** [comment]
Is there a way to be sure it has not been infected with a Trojan?

**Comment by mherrmann** [comment]
I just published a [blog post](https://fman.io/blog/fman-144-and-windows-defender/) about this problem.

**Comment by amakowiecki** [comment]
> could it be that you have definitions 1.281.53.0 not 1.128.53.0

You're right, it's 1.281.53.0, stupid typo, sorry.

**Comment by mherrmann** [comment]
No problem @amakowiecki :-) Thanks.

**Comment by mherrmann** [comment]
Microsoft have fixed the erroneous detection. If you still encounter problems, please follow these steps to clear the cache and obtain the latest malware definitions:

1. Open a command prompt as Administrator and navigate to `c:\Program Files\Windows Defender`.
2. Run `MpCmdRun.exe -removedefinitions -dynamicsignatures`.

Alternatively, the latest definitions are available for download [here](https://www.microsoft.com/en-us/wdsi/definitions).

**Comment by Seanny123** [comment]
Ended up having re-install. ):

**Comment by mherrmann** [comment]
But then it worked right?

**Comment by Seanny123** [comment]
It did work after reinstalling!

Didn't mean to shame you, just wanted to share my experience.

**Comment by mherrmann** [comment]
Appreciated! Thanks!
