### ISSUE TITLE
fman causes XnViewMP to crash when opening file

### ISSUE THREAD

**Issue by joshas** [fman-community/fman#570]
I use XnViewMP (version 0.92, 64bit) to open image files. In fman 1.4.4 opening image file that is associated with XnViewMP causes XnViewMP to crash. If an instance of XnViewMP is already open in background crash does not occur. Earlier fman versions worked without issues in this scenario. No problems opening images in Finder.

**Comment by mherrmann** [comment]
Fixed. Will go live with fman 1.4.5.

**Comment by mherrmann** [comment]
Fixed in [fman 1.4.5](https://fman.io/changelog#v1.4.5).
