### ISSUE TITLE
Search plugin causes fman to crash

### ISSUE THREAD

**Issue by blokeley** [fman-community/fman#571]
The `Search` plugin has a `Search with dialog` command.

If you invoke this twice in a row, it crashes `fman` completely.  The `fman` window simply disappears.

This might be a bug in the `Search` plugin, but `fman` should be resistant to it.

**Comment by mherrmann** [comment]
The `Search` plugin uses unsupported APIs. I can't (easily) prevent plugins from doing crazy things. Unless I run them in separate processes, which is difficult to implement. So my (current) stance on this is that it's outside fman's current scope and it should please be filed as an issue of the Search plugin instead.

**Comment by JayBeeDe** [comment]
@mherrmann : I could easily reproduce it:
- Open the "Search with Dialog window"
- Type something in the file filter field and click search (result can be empty, it doesn't matter)
- Wait the search to be finished
- Click on the fman window to put it in foreground and to put the Search Dialog window in background
- Reopen the "Search with Dialog window" via keyboard shortcut or via the ctrl+shit+P menu
- **fman crashes**


Tested in Windows

**Comment by raguay** [comment]
Yep, it happens in Mac OS as well.

**Comment by mherrmann** [comment]
I appreciate the reports; But as I wrote above, this is an issue that should be fixed in the Search plugin. In fact, it already is filed as an [issue](https://github.com/rholi/Search/issues/2) there.

**Comment by JayBeeDe** [comment]
Ok sorry, I have only checked for already existing bug reports in that repository... Thanks
