### ISSUE TITLE
Install fman on linux without root?

### ISSUE THREAD

**Issue by hugobuddel** [fman-community/fman#572]
Is there an easy way to install fman on linux without root? E.g. unzip and run?

I don't have root access on most of my work machines, so I can't use apt or rpm. At least, not easily. So it would be nice if there is a way to run fman. I'd like to use fman because then I can use the same file manager on all my systems.

This issue is similar to #550 and #65, but different since the discussions there seem to imply having root access.

**Comment by mherrmann** [comment]
You can just unpack the `.deb`, `.rpm` etc. and copy `opt/fman` inside it to (say) a removable drive. Here are the download links:

 * [fman.deb](https://download.fman.io/fman.deb)
 * [fman.rpm](https://download.fman.io/fman.rpm)
 * [fman.pkg.tar.xz](https://download.fman.io/fman.pkg.tar.xz)

**Comment by mherrmann** [comment]
(Feel free to re-open if that doesn't answer your question, or doesn't work.)

**Comment by hugobuddel** [comment]
That seems to work nicely, thanks!

**Comment by mherrmann** [comment]
Happy to hear it helped :-)
