### ISSUE TITLE
Sorting by Name: Show underscore "_" before numbers such as "0"

### ISSUE THREAD

**Issue by pandronic** [fman-community/fman#575]
I use underscore ("\_") for the folders and files that I want to appear first in a folder. This works both in Windows Explorer and Far Manager. In Fman if I have a folder name that start with a number it appear before the folders that start with "_". Fman probably sorts according to ASCII codes and the others employ some sort of smart sorting.

It's kinda of a deal breaker for me since I use underscore a lot and this messes up a lot of my folders. Any chance for a option?

**Comment by mherrmann** [comment]
Interesting. fman inherits Python's ordering of strings, which as you correctly surmised uses the ASCII encoding (/probably Unicode for non-ASCII characters).

Do you know of a better encoding that could be used? I already tried 'utf-8' but that would also sort `0` before `_`.

**Comment by pandronic** [comment]
I don't know if it's an encoding issue, probably just a custom sorting algorithm. Far Manager is open source (https://github.com/FarGroup/FarManager), maybe you could take a look at how they solved the problem?

**Comment by generic-user** [comment]
Hi, I have implemented a similar solution in C# once. I used an MIT licensed solution back then.

You can find the fiddle [here](https://dotnetfiddle.net/FgnhOq): don’t know if u know C# and the .NET framework. But if u would like I could help you to convert the implementation to python.

#### Example of the sorting algorithm:
```text
Unsorted                      Sorted
G16                           *BC-215
d0.20.2b.txt12                __G16
b0000.txt                     _underscored
abc1_2.txt                    1abc_2.txt
G16a                          a012.txt
d0.1000c.txt                  a000012.txt
BC-1                          a0000102.txt
_underscored                  a0000012.txt
a.010                         a000012b.txt
1abc_2.txt                    a0000012c.txt
b0001.txt                     a.010
abc12b.txt                    a.004
a012.txt                      a.100
G15-321                       a.000
G15a                          abc123.txt
s0-15s-10                     abc12.txt
s0-15s-215                    abc12.txt
b001.txt                      abc1_2.txt
s0-15s-214                    abc12b.txt
c0000c.txt                    -abc12.txt
-abc12.txt                    abccde.txt
a0000012c.txt                 b0000.txt
abc123.txt                    b0001.txt
*BC-215                       b001.txt
abccde.txt                    b00001.txt
e0000120000012                BC-1
a.004                         BC-214
c0000.txt                     c0000.txt
__G16                         c00001.txt
d0.2000y.txt                  c000b.txt
d0.20.2b.txt0002              c0000c.txt
a000012.txt                   d0.20000.2b.txt
G15                           d0.20.2b.txt
abc12.txt                     d0.20.2b.txt12
c00001.txt                    d0.20.2b.txt0002
d0.20.2b.txt10                d0.20.2b.txt10
b00001.txt                    d0.1000c.txt
a0000102.txt                  d0.2000y.txt
abc12.txt                     e0000120000012
d0.20000.2b.txt               e0000012000012
a.100                         G
e0000012000012                G16
c000b.txt                     G15
a.000                         G15
BC-214                        G15-321
G                             G16a
a000012b.txt                  G15a
G15                           s0-15s-10
d0.20.2b.txt                  s0-15s-215
s1-15s-215                    s0-15s-214
a0000012.txt                  s1-15s-215
s0-14s-215                    s0-14s-215
```

**Comment by nicogerber** [comment]
Hi, I would also like to see this enhancement implemented. NexusFile also sorts file and folder names starting with an underscore "_" before number such as "0".

**Comment by pandronic** [comment]
Looks like this is no longer an issue.
