### ISSUE TITLE
Font size change

### ISSUE THREAD

**Issue by Chaiavi** [fman-community/fman#580]
There is an open request for changing the font size using key bindings and mouse control #359 

I suggest here being able to change the font size (at least if not changing fonts altogether) using a ctrl+shit+p searching.

So I would be able to search for font (or "settings" or "configurations") where I will be able to change the font.

My current issue is that the font is too small for me (I assume most people using dual pane file managers aren't so young...) and I need a way (any way) of changing the font size.

**Comment by mherrmann** [comment]
Hi,

you can already change the font size by following [these steps](https://fman.io/docs/font-size-and-family). Does that help you?

Best,
Michael

**Comment by Chaiavi** [comment]
Thanks @mherrmann 

YES!
It works well, and now I have the font size I want.


This solved my immediate problem and I thank you for that.


I still think fman should have it configurable somewhere without creating and editing a Theme.css file though.

**Comment by mherrmann** [comment]
Happy to hear it works. I'll update #359 to incorporate your suggestions here.

**Comment by zohozer** [comment]
How I can define the font size in the `Theme.css` file? I could't find any reference into the manual?

https://fman.io/docs/font-size-and-family

**Comment by mherrmann** [comment]
Please see the example file mentioned in the manual: https://github.com/fman-users/Core/blob/master/Theme.css

**Comment by zohozer** [comment]
Thank you. Now it is working. Please update the manual with this link which is very useful.

**Comment by mherrmann** [comment]
The manual contains this link!
![image](https://user-images.githubusercontent.com/1076393/83228777-27496600-a187-11ea-93f5-f310dd269455.png)

**Comment by zohozer** [comment]
Thanks. My bad. I didn't realized that there is a link to that file.

**Comment by mherrmann** [comment]
No problem :-)

**Comment by reagle** [comment]
I'm checking on fman on macOS 12.1 21C52 arm64 and am unable to increase the font size. I'm editing `/Applications/fman.app/Contents/Resources/Plugins/Core/Theme.css` and increasing the point sizes, but nothing changes on `reload plugins` or restart...?

**Comment by reagle** [comment]
Oh, I see I need to edit `Theme (Mac).css`. I wonder what the non-platform specific files do then?
