### ISSUE TITLE
[Windows] can't find all folders

### ISSUE THREAD

**Issue by daniel-lribeiro** [fman-community/fman#582]
v.1.4.5

Ctrl + P can't find all the folders (not sure if just store in the local Onedrive folder)

**Comment by mherrmann** [comment]
With some exceptions, it only suggests directories you have already visited: https://fman.io/blog/goto-on-steroids/

**Comment by JESSICA-DOESNT-CODE** [comment]
I'm having the same issue, and I've definitely visited the directory.
