### ISSUE TITLE
New Folder shouldn't set default name to folder under cursor

### ISSUE THREAD

**Issue by matangover** [fman-community/fman#588]
This default makes no sense. You can't create a folder with a name that already exists.

**Comment by mherrmann** [comment]
If I remember correctly, this was specifically requested by a user. And what's the drawback? The entire text is selected, so you can just type a new name. But it helps users who want to create a similarly named folder.

**Comment by matangover** [comment]
OK, I can understand the use case. To me it's weird to have an invalid default (cannot create folder that already exists - for files it makes more sense because it strips the extension), and I don't remember myself ever wanting to create a folder named after an existing file / folder. But since the "damage" is minimal, it's super minor indeed.
