### ISSUE TITLE
'Edit' in empty folder raises error

### ISSUE THREAD

**Issue by matangover** [fman-community/fman#589]
![image](https://user-images.githubusercontent.com/5028956/49249540-7378e600-f3ea-11e8-9163-e3b40a460b87.png)

**Comment by mherrmann** [comment]
Fixed, thank you. Will go live with fman 1.4.9.

**Comment by mherrmann** [comment]
Fixed in [fman 1.4.9](https://fman.io/changelog#v1.4.9).
