### ISSUE TITLE
Palette and Comments in Key Bindings

### ISSUE THREAD

**Issue by nutnutwin** [fman-community/fman#592]
Newbie here
Thank you for making such a great app.

I was going through
https://github.com/fman-users/Core/blob/master/core/commands/__init__.py
for key bindings,
1. I wasn't able to find binding keyword for Palette(default: Cmd+Shift+P)
2. Seems I cannot use comment in "Key Binding.json"?

Wonder if you can give me some hints?

Thank you.

**Comment by mherrmann** [comment]
The command for the Command Palette is `CommandPalette`. You can refer to it in the key bindings as `command_palette`. See for instance the [default Key Bindings.json](https://github.com/fman-users/Core/blob/877f365d4fb5ca1753722b5d159918c5b70ad211/Key%20Bindings%20(Windows).json#L12).

No, .json files don't allow comments, sorry.

**Comment by nutnutwin** [comment]
Thank you so much for your reply!

**Comment by mherrmann** [comment]
Happy to help :-)
