### ISSUE TITLE
GoTo is very slow on macOS

### ISSUE THREAD

**Issue by kolnogorov** [fman-community/fman#598]
When you press CMD+P for GoTo panel, it takes around 5-10 seconds to show the panel, sometimes it activates system loader spinner. It's slow even if paths list is short or empty.

**Comment by kolnogorov** [comment]
I've discovered one clarification for this. It's, probably, not actually a "bug" itself, because it appears only when i have ftp-servers mounted as a folders (with CloudMounter), and there are paths to ftp-folders in goto cache file.

So, i think, there's not fman fault at all. But i guess, it will be nice to have a way to avoid these slowdowns. Maybe, make some feature to exclude some paths from goto-caching.

Anyways, thank your for the great product, what will become truly the best file manager of all times with no doubt! :)

**Comment by joshas** [comment]
Would be great if fman could detect if GoTo entries are loading too long and suggest ignoring some of problematic paths.

**Comment by mherrmann** [comment]
I think it should rather load entries in the background. Then, when you launch GoTo, it should display whatever it currently has. This will make it a lot faster.

**Comment by sullyj3** [comment]
Yeah, asynchronous fuzzy search would be much nicer.

**Comment by mherrmann** [comment]
Implemented asynchronous loading of entries in [fman 1.5.2](https://fman.io/changelog#v1.5.2) now. Hopefully, it should be faster for you guys.

(This only affects folders you visited previously. When you start typing an absolute path, fman still has to load it before being able to display it.)
