### ISSUE TITLE
Your license is not valid for this version of fman

### ISSUE THREAD

**Issue by chrizzzzz** [fman-community/fman#601]
Hi!

I recently bought fman for version 1.5.0. Now it seems like I have version 1.5.1 installed and the application complains about the license. Is there a way to install and stick with version 1.5.0? I tried to reinstall it with my original installation file, but it seems like it downloads something from the internet, perhaps the latest version? It is still 1.5.1 installed...

Thanks for a great product!
Christian

**Comment by mherrmann** [comment]
Hi Christian,

are you still able to find the fman license key email? It contains instructions for downloading and "sticking with" fman 1.5.0.

**Comment by chrizzzzz** [comment]
Hi Michael!

I found the email and the links. The setup file in the email is much bigger so I must have downloaded the general setup file at some point. :-)

Thanks for your quick reply!
Christian

**Comment by mherrmann** [comment]
Happy to help :-)
