### ISSUE TITLE
Creating folder while moving a file throws an error

### ISSUE THREAD

**Issue by kapooostin** [fman-community/fman#610]
If I add a folder in `Move` dialog `fman` asks whether it should create that folder for me. And when I click `Yes` it throws an error:
![image](https://user-images.githubusercontent.com/467097/50436897-e2b5fd00-08f8-11e9-870b-8ec88c7b4230.png)

**Comment by mherrmann** [comment]
Fixed in [fman 1.5.3](https://fman.io/changelog#v1.5.3).
