### ISSUE TITLE
Cannot "move" file with drag-and-drop

### ISSUE THREAD

**Issue by thomas-haslwanter** [fman-community/fman#611]
When dragging a file to a folder, the file is "copied" and not "moved".
Interestingly, a "move"-symbol (->) shows up, and a "copy"-symbol (+) shows up when the Ctrl-key is also pressed. But in both cases, the same action happens.

In other words, it is impossible to "move" a file with drag-and-drop, and only to "copy" a file.

Please enable "drag-and-drop" like in other file managers.

**Comment by mherrmann** [comment]
This appears to be pretty similar to #459. Which OS are you on?

**Comment by thomas-haslwanter** [comment]
No, I stay on the same volume.
And in this case I want a MOVE, not a copy.
I am on win10.

Best regards, Thomas

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by mherrmann** [comment]
Fixed in [fman 1.5.4](https://fman.io/changelog#v1.5.4).

**Comment by thomas-haslwanter** [comment]
Danke!
