### ISSUE TITLE
"Git Bash Here" command

### ISSUE THREAD

**Issue by viktortomov** [fman-community/fman#613]
Is there a way to configure fman to include Git Bash Here command? I.e. in the right-click menu or in the ctrl+shift+p commands menu?

**Comment by mherrmann** [comment]
You could use it as the Terminal for F9, and change the context menu to display the Terminal command? See fman.io/docs.

**Comment by viktortomov** [comment]
> You could use it as the Terminal for F9, and change the context menu to display the Terminal command? See fman.io/docs.

Thanks for the fast response! I think it would work.

Anyway, it is strange that I don't see the Core Settings file as described in the docs:
![image](https://user-images.githubusercontent.com/46623014/51085455-2a82b400-1742-11e9-8027-c8e8bc96b34a.png)
Any suggestions?

**Comment by mherrmann** [comment]
Press F4 and pick an editor. It will appear.

**Comment by mohnish82** [comment]
If you're using Conemu terminal emulator with Git Bash, following gets you new _tab_ at current directory.

```json
  "terminal": {
    "args": [
      "C:/<Path-to-Conemu-Install-Dir>/Conemu64.exe",
		"-reuse",
		"-dir",
		"{curr_dir}"
    ]
  }
```
