### ISSUE TITLE
It's Webroot SecureAnywhere's turn to flag fman as malware

### ISSUE THREAD

**Issue by Taconvino** [fman-community/fman#614]
![image](https://user-images.githubusercontent.com/21037174/51138142-1496f100-181f-11e9-9984-5b120c760f7b.png)

Hope it's ok to post this here.

**Comment by mherrmann** [comment]
Hi,

it's absolutely okay to post this here. But it's a problem with SecureAnywhere, not fman. Please see [here](https://fman.io/blog/fman-and-antivirus/).

In short, it's a false positive. Please mark it as such in SecureAnywhere, or get in touch with their support to fix this.

Cheers
Michael
