### ISSUE TITLE
fman quarantined by Windows Defender as Trojan:Win32/Ludicrouz.Q

### ISSUE THREAD

**Issue by blokeley** [fman-community/fman#624]
As of 2019-02-08, fman version 1.5.6 is being quarantined as malware by Windows Defender definition version 1.285.1134.0.

Windows 10 Pro.

**Comment by mherrmann** [comment]
Which exact file?

**Comment by mherrmann** [comment]
Microsoft have removed the detection. Please update your malware definitions as explained in [this post](https://fman.io/blog/fman-144-and-windows-defender/). Maybe you'll have to re-install fman.

Sorry for the trouble. It's Microsoft's wrong classification :(
