### ISSUE TITLE
Open multiple files with Enter

### ISSUE THREAD

**Issue by matangover** [fman-community/fman#625]
Right now when multiple files are selected and opened (either with Enter or with Cmd+Enter), only the one highlighted file is opened. There is a command 'Open selected files' which does open multiple files but does so sequentially instead of simultaneously.

One example where sequential opening is problematic is opening multiple audio files:
 - When opened from Finder, they all go into my VLC playlist one after another, as expected. The first file is played.
 - When opened from fman with Enter, only the first file is opened.
 - When opened from fman using 'Open selected files', the first file starts playing and then the second file starts playing after a short delay, etc.

IMO, there are two desired changes:
 - 'Open selected files' should open simultaneously rather than sequentially.
 - 'Open selected files' should be the default for Enter. (And perhaps 'open' should be renamed to 'open highlighted file'.)

**Comment by mherrmann** [comment]
I didn't dare change `Open` (resp. `OpenFile`) because some other functionality depends on it. But I just released [fman 1.5.7](https://fman.io/changelog#v1.5.7) that improves `OpenSelectedFiles` along the lines you suggested.
