### ISSUE TITLE
Search Dialog Window shall be maximize-able

### ISSUE THREAD

**Issue by JayBeeDe** [fman-community/fman#626]
It shall be possible to maximize the Search Dialog Window (since it is a nice window :) )
And it also could be nice to be able to always have it maximized by default.

**Comment by mherrmann** [comment]
Please file this on the [issue tracker of the Search plugin](https://github.com/rholi/Search/issues).

**Comment by JayBeeDe** [comment]
Done: [https://github.com/rholi/Search/issues/4](https://github.com/rholi/Search/issues/4)
