### ISSUE TITLE
Search Dialog Window - File filter shall support regexp

### ISSUE THREAD

**Issue by JayBeeDe** [fman-community/fman#627]
Search Dialog Window:
The file filter shall support regexp.

**Comment by JayBeeDe** [comment]
Is it similar to #56  ?

**Comment by mherrmann** [comment]
This is an issue for the Search plugin, which I don't maintain. Please file this on [its issue tracker](https://github.com/rholi/Search/issues).

**Comment by mherrmann** [comment]
(And no, it's not like #56 because "filtering" is what happens when you just start typing inside a directory, and the non-matching files are hidden.)

**Comment by JayBeeDe** [comment]
Done: [https://github.com/rholi/Search/issues/3](https://github.com/rholi/Search/issues/3)
