### ISSUE TITLE
Action dialog not pop-up

### ISSUE THREAD

**Issue by jardous** [fman-community/fman#633]
Action dialog (e.g. while copying large files to NAS) should not block the whole app. It should be possible to minimize the dialog window to continue working with other files

**Comment by mherrmann** [comment]
Hi, I dont think it does block the whole app?

**Comment by jardous** [comment]
right. Sorry for confusion. It just shows in the middle of the fman window and I was used to from Total Commander that the dialog could be sent to background. But it is enough to move the dialog and work. Thanks
