### ISSUE TITLE
Assign new schema to archive_handlers[]

### ISSUE THREAD

**Issue by nataliapc** [fman-community/fman#634]
There is any way for a plugin to modify **archive_handler[]** and assign a filetype to a schema?
Thanks

**Comment by mherrmann** [comment]
Absolutely. In your plugin, include a `Core Settings.json` file that includes an archive handler. Eg.:

    {
        "archive_handlers": {
            ".docx": "zip://"
        }
    }

You can also get the same effect by putting such a `Core Settings.json` file into your Settings plugin. (Likely, you will already have a `Core Settings.json` file there. In that case, edit it.)
