### ISSUE TITLE
Support for google filestream

### ISSUE THREAD

**Issue by jtrv** [fman-community/fman#635]
Not sure what it would take but support for google drive file stream would be awesome.

**Comment by rkhwaja** [comment]
Google Drive can have 2 files with the same name in the same directory. It doesn't strictly follow the filesystem abstraction.

**Comment by mherrmann** [comment]
This is currently beyond the scope of fman, but you can implement this as a plugin. Please see [here](https://fman.io/docs/plugins-introduction) and [here](https://fman.io/blog/fmans-new-file-system-api/) for getting started.
