### ISSUE TITLE
Uninstall on Windows 10 leaves behind omaha updater

### ISSUE THREAD

**Issue by ementat** [fman-community/fman#640]
Hi! I am trying to uninstall fman, but fman uninstaller leaves omaha updater as-is. So, fman is removed, but updater is still working and I don't see any way to remove it. Is it possible to uninstall the fman updater?

**Comment by mherrmann** [comment]
It uninstalls itself after a while. To speed up the process, follow the instructions for forcing an automatic update on https://fman.io/docs/automatic-updates.
