### ISSUE TITLE
~\Documents Pulling from Old Location

### ISSUE THREAD

**Issue by briankb** [fman-community/fman#644]
**Windows 10 OS**

using ~\Documents pulls up C:\Users\brian\Documents but I moved my default locations for Documents to my F: drive which is F:\Documents\ 

File explorer shows this on the left pane under "This PC" correctly and when navigating from there it goes to F:\Documents but fman pulls up C:\Users\brian\Documents. I assume it is getting this directory from somewhere, maybe the registry? 

Is it customizable so I can get ~\Documents or ~\Photos to go to the correct folder? 

on my system all of these default folders were moved to my F drive as C is my M.2 NVME which has limited space. 
~\Documents => F:\Documents
~\Photos => F:\Pictures
ect.

**Comment by mherrmann** [comment]
Once you've visited `F:\Documents` a few times, fman will automatically suggest it over `C:\...\Documents` when you type `Documents`. (Note that it will still suggest `C:\...` when you type `~\Documents` because `~` is your home directory and likely still on `C:\`.)
