### ISSUE TITLE
[Request] Publish fman to Chocolatey(Windows), Snapcraft(Linux), Brew(MacOS)

### ISSUE THREAD

**Issue by ma3yta** [fman-community/fman#648]
I published to _**Chocolatey**_ _(The package manager for Windows)_:
command ``choco install fman``
[<img src="https://i.gyazo.com/543ea404ce6f062ddf8e0e26774be037.png" alt="drawing" height="56"/>
](https://chocolatey.org/packages/fman/1.5.7.0) package repository: https://github.com/Ma3yTa/fman-chocolatey

to _**Snapcarft**_ _(The app store for Linux)_:
command ``snap install fman``
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/fman)
package repository: https://github.com/Ma3yTa/fman-snap

_**Brew**_ _(The package manager for macOS)_:
command ``brew cask install fman``
PR to update v1.5.7 by https://github.com/Homebrew/homebrew-cask/pull/61535

Integrate packages publishing in your build system.
Adding these channels will increase the number of users and cover other Linux distros.

_**NB.**_  @mherrmann I can transfer Chocolatey and Snapcraft accounts to you by changing email address if you would like to continue publishing packages.

**Comment by Ma3yTa** [comment]
fo example: https://chocolatey.org/packages/TotalCommander

**Comment by oskretc** [comment]
nice, Will totally use it. Thanks

**Comment by mherrmann** [comment]
This is very cool, thank you @Ma3yTa! Can the steps for uploading a new version to the respective repositories be automated somehow? Then I can add this to fman's build/release process.

**Comment by ma3yta** [comment]
@mherrmann 
I created scripts but need to improve them to just provide version number, then script can download binary, calculate checksum and update appropriate fields in files, build and publish :
for ``chocolatey`` - https://github.com/Ma3yTa/fman-chocolatey/blob/master/publish.ps1
for ``snap`` - https://github.com/Ma3yTa/fman-snap/blob/master/publish.sh
for ``brew`` - https://github.com/Ma3yTa/fman-cask/blob/master/publish.ps1#L19

**Comment by mherrmann** [comment]
Okay!

So for Homebrew we need to create a PR that updates [`Casks/fman.rb`](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/fman.rb). I see you are doing this with a PowerShell script. I'm on Linux usually, so that's not very practical for me. But I suspect I can create a little script that does the same.

How do you create the Snap file that's used in [`publish.sh`](https://github.com/Ma3yTa/fman-snap/blob/master/publish.sh)?

For chocolatey, do I understand correctly that you run [`publish.ps1`](https://github.com/Ma3yTa/fman-chocolatey/blob/master/publish.ps1) in fman's installation directory, in particular in the `Versions/1.5.7` subdirectory?

**Comment by ma3yta** [comment]
>How do you create the Snap file that's used in publish.sh?

https://github.com/Ma3yTa/fman-snap/blob/master/publish.sh#L4 
``snapcraft`` command without arguments creates ``.snap`` file from https://github.com/Ma3yTa/fman-snap/blob/master/snapcraft.yaml which is located in the same directory.

>For chocolatey, do I understand correctly that you run publish.ps1 in fman's installation directory, in particular in the Versions/1.5.7 subdirectory?

No. In the root of https://github.com/Ma3yTa/fman-chocolatey . 
https://github.com/Ma3yTa/fman-chocolatey/blob/master/publish.ps1#L4 creates a package from https://github.com/Ma3yTa/fman-chocolatey/blob/master/package/fman.nuspec

**Comment by Ma3yTa** [comment]
for ``brew`` I will rewrite the script to bash

**Comment by ma3yta** [comment]
@mherrmann added bash script for ``brew`` https://github.com/Ma3yTa/fman-cask/blob/master/publish.sh

**Comment by ma3yta** [comment]
@mherrmann changed the email on ``snapcraft`` and ``chocolatey`` to yours.  ``fman`` package name is linked to these accounts.
just reset the password after email verification.
also, delete my email from ubuntu one because there can be few.

**Comment by ma3yta** [comment]
@mherrmann also, the suggestion that you can integrate the packages publishing in https://github.com/mherrmann/fbs . good luck!

**Comment by mherrmann** [comment]
Thank you! I'll get to your emails soon; Just busy with some tax stuff.

**Comment by Ma3yTa** [comment]
@mherrmann Ubuntu posted in Twitter about fman :)
https://twitter.com/ubuntu/status/1129041337653891072
please check if all works well, I noticed that link not added to Desktop
