### ISSUE TITLE
Positioning of fman in Win10 incorrect

### ISSUE THREAD

**Issue by thomas-haslwanter** [fman-community/fman#649]
It is only a minor point. But then I am in fman, and hit
Win + left
fman is positioned in the right(!) half of the screen, and vice versa with 
Win + right

I am using Win10, 64 bit, and all other programs are positioned correctly with the Windows-key

**Comment by mherrmann** [comment]
That's strange. fman itself doesn't do anything special with regard to this Windows functionality. The most likely causes I can think of are a Qt bug, or something special about your particular system. A preliminary [search](https://www.google.com/search?q=qt+windows+bug+win%2Bleft) for Qt bugs did not yield any interesting results. 

Does the problem also occur with [this test app](https://github.com/fman-users/fman/files/3053017/fman.zip)?

**Comment by thomas-haslwanter** [comment]
Thanks for responding so quickly!

What happens with the test-app, when I repeatedly press the
Win + "<-" (i.e. Win-key plus "left" on the num-pad):

small window -> full left half of screen -> full right half of screen -> small window

i.e. it is a cyclical behavior (which I had not realized).

With fman, I get:
i) after startup of fman, it appears in the top left half of the screen
ii) when I repeatedly press the
Win + "<-" 
it switches
top left half of screen -> top right half of screen -> top left half of screen

What I don't understand is why - even if fman takes up the full left half of the screen - it gets reduced to the upper/lower left half. But this is a really minor issue, and I go ahead and close the issue.

**Comment by mherrmann** [comment]
Okay, thank you for sharing your findings :-)
