### ISSUE TITLE
Directories ending in ".tar" are shown as empty

### ISSUE THREAD

**Issue by teoc98** [fman-community/fman#655]
If I open a directory whose name ends in ".tar", it does not show any file, like if it was empty. 
If I rename it with a diffent name (not ending in ".tar"), it's correctly visualized.

**Comment by mherrmann** [comment]
Thank you for reporting this. I fixed it now. Will go live with fman 1.6.0.

**Comment by mherrmann** [comment]
Fix released as part of [fman 1.6.0](fman.io/changelog#v1.6.0).
