### ISSUE TITLE
Sort by Name: Possibility to NOT sort numbers.

### ISSUE THREAD

**Issue by MikiGrit** [fman-community/fman#664]
I name my folder with photos by date e.g.
`2019_photos for whole year`
`201812_december`
`20190131_last day of month`

Fman currently take into account numbers when sorting and this messes up to correct order. Would it be possible to fix this and sort solely by strings?

PS: I'm on Ubuntu.

**Comment by mherrmann** [comment]
It used to be this way, but there are many very valid use cases for sorting by numbers (Eg. `Picture 2.jpg` and `Picture 12.jpg`). I feel this is an edge case, and the more common case is to sort by numbers. So I'm closing this issue as a "wontfix", sorry.
