### ISSUE TITLE
Select files from multiple directories

### ISSUE THREAD

**Issue by saim80** [fman-community/fman#675]
I would like to have a feature where I can select multiple files from various directories and take an action with all the selected files at once. Currently, changing directories deselects all the files already selected in the previous directory.

**Comment by mherrmann** [comment]
You can implement this yourself, by [writing a plugin](https://fman.io/docs/plugins-introduction). I won't get to implement this in core fman any time soon. So I'm closing this issue for now. If you need help with writing the plugin, let me know.
