### ISSUE TITLE
Have possibility to use just one pane ?

### ISSUE THREAD

**Issue by liberodark** [fman-community/fman#680]
Hi,

Have possibility to use one pane and not two all the time ?
Is not good for compress in same folder not on the other pane.
Would be good to add possibility to hide one pane and show two pane.

Best Regards

**Comment by mherrmann** [comment]
I'm closing this as a duplicate of #57.

**Comment by mherrmann** [comment]
(You can sort of get what you want by dragging the middle divider in fman all the way to the right.)
