### ISSUE TITLE
When copying path, can you make it so that even on Windows the paths are also copied with /

### ISSUE THREAD

**Issue by xiaodaigh** [fman-community/fman#684]
I use R and Julia and Python and the paths need to be `c:/data/` instead of `c:\data`. Is there a setting on Windows to default to `/`?

**Comment by mherrmann** [comment]
There's no setting, but you could [write your own plugin](https://fman.io/docs/plugins-introduction) that does this. You can copy and modify the [code for the `CopyPathsToClipboard` command](https://github.com/fman-users/Core/blob/353cc9bede6d42362ee76955eaabee2d4ca02f3a/core/commands/__init__.py#L876-L882). If you need help with this, feel free to let me know.

**Comment by xiaodaigh** [comment]
Got it working. Gotta submit it as a plugin, and also how to get rid of `_report_clipboard_action` from my own code?

```python
from fman import DirectoryPaneCommand, clipboard, show_status_message
from fman.url import as_human_readable

def _report_clipboard_action(verb, files, suffix='', ftype='file'):
	num = len(files)
	first_file = as_human_readable(files[0])
	if num == 1:
		message = '%s %s%s' % (verb, first_file, suffix)
	else:
		plural = 's' if num > 2 else ''
		message = '%s %s and %d other %s%s%s' % \
				  (verb, first_file, num - 1, ftype, plural, suffix)
	show_status_message(message, timeout_secs=3)

class CopyPathBackslash(DirectoryPaneCommand):
	def __call__(self):
		to_copy = self.get_chosen_files() or [self.pane.get_path()]
		files = '\n'.join(to_copy)
		clipboard.clear()
		
		to_copy2 = map(lambda x: '"' + as_human_readable(x) + '"', to_copy)

		clipboard.set_text(',\n'.join(to_copy2))
		_report_clipboard_action('Copied', to_copy, ' to the clipboard', 'path')
```

**Comment by mherrmann** [comment]
Well done! In my opinion, you can just leave `_report_clipboard_action` in your code. You can't "reuse" fman's implementation of this. The other option would be for you to remove the call `_report_clipboard_action('Copied',...)`. But then you don't get the status message.

Again, congratulations!! :)

**Comment by xiaodaigh** [comment]
plugin here https://github.com/xiaodaigh/CopyPathWithBackslashQuotes

When does it get into fman?
