### ISSUE TITLE
Ubuntu installation fails

### ISSUE THREAD

**Issue by ghost** [fman-community/fman#685]
I followed the ubuntu installation steps, but after apt-get update I get this error:

```
W: GPG error: https://fman.io/updates/ubuntu stable InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY B015FE599CFAF7EB
E: The repository 'https://fman.io/updates/ubuntu stable InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

```

I'm using Ubuntu 19.04

**Comment by mherrmann** [comment]
Sorry, but I cannot reproduce this on a clean installation of Ubuntu 19. I'm assuming it's a problem on your end. Did you execute the first step?

    sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 9CFAF7EB

**Comment by ghost** [comment]
Strange. I did the command (I can see it in my history with ctrl-R).
I executed that same command again from my history and now it works. I remember that the command was slow. I didn't see an error, but maybe there was a timeout or something. Now it works. Sorry for this.
