### ISSUE TITLE
Copy from search results

### ISSUE THREAD

**Issue by ikost** [fman-community/fman#686]
Hi! I found the following issue. To reproduce: 1. I search for a file with dialog and click on open the result in the fman pane 2. I try to copy that file to the second open pane 3. fman is raising an error 

> line 92, in copy
    if src_scheme == self.scheme and dst_scheme == file_scheme:
NameError: name 'dst_scheme' is not defined <

**Comment by mherrmann** [comment]
Hi, fman does not have its own search functionality. Are you using a plugin perhaps? If so, which one?

**Comment by ikost** [comment]
Hi. Yes, you are correct. The bug belongs to "Search" plugin which I thought is part of the fman. My mistake...

**Comment by mherrmann** [comment]
Then I'll close this issue :-) You may want to create an issue on the tracker for the search plugin.
