### ISSUE TITLE
Cannot copy to GDrive

### ISSUE THREAD

**Issue by fly666** [fman-community/fman#690]
When trying to simply copy files from one pane to the other, I consistently get the following message 

"You cannot copy a file to itself"

Of course, the path is different on the two tabs. Is it too long?
I start to regret buying this tool. This is a wonderful tool, but this is also a basic feature, and it quickly kills the productivity I gain with fman if we have to report bugs of that type.

![2019-10-09 09_48_08-fman](https://user-images.githubusercontent.com/16515207/66461730-f5f61b80-ea79-11e9-8f05-004bae4247b1.png)

**Comment by gkandler** [comment]
How exactly are you copying the file from one pane to the other?

**Comment by mherrmann** [comment]
How exactly are you copying the file from one pane to the other?

**Comment by fly666** [comment]
copy or move yields the same result (F5 , F6) or through ctrl-shift-P...
same error message all the time
G:\ is a google Gdrive drive.

**Comment by fly666** [comment]
copy or move yields the same result (F5 , F6) or through ctrl-shift-P...
same error message all the time
G:\ is a google Gdrive drive.

**Comment by fly666** [comment]
Did some tries, we can copy between G:\ and another drive C:\ for instance.
Copying from G:\ to G:\, whatever the path, fails (even if the path is
short).

**Comment by fly666** [comment]
working perfectly fine with and USB key mounted on D:\. Seems to be linked
to Google drive stream G:\

**Comment by theyoungercyrus** [comment]
I can reproduce issue for Google File Stream 

![image](https://user-images.githubusercontent.com/41883597/66722977-fed04f80-ede1-11e9-9fe7-885ea6b1426c.png)

![image](https://user-images.githubusercontent.com/41883597/66723006-3d660a00-ede2-11e9-80ec-0910913cfccc.png)

**Comment by mherrmann** [comment]
Fixed in [fman 1.6.8](https://fman.io/changelog#v1.6.8).

**Comment by fly666** [comment]
well done, much appreciated and working like a charm!

Kindest regards

**Comment by theyoungercyrus** [comment]
Can also confirm functionality.

Registered copy as result :)
