### ISSUE TITLE
Apple doesn't trust fman.io - Mac OS Catalina update

### ISSUE THREAD

**Issue by cbcoutinho** [fman-community/fman#691]
The most recent update to Mac OSX (Catalina) has brought on a number of security checks that restrict the opening of apps from unregistered developers

<img width="532" alt="Screen Shot 2019-10-18 at 10 19 32" src="https://user-images.githubusercontent.com/12901868/67078074-def9ac80-f190-11e9-941f-3c79dc623336.png">

**Comment by mherrmann** [comment]
Thanks. I uploaded a [release snapshot version of fman](https://www.dropbox.com/s/i02nv77upkl355i/fman.dmg?dl=1). Does this work for you (and other people reading this?) on Catalina?

**Comment by mherrmann** [comment]
Fixed in [fman 1.6.7](https://fman.io/blog/notarization-for-macos-catalina/). If you are on macOS Catalina and still see the above dialog, please report here.

**Comment by jonesberg** [comment]
Good afternoon!

I get the same screenshot as previously shown on version 1.6.9 (see attached). The modified date of the `.app` is Dec 6, 2019 at 02:47 on my machine.

<img width="532" alt="image" src="https://user-images.githubusercontent.com/3671624/70397406-e5adde80-19df-11ea-8e25-62d4149c152d.png">

**Comment by mherrmann** [comment]
:disappointed: you downloaded from fman.io/download @jonesberg ?

**Comment by mherrmann** [comment]
(Looking at your screenshot, it seems that's what it says.)

**Comment by jonesberg** [comment]
Hi Michael!

Correct: I've downloaded the file from fman.io/download.

**Comment by mherrmann** [comment]
Okay, thank you for letting me know :-(

**Comment by mherrmann** [comment]
I think I was able to finally fix this for all users in [fman 1.7.0](https://fman.io/changelog#v1.7.0). If not, please let me know. Sorry for the trouble. Apple with Catalina really don't make it easy for app developers like me.
