### ISSUE TITLE
Bitdefender flags fman install as malware

### ISSUE THREAD

**Issue by timoto** [fman-community/fman#693]
Bitdefender flags fman install as malware for both cloud and offline installers:

C:\Users\User Name\AppData\Local\fman\fman.exe is malware of type Gen:Suspicious.Cloud.2.IY2@a8aGxYfi

**Comment by mherrmann** [comment]
This is a problem in Bitdefender, not fman. Please tell them to fix this. (See also [here](https://fman.io/blog/fman-and-antivirus/).)
