### ISSUE TITLE
When filtering list, Ctrl + A doesn't allow to select the input in order to remove it. 

### ISSUE THREAD

**Issue by ReneFroger** [fman-community/fman#700]
Bug report
==============
**Version:** Fman version 1.6.6.
**Operating system:** Ubuntu 18.04.1 LTS with Linux kernel

The CUDA standard of input methods describes that Control+ A allows to select all text in an input field. Like in your addressbar or something.
Fman behaves nearly correctly to this standard, except one thing.

When browsing a directory in fman, type something and do your action, like delete.
Then you want to do Control + A to remove the content of input and typing other words to filter.
But nothing happens when you do Control + A, which is strange, because in all browsers and input fields, Control + A allows you to select all text in once.

Seems a bug to me?

**Comment by mherrmann** [comment]
Hi, you should be able to press <kbd>Escape</kbd> to get the behavior you want right?

**Comment by ReneFroger** [comment]
No, but that's not the point. I want to select all the text in the input method with <kbd>Control</kbd> + <kbd>a</kbd>, like in the reply field of Github (try it), it's the CUDA-standard. 

I was kindly surprised to not see that back in fman, while the other input methods which follows the CUDA-standard, are implemented.

**Comment by mherrmann** [comment]
The thing is that fman's filter field never really gains focus. It's more of a transparent overlay that happens to display the characters you typed. <kbd>Ctrl</kbd>+<kbd>a</kbd> is meant to select all files, not all characters in the filter field. In this respect, I see the behavior you describe to work as intended.
