### ISSUE TITLE
Target folder purged when moving folder

### ISSUE THREAD

**Issue by zelk** [fman-community/fman#702]
**Reproduction**
- Windows OS (not reproducible on Mac and unknown on Linux)
- Setup Google Drive File Stream folders
- Move a folder from one place to another within Google Drive File Stream folders (it is unclear if the bug also exists when copying from a regular folder into a Google Drive File Stream folder and vice versa or if the bug is only apparent when moving between two Google Drive File Stream folders)

**Expected behavior**
- Folder and its subfolders and files are moved from one location to the other.

**Result**
- Note that the target folder is completely wiped clean. All files, all subfolders and their subfolders and files are deleted, including the target folder itself.
- Then something weird happens where fman tries to rename a folder that doesn't work. I've just tried it once because it took me a lot of work to reproduce all the files and folders that got purged. I haven't dug deep into what happened there bug Google Drive File Stream showed me an error message that I was trying to do something that it was unable to sync to the cloud.

**Comments**
People tend to use Dropbox, Google Drive or Microsoft OneDrive and a few more. Google Drive is clearly very usual. There is another bug related to Google Drive File Stream that renders fman unusable, where you cannot copy or move files what so ever on Windows on Google Drive File Stream and I've seen this on several computers (https://github.com/fman-users/fman/issues/690). That's of course also bad but it at least just makes people leave and go for Total Manager or something like that. However, this bug deletes complete folder structures without warning. It took me some time to figure out what actually had happened so that I could recreate everything. I propose that this bug is rated very high.

The bug reminds me of this fixed bug, that also purged target folders; https://github.com/fman-users/fman/issues/357

**Comment by mherrmann** [comment]
Very sorry for the trouble. I just fixed this in [fman 1.6.8](https://fman.io/changelog#v1.6.8).
