### ISSUE TITLE
"fman.app" can't be opened because Apple cannot check it for malicious software

### ISSUE THREAD

**Issue by uvatbc** [fman-community/fman#711]
![image](https://user-images.githubusercontent.com/8391225/70484051-65e74900-1a9f-11ea-91ee-d46cdb82d96c.png)

Attempted up use the version that was available today (Dec 9th 2019) from the fman main site.

**Comment by uvatbc** [comment]
![image](https://user-images.githubusercontent.com/8391225/70484156-d4c4a200-1a9f-11ea-81e5-3848e6a81210.png)
Mac version: OSX Catalina

**Comment by mherrmann** [comment]
Closing this as a duplicate of #691.
