### ISSUE TITLE
Feature Request: Edit Command (F4) to give warning on folders

### ISSUE THREAD

**Issue by thesonofugly** [fman-community/fman#714]
Accidentally hit F4 (shortcut for Edit) today on a folder and it opened every file within that folder in my default editor (Notepad++). Would it be possible to add a warning that says something "You are about to edit <number> files. Do you wish to continue?" and have the number be configurable?

**Comment by mherrmann** [comment]
You can do this yourself by [writing a plugin](https://fman.io/docs/plugins-introduction) that does basically the same as the [built-in Edit command](https://github.com/fman-users/Core/blob/0562e61f57aec25d635840d584321a068ed3a94c/core/commands/__init__.py#L408). Let me know if you need help.
