### ISSUE TITLE
Opening file inside zip with Studio Code 

### ISSUE THREAD

**Issue by CharlesFr** [fman-community/fman#715]
I get the error below when I try to open a file which is inside a zipped file. I'd like this to open directly with Studio Code.

Can someone point me in the right direction?

![image](https://user-images.githubusercontent.com/16102087/71257405-9181f300-232b-11ea-9860-49bc85dc4d8e.png)

**Comment by mherrmann** [comment]
You can develop a custom plugin to do this, but it won't be easy. The error message gives an indication where to start.
