### ISSUE TITLE
QuickWindowsShares

### ISSUE THREAD

**Issue by Qitsch** [fman-community/fman#719]
Is there a way to open Windows share just by typing \\servername\sharefolder
I've managed to access shares only if I map them beforehand though there are issues while navigating network shares(hangs mostly).

**Comment by mherrmann** [comment]
Does it work if you use two back slashes while typing into GoTo? `\\servername\sharedfolder`

**Comment by Qitsch** [comment]
😨 It works...Thx!!!  I was trying just the server name \\servername, because there are multiple shares on server, and it doesnt do anything.
