### ISSUE TITLE
openFile crashes on windows 10

### ISSUE THREAD

**Issue by pburns001** [fman-community/fman#723]
Invoking openFille on text file results in this error:
![fman_file_open_fail_msg](https://user-images.githubusercontent.com/12852113/72849513-141c0c00-3c64-11ea-94f4-38d391fd32a7.PNG)

**Comment by pburns001** [comment]
I uninstalled and then reinstalled fman and it's working now, not sure what was happening.

**Comment by pburns001** [comment]
didn't mean to close

**Comment by mherrmann** [comment]
I think it's fine to close this because it's working for you now. Thank you for letting me know.

**Comment by pburns001** [comment]
Sounds good; I think the problem was hitting enter with a file selected without a application associated by the OS.
