### ISSUE TITLE
Can't go to directories with translated names on Norwegian Windows (like Users, Desktop)

### ISSUE THREAD

**Issue by bjarte** [fman-community/fman#726]
I have a Norwegian installation of Windows, but I have since changed the display language to English.

The directory C:\Users is displayed as "Users" everywhere in Explorer and fman _except_ in the go-to popup box, where it is displayed as "Brukere" (Norwegian for users).

In the go-to popup, if I select for example "C:\Brukere\\[username]", nothing happens.

See screenshots for an example.

![2020-02-04 11_23_47-Window](https://user-images.githubusercontent.com/134068/73736926-ef369700-4741-11ea-86d1-85764f31f431.png)
![2020-02-04 11_24_24-Window](https://user-images.githubusercontent.com/134068/73736927-ef369700-4741-11ea-957d-d59c98bd87b0.png)

**Comment by bjarte** [comment]
I tried to set Windows back to Norwegian, but I get the same result. The main window in fman displays the English directory names, while the go-to popup displays Norwegian names. Clicking on the path with Norwegian directory names doesn't do anything:

![2020-02-04 11_48_19-Window](https://user-images.githubusercontent.com/134068/73738369-a8966c00-4744-11ea-9dcc-638f8467fb02.png)

**Comment by bjarte** [comment]
This is a duplicate of #701, I realised:
https://github.com/fman-users/fman/issues/701

Thanks for the excellent work on fman!

**Comment by JohnArcher** [comment]
@bjarte Please add a +1 reaction to #701 so @mherrmann sees that this has high priority (see README.md).
