### ISSUE TITLE
Appdata directory won't open

### ISSUE THREAD

**Issue by dkrey** [fman-community/fman#730]
When I use CTRL-P and enter AppData, the directory is shown in the preview, but I'm unable to enter it.

This actually works
~\AppData

This doesn't do anything
C:\Users\dkrey\AppData

**Comment by JohnArcher** [comment]
@dkrey Do you use a non-English Windows? Then this may be the same problem as #701 . If so, please add a +1 reaction at this issue. Thanks!

**Comment by dkrey** [comment]
Yup, that's exactly my problem, thanks for the heads up. Let's follow the issue at https://github.com/fman-users/fman/issues/701 then.

**Comment by JohnArcher** [comment]
You are welcome! And thanks for voting.

Off Topic (sorry, don't know how to directly contact a user): I see some C64 stuff in your repos; nice! Are you also into Amiga?

**Comment by dkrey** [comment]
Yeah, I currently have two of 'em: an A1200 and an A500. But I haven't coded any assembly for the 68k.
