### ISSUE TITLE
Renaming file/folder by just changing case results in "already exists" error

### ISSUE THREAD

**Issue by judetheobscure3** [fman-community/fman#732]
Using fman v1.7.1 on Windows 10 - attempting to rename a file or folder using the same name but with a different case results in an "...already exists" error. For example, trying to rename "test.txt" to "Test.txt" results in the error "Test.txt already exists!". This occurs whether attempting to rename using the Shift+F6 shortcut or Right Click -> Rename.

![2020-03-12 13_57_37-fman – NOT REGISTERED](https://user-images.githubusercontent.com/53664059/76558019-8e019200-646a-11ea-83d2-ac9c0dca3d5e.png)

**Comment by judetheobscure3** [comment]
To expand a little further - although the resulting message looks more informational than it does like an error, the renaming fails.

**Comment by Arty2** [comment]
Cannot replicate on 1.7.2, probably fixed?

**Comment by mherrmann** [comment]
Can't replicate either. I suspect @judetheobscure3 is on Windows. There, the error message is intended. Because Windows doesn't distinguish between lower- and upper-case file names internally. (So in other words, on Windows, `test.txt` and `Test.txt` are the same file.)

**Comment by Arty2** [comment]
Apologies, should mention that my system is Windows 10, version 1909 (build 18363.720).
