### ISSUE TITLE
fman wrongly calculates MiB while labeling MB

### ISSUE THREAD

**Issue by dcervenkov** [fman-community/fman#733]
fman uses the SI prefix M (10^6), k (10^3), etc. while in reality, it calculates Mi (2^20), ki (2^10), etc. This should be fixed. My preferred fix would be to allow the user to chose SI or binary prefixes which would select the corresponding correct calculation.

**Comment by mherrmann** [comment]
Thank you. I fixed this now so fman correctly calculates 10^x, not 2^x. The fix will go live with the next release.

**Comment by mherrmann** [comment]
Fixed in [fman 1.7.2](https://fman.io/changelog#v1.7.2).
