### ISSUE TITLE
Window title to display active dir name

### ISSUE THREAD

**Issue by Arty2** [fman-community/fman#742]
This is particularly useful for handling multiple instances of fman, and also make it more relevant as what's important is the handling of directories and not the app's name. Don't get me wrong; love your concept and approach, keep it up!

PS: Relevant to #227

**Comment by mherrmann** [comment]
I'm sure you could [write a plugin](https://fman.io/docs/plugins-introduction) that does this. Implement [`DirectoryPaneListener.on_path_changed`](https://fman.io/docs/api#DirectoryPaneListener.on_path_changed) and use `win32gui` as in the attached screenshot. (Or better: obtain the window handle from Qt.) If you need help, let me know.

![2020-04-13 07_30_21-Hello World!](https://user-images.githubusercontent.com/1076393/79094767-d5748a00-7d58-11ea-8029-539d48c12a83.png)

**Comment by Arty2** [comment]
@mherrmann Appreciate your response, I'll be looking into it.
