### ISSUE TITLE
Purchase email/login email

### ISSUE THREAD

**Issue by ruslan-valis** [fman-community/fman#747]
Hi!

I've been purchased fman pro version from your site several minutes ago.
Can't receive email with reigstration credentials, email is not arrived for half an hour.
Can you double-check payment from your side and re-send reg email please?
Email: ruslan.valis@elecode.dev

Amazing file manager, btw. :)

Thank you,
Ruslan Valis

**Comment by mherrmann** [comment]
Hi,

you should have received several emails to your address. I see you tried to log in. Did that work? That is, when you went to https://fman.io/account/login and entered your email address there, did you get an email for logging in?

Thank you for purchasing a license,
Michael

**Comment by ruslan-valis** [comment]
Hi again,

I've double-checked my inbox, no emails related to fman...
but then i've looked over "junk email" in outlook and get your email.

Thank you, works perfect now. 
Be aware that microsoft encounting your email as spam.
BTW license invoice from MS Office they also marked as spam 👍 

Thank you,
Ruslan Valis

**Comment by mherrmann** [comment]
Happy to hear it works now!
