### ISSUE TITLE
Open same directory in other pane

### ISSUE THREAD

**Issue by tilboerner** [fman-community/fman#748]
I'm trying to find a shortcut or command to make the inactive pane open the same directory that is currently active in the other pane.

For example, if I have directory `/A/B/C` open on the left, I'd like a way to make the right panel open `/A/B/C` as well, independent of what's currently open or selected there. "Open in [left/right] pane" does not help me, because it opens a sub-directory instead of the current one.

I haven't found a reference to any of this in the docs. It's hard to search for in the command palette (`Ctrl` + `Shift` + `P`) since I don't know what such an action would be called; some cursory searches for "open", "clone", "pane" or "other" didn't yield anything useful. (Is there a complete, easily browsable list of all commands in a file somewhere?)

Does such a command exist and what is it called? Then I could make a key binding for it.

**Comment by tilboerner** [comment]
I think I just found the solution by accident, it just works the other way around: you can open the other pane's directory in the currently active pane by pressing `Ctrl` + `arrow`.

For example, when you're in the right pane and want to open the same dir that's open left, press `Ctrl` + `->`. Use the left arrow when you're in the left pane.

**Comment by mherrmann** [comment]
Sorry for your frustrating experience.

Here's how I usually do it: Press <kbd>End</kbd> in the left pane to put the cursor on a file, then press <kbd>Ctrl</kbd>+<kbd>→</kbd>. 

There's no built-in command that does exactly what you want. If it's important to you, you could [write a plugin](https://fman.io/docs/plugins-introduction) that copies the [implementation of the "open in left/right pane" command](https://github.com/fman-users/Core/blob/20d328a67fbd13d1adcf840f8b158040bfb3730f/core/commands/__init__.py#L1075-L1116).

**Comment by mherrmann** [comment]
Ah! That's of course even better :)

**Comment by tilboerner** [comment]
Thanks for the super-quick response and for making the nicest file manager I know. :+1:

**Comment by mherrmann** [comment]
My pleasure :) I'm happy to hear you like it.
