### ISSUE TITLE
Freezes every time after selecting first folder

### ISSUE THREAD

**Issue by alexpriest** [fman-community/fman#753]
Hi there—new user here, exploring fman for the first time. Every time I open it up, it freezes as soon as I select and open my first folder. Issue occurs when I'm in the tutorial and when I cancel the tutorial and try to use it on my own.

Any ideas? On a mac running Catalina.

Thanks!

**Comment by mherrmann** [comment]
No idea, sorry. Could it be that there is a popup hidden somewhere, that prevents fman's main window from being active? Does the problem persist across computer restarts?

**Comment by alexpriest** [comment]
Welp, a restart fixed it. Sorry for bugging you.
