### ISSUE TITLE
Feature quest: support for "Open Bash here"

### ISSUE THREAD

**Issue by ehcheng** [fman-community/fman#756]
Would love support for opening other terminals, like Bash (Windows Linux Subsystem), PowerShell, and Windows Terminal (wt). Thank you!

**Comment by mherrmann** [comment]
Hi! You do know that it's possible to configure the Terminal? Please see the [docs](https://fman.io/docs/terminal).

**Comment by ehcheng** [comment]
Thank you! Very helpful.

**Comment by gmkado** [comment]
@ehcheng were you able to get this working for wt and if so can you share what you did?  I just tried adding this to the core settings:

`"terminal": {"args": [ "wt.exe", "-d {curr_dir}" ] }`

It opens the terminal with error 0x8007010b which cryptically means the start directory was not correctly formatted

**Comment by ehcheng** [comment]
@gmkado Yes, this is working for me:
`	"terminal": {
		"args":[
			"C:/Users/publi/AppData/Local/Microsoft/WindowsApps/wt.exe",
			"-d",
			"{curr_dir}"
		]
	}`

**Comment by gmkado** [comment]
Thanks! That worked for me.  I needed to separate the `-d` and `curr_dir` into separate entries on the array
