### ISSUE TITLE
Can't delete any file or folder on mac. 

### ISSUE THREAD

**Issue by megaDRONe86** [fman-community/fman#763]
macOS 10.15.5
Fman never asked access for Automation/Finder.

![2020-07-13 23-32-14 2020-07-13 23_34_42](https://user-images.githubusercontent.com/2099768/87351082-8a3d6380-c561-11ea-9ccb-a94be86fcd52.gif)

**Comment by megaDRONe86** [comment]
I was able to fix it by using "Get Info", but before this deleting was not working and never asked permission.

**Comment by mherrmann** [comment]
Sorry about that. It's documented [here](https://fman.io/docs/macos).

**Comment by megaDRONe86** [comment]
@mherrmann on the website it's written: "The first time you delete a file in fman or invoke the Get Info command, you get the following popup (on macOS Catalina or later)"
But only Get Info command triggers the dialog. So you should fix documentation or better trigger GetInfo at first app launch.
