### ISSUE TITLE
OSX version support

### ISSUE THREAD

**Issue by clankill3r** [fman-community/fman#769]
Hi, I have been trying out fman for half a week now and I really like it. Trimming short amounts of time adds up to a lot of time. I want to buy a license but I have a question first.

The thing is, I use OSX 10.12.6 and I'm planning on sticking with that version cause it doesn't get better.
I see a lot off apps riding with the apple train, and have dropped support for OSX 10.12. 
It seems like human kind is loosing the ability to make software that can support I wide range of OSX versions.

I was wondering if this would affect fman anytime soon?

**Comment by mherrmann** [comment]
Hi! I'm happy to hear you like it. I have no intention to discontinue support for 10.12 anytime soon.
