### ISSUE TITLE
this application failed to start because it could not find or load the Qt platform plugin "windows" in "" when running exe

### ISSUE THREAD

**Issue by dgremmell19** [fman-community/fman#776]
Hello, I have been spinning my wheels here and have not found the correct answer to this. I created my application and ran fbs_freeze which created my target folder and the .exe file. When I try to run the .exe file, I receive this error:

this application failed to start because it could not find or load the Qt platform plugin "windows" in "" pyqt5 fbs exe

![image](https://user-images.githubusercontent.com/14253022/94091470-4f1fa200-fde6-11ea-9f97-c0596500ddba.png)

It looks like it is finding qwindow.dll but then unloads it. I can also confirm the files exist in the paths in the debug print out. 

I am on a windows 10 laptop. 

Any ideas on how to fix this?

**Comment by mherrmann** [comment]
Hi, this is the issue tracker or fman, not for fman build system (fbs). Furthermore, fbs's issue tracker would not be the right place for your question either, because it's only for bugs and not for help with your applications. I'd suggest you ask your question on StackOverflow.
