### ISSUE TITLE
Setting up hyper terminal as default?

### ISSUE THREAD

**Issue by sf-pear** [fman-community/fman#778]
How can I set up hyper terminal to my default terminal on fman (windows10)? I have tried the following:
```
{
	"terminal": {
		"args": "start C:\\Users\\---\\AppData\\Local\\hyper\\Hyper.exe", "shell": true, "cwd": "{curr_dir}"
	},
	"native_file_manager": {
		"args": ["start", "explorer", "{curr_dir}"], "shell": true
	}
}
```
It opens hyper, but not on the current directory. What am I doing wrong?

Notes: 
- I changed hyper's setting to automatically run bash, not sure if this has something to do with it not working.
- I can start hyper in the directory from file explorer with no issues.

**Comment by mherrmann** [comment]
Hi! You could debug the problem by executing `start C:\\Users\\---\\AppData\\Local\\hyper\\Hyper.exe` in a Windows command prompt, and seeing if that applies your current directory.

**Comment by sf-pear** [comment]
Hey! Thanks for the quick reply :) it didn't work in cmd either. Same issue, it opens, but not in the right directory. Do you know how I can fix it?

**Comment by mherrmann** [comment]
I don't know, sorry, but this means that the problem you are experiencing is not caused by fman. I'd recommend you ask on StackOverflow or similar to get to a stage where you have a command that works in the Windows command prompt.
