### ISSUE TITLE
Missing Error reports - Plugin 'Search'

### ISSUE THREAD

**Issue by thomas-haslwanter** [fman-community/fman#779]
On my system the "search" Plugin only responds with

`Plugin 'Search' raises an error.
`
Afterwards, the statusline keeps on indicating "searching ..."

It would be very helpful to see the error-message.
Also, does anybody else have that problem?

**Comment by mherrmann** [comment]
Hi Thomas, this belongs in the issue tracker of the Search plugin please. I'm closing this.
