### ISSUE TITLE
"Unable to connect to the Internet" during installation

### ISSUE THREAD

**Issue by thompsonalt** [fman-community/fman#782]
I've been using fman for a few months and loving it. Today, after building a new PC with a fresh install of Windows 10, fman's install isn't working. The install window says "Connecting to the internet" for a few minutes and then finally "Unable to connect to the Internet. If you use a firewall, please whitelist fmanUpdate.exe".
I haven't made any modifications to my firewall, and I've never had an issue installing fman before. I've tried tried adding all the fman executables I could find to "Allowed Apps" in Windows Defender Firewall to no avail. I've also tried disabling all the Windows defender firewalls.

Do you have any idea what could be causing this? Thanks!

**Comment by mherrmann** [comment]
Thank you very much for letting me know and sorry for the trouble. I've fixed it now so that when you go to fman.io/download and select Windows as before, the installer works.
