### ISSUE TITLE
New file add to working folder does not appear in fman

### ISSUE THREAD

**Issue by sarmamen** [fman-community/fman#784]
If my working folder is open in fman and I create a new file, the file is not shown in fman left pane until I click on the pane.

Execute the script:
![Bug_1_1](https://user-images.githubusercontent.com/18058256/98928720-6ae82000-24da-11eb-934c-81b75c890aca.PNG)

After clicking on the left pane:
![Bug_1_2](https://user-images.githubusercontent.com/18058256/98928735-6f143d80-24da-11eb-9233-0cf700dc58a4.PNG)

**Comment by mherrmann** [comment]
Thank you for the report. This is intended behavior. It's too expensive and comes with too many technical headaches to watch the folder for changes. (fman used to do it, but it lead to problems.)

**Comment by sarmamen** [comment]
I can understand this if the file is created outside of fman. But the problem is also there if i copy a file with fman from Folder1 to Folder2. Timestamp doesn't change on right pane and i have to go out from Folder2 and back in to make sure that the new file was copied.

File created in Folder1 at 12:01 and copied to Folder2 at 12:01
![image](https://user-images.githubusercontent.com/18058256/98932265-67a36300-24df-11eb-9e39-4eff72748c82.png)

After one min the dummyFile in Folder1 was recreated and the size increased to see the difference and copied to the Folder2:
![image](https://user-images.githubusercontent.com/18058256/98932429-97526b00-24df-11eb-9f93-70a0fdf47595.png)

After going out from the Folder2 and going back in
![image](https://user-images.githubusercontent.com/18058256/98932605-d7195280-24df-11eb-8f73-1d37d17055b4.png)
