### ISSUE TITLE
Delete file/folder not working on MacOS Big Sur

### ISSUE THREAD

**Issue by renmarq** [fman-community/fman#796]
Hi, I'm encountering a bug on Mac OS Big Sur (11.1). Can you help? Thanks.

Steps to reproduce:
1. Delete a file or a folder
2. The file disappears from fman but is not moved to the bin in the os
3. Refresh fman view, the file re-appears.

Edit: I just read the doc page about the authorizations. The problem is I don't see fman in the 'Automation' section to activate and I don't see any way to add it? Thanks.

**Comment by mherrmann** [comment]
Some people had success getting the "authorize fman?" dialog by invoking the "Get Info" command from the Command Palette. Does that help?

**Comment by renmarq** [comment]
Thank you Michael, it worked!

Le lun. 4 janv. 2021 à 06:27, Michael Herrmann <notifications@github.com> a
écrit :

**Comment by mherrmann** [comment]
Happy to hear it!
