### ISSUE TITLE
Edit (F4) doesn't work, giving the following error

### ISSUE THREAD

**Issue by igoryonya** [fman-community/fman#804]
Command 'MyOpenWithEditor' raised error.

Traceback (most recent call last):
  File "fman/impl/plugins/command_registry.py", line 128, in _execute_command
  File "/home/ria/.config/fman/Plugins/Third-party/OpenWithEditor/openwitheditor/__init__.py", line 36, in __call__
    editFile(editor, file)
  File "/home/ria/.config/fman/Plugins/Third-party/OpenWithEditor/openwitheditor/__init__.py", line 68, in editFile
    subprocess.run(["/usr/bin/open", "-a", editor, as_human_readable(file)])
  File "subprocess.py", line 423, in run
  File "subprocess.py", line 729, in __init__
  File "subprocess.py", line 1364, in _execute_child
FileNotFoundError: [Errno 2] Нет такого файла или каталога: '/usr/bin/open': '/usr/bin/open'

-----

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.5 LTS
Release:        18.04
Codename:       bionic

$ uname -a
Linux ws02800008006 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

-----

Just for fun, I've checked that "/usr/bin/open" file on system and it doesn't exist.

===

P.S.:
Preview File doesn't work either.
Pressing F3 or executing the Preview command from Quicksearch dialog doesn't do anything. No error, no responce at all. Just goes to the void.

**Comment by raguay** [comment]
Hi,

Yes, I wrote that plugin/extension on my Mac. I never ran it on linux and
I'm not sure what the equivalent is in Linux of the open command.
Therefore, that extension is currently Mac only and I don't have the time
right now to expand it to other OSes. If you want to try expanding the
extension, you can always submit a pull request.

**Comment by raguay** [comment]
BTW: If you have a problem with an extension, you should go to that extensions Github page and file the problem there.

**Comment by raguay** [comment]
Also, the builtin command to edit a file should work. Just unload the extension ‘OpenWithEditor’ from your extensions and the builtin command will be available.

**Comment by igoryonya** [comment]
Please tell if you know, if there is an info about extension's GitHub URLs from within the fman, because I couldn't find it. That's why I went to the main fman's github page.

**Comment by igoryonya** [comment]
> subprocess.run

**Comment by igoryonya** [comment]
> Linux of the open command

1. I don't know anything about python, but doesn't "subprocess.run" already supposed to just execute an app? Why can't you just directly use an editor from the subprocess.run?
2. I've found this command: /usr/bin/openapp. man describes it as:

openapp(1)                                                                                                                      GNUstep System Manual                                                                                                                     openapp(1)

NAME
       openapp - launch applications from the command line

SYNOPSIS
       openapp [--find] [--debug [--gdb= debuger]] [ --library-combo=library-combo ] application [arguments...]

DESCRIPTION
       The openapp command allows you to launch graphical GNUstep applications from the command line.

       application is the complete or relative name of the application program with or without the .app extension, like Ink.app.

       arguments are the arguments passed to the application.

       openapp first checks whether the application is in the current working directory.  If not then searches the GNUstep domains' Applications folders in the following order: User (i.e. ~/GNUstep/Applications), Local, Network, System. First match wins.

---

May be that is the one.

**Comment by raguay** [comment]
No, there isn't a way to get the GitHub address from fman, that I know of.
But, usually a search in Github for the name of the extension usually
brings it up okay.

**Comment by raguay** [comment]
> > Linux of the open command
> 
> 1. I don't know anything about python, but doesn't "subprocess.run" already supposed to just execute an app? Why can't you just directly use an editor from the subprocess.run?

The extension does use subprocess.run to run the OSes application to open an app with a file. Otherwise, it uses it to open a command line script with the file. The subprocess.run function doesn't open graphical programs directly. Just command line programs.

> 2. I've found this command: /usr/bin/openapp. man describes it as:
> 
> openapp(1) GNUstep System Manual openapp(1)

Yes, that one should work for linux. It seems to have the same functionality as macos open command. I just added it to the extension, but since I'm not running linux, I can't test it right now. Uninstall the extension and re-install should get the latest version of the extension with this added in.

**Comment by raguay** [comment]
Were you able to test it?
