### ISSUE TITLE
Can't create/open excel files through the command create_and_edit_file 

### ISSUE THREAD

**Issue by GKrog** [fman-community/fman#805]
When creating excel files   form the cmd create_and_esdit_file either .xlsm or .xlsx fails when I start it in excel from fman

![image](https://user-images.githubusercontent.com/63813802/107199751-167c1000-69f7-11eb-8e16-457d5d44a3af.png)

![image](https://user-images.githubusercontent.com/63813802/107199721-0e23d500-69f7-11eb-87c6-99b83c881d1a.png)

I also have some issues trying to set the default editor based on the file type, now it is instantly opens up i notepad++, since I'm not a coder I have some issues trying tofigure out the documentation to get this to happen. 

{"editor": 
    {"args": ["C:/Program Files/Notepad++/notepad++.exe", "{file}"]}

}

I've tried to change it to 

{"editor": 
    {"args": ["C:/Program Files/Notepad++/notepad++.exe", "{txt}"]},
    {"args": ["C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE", "{xlsm}"]},
    {"args": ["C:\Program Files\Microsoft Office\root\Office16\EXCEL.EXE", "{xlsx}"]}

}

**Comment by GKrog** [comment]
I see now the forward and backslash difference from copying the exe path directly from windows, though that didn't make any changes

**Comment by GKrog** [comment]
I've discovered that the open excel file is not fman related, I experienced the same issue now through a autohotkey script. 

but still it would be nice to defince the default editors/programs when using create_and_edit_file

**Comment by mherrmann** [comment]
`Create and edit file` creates an empty file. Empty as in "0 bytes". An empty file in Excel presumably looks very different, i.e. it has more than 0 bytes. The file extension `.xlsm` is just a name that tells Windows to use Excel to open that file. But when you ask Excel to open a file that is literally empty (0 bytes), it cannot do it. The only way for fman to work around this would be if fman understood that `.xlsm` is an Excel file and that it should generate the file byte contents that represent such a file to Excel. But this is wide outside fman's scope.
