### ISSUE TITLE
Drag and drop a GIF image from Chrome

### ISSUE THREAD

**Issue by lawrence-laz** [fman-community/fman#809]
When I drag and drop an image from Chrome browser to fman on Windows, it displays an error message:
```
Could not copy https://im6.ezgif.com/.../myfile.gif (no such file or directory).
```

Is this behavior not supported?

**Comment by mherrmann** [comment]
Not at the moment; You'd need to download the file with <kbd>Ctrl</kbd>+<kbd>S</kbd>.
