### ISSUE TITLE
Right-button menu for Windows Explorer

### ISSUE THREAD

**Issue by it-sec-std** [fman-community/fman#815]
There are some potentially useful features that are registered in Windows Explorer right-click menu (e.g. 7-zip, hashing, antivirus, etc), please see the example below:

![](https://www.windowscentral.com/sites/wpcentral.com/files/styles/large/public/field/image/2016/10/context-menu-open-bash-windows10.jpg)

For Total/Double commander they are available with right-click in the directory path panel.

Could we have the same in fman? I passed the interesting tutorial and know about F10 =) but certainly it's too long way to do same things)

**Comment by mherrmann** [comment]
Thank you for the suggestion. Not offering you the "default" entries was a conscious choice. If you're interested in the reasons, you can see this blog post: https://fman.io/blog/fmans-new-context-menu/
