### ISSUE TITLE
Plugins have disappeared

### ISSUE THREAD

**Issue by thomas-haslwanter** [fman-community/fman#821]
I have had to re-install fman. And some of the formerly available plugins have disappeared, e.g. the plugin to compare files. Is there any explanation, why existing plugins have been removed?

**Comment by raguay** [comment]
If you use a program to delete fman (ie: CleanMyMac, Keyboard Maestro,
etc), then that directory will also be deleted.  But, I noticed last time I
re-installed fman that the OS deleted the plugin directory as well (but, it
didn't used to). If you want to remove fman without losing your plugins and
registration, you will have to use `rm -f /Applications/fman.app` which
will not remove any other directories used by fman. But, be careful! Using
a command line like that does remove files with absolutely no way to get
them back.

**Comment by thomas-haslwanter** [comment]
That is not exactly what I meant: I was not able to newly install some of the exiting plugins. However, I have realized that the problem was caused by a quirk in my installation: I installed the program as "admin", and wanted to use and configure it as simple user.
So if every user installs fman independently that problem does not occur.
