### ISSUE TITLE
Windows 10 install does nothing

### ISSUE THREAD

**Issue by ekarious** [fman-community/fman#824]
Hello, 

I've tried to installed it recently to Windows 10 on a clean install and after double clicking the `fmanSetup.exe` file nothing happened. Tried a few times without success.

Does this already happened to others ?

**Comment by mherrmann** [comment]
Hi, how big is the `fmanSetup.exe` file? Where did you get it from? Do you have 32 bit Windows?

**Comment by ekarious** [comment]
HI, I got it from the official website, in the download folder.
I have a 64bit Windows 10 with the latest May 2021 upgrade.

**Comment by mherrmann** [comment]
And how big is the file?

**Comment by ekarious** [comment]
It is 31.2 Mo

I tried again by downloading today but still the same problem.

**Comment by mtra-nc** [comment]
I 'had' the same issue.
In my case fman installed itself but silently.
Please check your `C:\Users\%username%\AppData\Local\fman` directory whether it's there.

**Comment by ekarious** [comment]
I'll be damned. It's there, but there is no "shortcut" when searching the app with windows start menu. I'll do something. Thank you :)
