### ISSUE TITLE
Ability to 'Search files in subfolders' while using SFTP plugin (connection)

### ISSUE THREAD

**Issue by dspasicpdy** [fman-community/fman#828]
Hi, 
When connecting to remote host via the sftp plugin, functionality 'Search files in subfolders' is not working.

it returns stacktrace with the line:
_FileNotFoundError: [Errno 2] No such file or directory: 'sftp://<x_host>/x_path'_

I'm not aware of how hard would it be to implement such feature... if possible at all..
Thank you in advance!

**Comment by mherrmann** [comment]
I think the "Search files in subfolders" functionality is provided by a plugin, and I guess this plugin is not compatible with the SFTP plugin. I'd recommend you get in touch with the authors of the respective plugins.
