### ISSUE TITLE
Drag and drop from fman to outlook doesn't work on Windows.

### ISSUE THREAD

**Issue by Moving-Electrons** [fman-community/fman#829]
Dragging a file from fman and dropping it in an outlook email window does not work properly. Instead of pasting the file, it pastes the file's path into the email. I consider this a big issue as I'm constantly attaching files to emails by dragging them and dropping into outlook.

 OS: Windows
Version: 1.7.3.

**Comment by mherrmann** [comment]
I'll close this as a duplicate of #298.
