### ISSUE TITLE
apt-key is deprecated – cannot install fman

### ISSUE THREAD

**Issue by Granjow** [fman-community/fman#831]
I cannot install fman anymore on Ubuntu 21.04 because `apt-key` is deprecated and will be removed after Ubuntu 22.04 and Debian 11.

```
> apt-key adv --keyserver hkp://keyserver.ubuntu.com --recv 45BCC825BC281C06D2A7F912B015FE599CFAF7EB
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).
Executing: /tmp/apt-key-gpghome.xqjyYw1YLx/gpg.1.sh --keyserver hkp://keyserver.ubuntu.com --recv 45BCC825BC281C06D2A7F912B015FE599CFAF7EB
gpg: keyserver receive failed: Server indicated a failure
```

Can you update the instructions on installing fman under Ubuntu 21.04+?

**Comment by mherrmann** [comment]
I'm on Debian 11 and the command works for me. The error you posted indicates a temporary server failure to me. Are you able to reproduce it on other machines?

**Comment by Granjow** [comment]
Indeed – just tested it in a 20.04 docker container and had the same issue, so it cannot be because of Ubuntu 21.04 soon terminating support.

When I use `hkp://keyserver.ubuntu.com:80` instead, it works fine. Seems to be a local network issue.

Thanks for the help!
