### ISSUE TITLE
Add support for USB-Connected devices like smartphones

### ISSUE THREAD

**Issue by Chaiavi** [fman-community/fman#834]
I would like to be able to browse my phone files 

I think this is a pretty basic feature from a file manager

**Comment by mherrmann** [comment]
You (or someone else interested in this) can implement this yourself via fman's file system API. See https://fman.io/blog/fmans-new-file-system-api/.

**Comment by Chaiavi** [comment]
@mherrmann This is amazing documentation, it seems actually quite easy to implement

Thank you.

I am not sure I am the right fit for it, I hope someone will chime in, anyway, FMAN is built with amazing modularity which I recognize and truly appreciate
