### ISSUE TITLE
where is custom preference file?

### ISSUE THREAD

**Issue by xendia100** [fman-community/fman#844]
i hope it make preference file like this
i am using osx.

now. Application Support directory is too deep
( i recommand it is only for default setting )

i'd like to recommand setting file location move like this.

~/.config/.fman
~/.config/.fman.d/[installed themes, plugins by command]

or

~/.fman
~/.fman.d/[installed themes, plugins by command]

now where is custom setting file?
id like to backup setting file.

**Comment by mherrmann** [comment]
Did you even bother to look at the documentation?

**Comment by xendia100** [comment]
![image](https://user-images.githubusercontent.com/96650095/152689957-f78a1fc0-6705-4c52-b60a-98ae72299b67.png)
what is mean? my mistake?

**Comment by xendia100** [comment]
![image](https://user-images.githubusercontent.com/96650095/152690069-619b6231-8a9e-4bbb-b0b4-ffb07bb2ba39.png)

and all user setting file is too many. :(
do i have to backup all?

for example. vim, emacs
if user get 1file, they restore all setting status

i like this simple system with plugin like atom, vscode, emacs, vim.
this is good. but i didnt buy this cuz of setting file export, import ( by gui or file whatever )

i hope i buy this.
