### ISSUE TITLE
Delete doesn't work

### ISSUE THREAD

**Issue by ryecroft** [fman-community/fman#850]
macOS 12.3

I'm trialing fman and very pleased with it so far, except deleting files seems to have no permanent effect. The fman ui updates temporarily, but doing an `ls` of the directory shows the file is still there, and navigating away then back in fman refreshes the file list to show that it has not in fact been deleted, please see screen capture below.

https://cln.sh/TC8vAr

**Comment by mherrmann** [comment]
I believe this is a duplicate of #796.

**Comment by ryecroft** [comment]
Thanks Michael I missed that one.
