### ISSUE TITLE
Consider open sourcing

### ISSUE THREAD

**Issue by dufferzafar** [fman-community/fman#858]
One of the things that I liked about fman when it first launched was it's [open source promise](https://fman.io/blog/transparency/):

<img width="649" alt="image" src="https://user-images.githubusercontent.com/1449512/174261491-d7b147d5-533c-4401-a7e0-884a2e8acecd.png">

There haven't been any new commits to fman in atleast two years now? I'm not sure about this, but I can't figure out a way to confirm this either. 

Previously, the http://fman.io page used to have a [commits panel on the home page itself](https://web.archive.org/web/20200820165351/https://fman.io/): 

<img width="994" alt="image" src="https://user-images.githubusercontent.com/1449512/174356541-a50ba66f-816d-45d0-81e6-d6aa4802f9d1.png">

There are no dates on the fman.io chanelog or blog posts as well. [They used to be there, but have now been removed.](https://web.archive.org/web/20200512073817/https://fman.io/blog/)

The only place that still has dates is the RSS feed which shows the last update _might_ have been in May 2020: https://fman.io/blog/rss.xml

---

@mherrmann I'd like to ask you to please consider open sourcing fman now.

**Comment by mherrmann** [comment]
Hi @dufferzafar, I have some private commits that I haven't had time to make public. I won't be open sourcing fman just yet.

**Comment by fox8091** [comment]
It's been an additional 6 months since this was brought up, and it seems there have still been no new public commits (Unable to actually check, since the commit log has been removed). Please follow your commitment and open source fman. There has not been a new release since sometime between April 2020 and February 2021, exact time is inconclusive since fman also removed the release dates for each version on the changelog page. All around, this seems like a way to dodge open sourcing fman as initially promised. Is this in any way related to your plans to sell fman's source code for €140 (€189 - the €49 for just the videos) under a restrictive license as mentioned in your July 3, 2019 email announcing your book?

**Comment by NathanMH** [comment]
Many more months have passed without updates, commits, or comment. At this point I'm reticent to pay for an abandoned project, but also don't want to use a (mostly) dead closed source project either.

**Comment by dufferzafar** [comment]
"We shall never surrender!" - https://www.youtube.com/watch?v=CXIrnU7Y_RU

**Comment by tuurep** [comment]
Is this fraud?

**Comment by dufferzafar** [comment]
No, I don't think Michael was ever a fraud.

I remember the beginnings of fman - they worked really hard on market research of all existing file managers. I remember nudging them towards XYplorer which is what I was using that time on Windows.

The Open Source promise is a real gem - fman is the first project where I saw it - but I was just naive to assume that there would be an automated script that would push the repository to Github if commits are every delayed.

Michael was able to pull a self contained Qt starter kit - FBS - out of this project, and I believe that he tried really hard to build a better file manager, but alas life got in the way.

---

I can't find a link to this twitter thread I posted way back in 2018:

---

I’ve always wanted a feature rich file manager, but haven’t been able to find one.

Something that is: available on Linux, easily extensible and visually pleasing (icons, thumbnails etc.)

Did I say I’m picky?

There’s actually lots of good Windows based tools. Like @XYplorer: https://www.xyplorer.com

I was very happy with even its free version.

When I switched to Linux, around 4 years ago, I tried to get it work with Wine. It ran, but only barely. Weird errors abound.

One of the reasons I loved XYplorer was because it’s default view wasn’t “two-panes with list of files” - something that is oft associated with such file managers.

I just abhor list views.

Perhaps because I grew up using “Windows Explorer” and not “Midnight Commander”

I use #KDE now, which has a large suite of applications.

Once such gem is Krusader.

Sadly, It is two-paned and doesn’t have icons view. 

But boy does it have lots of configurable keyboard hotkeys - “user actions” as they’re so aptly named.

It has been a month since I switched to Krusader (from Dolphin - the Windows Explorer of KDE) and in that time I’ve filed multiple bugs/features and got decent responses from the devs:

https://bugs.kde.org/buglist.cgi?email1=dufferzafar&emailreporter1=1&emailtype1=substring&f1=reporter&list_id=1536354&o1=equals&product=krusader&query_format=advanced&v1=dufferzafar0%40gmail.com

One of Krusader’s coolest features is its UI for the standard “locate” command - which allows you to find files fast (just like the ‘Everything’ tool for Windows.)

https://www.voidtools.com

To be honest, I actually wish for a mix of Dolphin & Krusader, with features like:

Icon view instead of detailed list
Thumbnails for music & video files
Remember view settings per folder

etc. etc.

And before you begin to say: “build it yourself - it’s all open source”

I already have that on my todo list, right along with hundreds of other ideas.

“So many codes, so little time.” - Frank Zappa

#fakequote

No talk about powerful file managers can be complete without applauding ranger: https://ranger.github.io

I still remember how ecstatic I was when I found that it works amazingly well over SSH connections.

Have been using it for ~3-4 years now, and it sure has its use-cases.

One of the things I use it for is to quickly explore code repos: git clone && ranger!

Navigation using Vim-like key movements is godsent,
So is the preview pane which can show syntax highlighted code.

To top it all off - it’s written in #Python, as all good things should be.

The thing is, it’s core feature is also it’s biggest limitation - it’s inside a frickin’ terminal. Which were mostly made for displaying text.

I don’t want text. I want gorgeous images.

I want to visually skim through my wallpapers directory.

Not a big demand, is it? in 2018?

So yeah,

I constantly juggle between various file managers.

And I lament over the state of Linux software.

And I wish, and I hope...

...for a bright future.


and bright it will be!

@m_herrmann is building fman - “sublime text of file managers” http://fman.io

I’ve been following it from the very beginning & it gets a lot of things right:

Python API - making it pretty extensible
Automatic Updates
The Open Source Promise


I tried it about six months ago, but was instantaneously put off by the two panes & the “details view”.

Tried it again right now and couldn’t figure out how to get large icons. Spent like a minute with the app and wanted to go back.

It just needs some time to mature, I guess.

**Comment by dufferzafar** [comment]
cc: @aryans022 @Dewolf1
