### ISSUE TITLE
Fman an Monterey

### ISSUE THREAD

**Issue by proftc** [fman-community/fman#862]
When running fbs freeze on Monterey I get pages of missing dependencies
though it worked perfectly on Mojave
 
A typical msg is

(venvCD37A) IT036317:FBS_Test terry$ fbs release 1.0.0 5020 ERROR: Can not find path /usr/lib/libSystem.B.dylib (needed by /Users/terry/.pyenv/versions/3.7.7/bin/python3.7)

However the final dmg is created and works? I googled this and it seems that Monterey has now hidden some libraries? Is there a way around this?

**Comment by mherrmann** [comment]
Moving this to https://github.com/mherrmann/fbs/issues/282.
