### ISSUE TITLE
context menu

### ISSUE THREAD

**Issue by ravaq** [fman-community/fman#881]
Hi
two questions:
1. I didn't find context menu (or right click) command in command pallete,  is there any or I should use mouse for that?
2.  where is the options or config? for example I want to turn off the delete confirm dialog, how can I do that?

thanks!

**Comment by mherrmann** [comment]
Hi,

1. It's for the mouse. But on usual keyboards, there is also a key that simulates a right mouse click.
2. Please see https://fman.io/docs. It's not possible to turn off the delete confirm dialog.

**Comment by ravaq** [comment]
Thanks for your attention and response.
