### ISSUE TITLE
Option to group directories?

### ISSUE THREAD

**Issue by emilkaae** [fman-community/fman#883]
Hi,

I am very impressed with fman. I was wondering if there is an option to group directories when the view is sorted by name?

Best regards,
Emil

**Comment by mherrmann** [comment]
Hi, happy to hear you like it. There is no such option, sorry.

**Comment by emilkaae** [comment]
Thanks for responding. I'll close this issue then. I have not had time to look into the plugin API yet—would a plugin have access to affect the sorting of items?

**Comment by mherrmann** [comment]
Yes :)
