### ISSUE TITLE
Program freezes when searching for directory

### ISSUE THREAD

**Issue by seth-js** [fman-community/fman#884]
I've been using fman for years without issues. For some reason since yesterday, whenever I press `Ctrl+P`, and start typing to get to a directory, it freezes on the third letter every time. After about thirty seconds, the third letter appears, then I type the fourth letter and have to wait another 30 seconds. Pressing backspace until the third letter also freezes the application for each character. I'm not sure what's causing this, and I've already uninstalled and reinstalled fman twice, making sure to remove all config files and plugins.

I'm using Windows 10.

**Comment by seth-js** [comment]
It's fixed now. I'm still not sure what was causing it. Enabling safe mode, rebooting, disabling safe mode, and rebooting again fixed it.

Thank you for creating fman. It's extremely useful, and I can't imagine traversing and managing files and directories with anything else.

**Comment by mherrmann** [comment]
Happy to hear it's working again. Thank you for the kind words!
