### ISSUE TITLE
'Go To' error raised on launching fman

### ISSUE THREAD

**Issue by calton1954** [fman-community/fman#885]
Background is that I had 2 fman windows open (among other things) when my cat turned off my pc! After rebooting every time I launch fman I get this error. I'm running on a Windows 11 pc. I assume there's a corrupt file somewhere, but not in the fman folder itself as I've tried reinstalling and still get the error. Screen shot of error :
![image](https://github.com/fman-users/fman/assets/160400072/862d2e50-0462-44af-a02d-ed4333e9feab)

**Comment by calton1954** [comment]
Forgot to say, fman vers 1.7.3

**Comment by seth-js** [comment]
I just had this issue also. I wanted to test out something on another computer that I have, so I moved my SSD to the other computer. After I was finished testing it, I force shut it down out of laziness and moved the SSD back to my main PC. I then was getting this error message. It seems like `Visited Paths.json` gets corrupted if the computer unexpectedly shuts down while fman is open.

Delete this file:

`C:\Users\[Username]\AppData\Roaming\fman\Plugins\User\Settings\Visited Paths (Windows).json`

After that, everything should be back to normal. It will create a new file when the program opens. You will unfortunately lose your path history, but it's not a big deal.

**Comment by calton1954** [comment]
Thanks so much Seth, that worked a treat!
