### ISSUE TITLE
[PERFORMANCE ISSUE] Unbearably slow load times on large network drives 

### ISSUE THREAD

**Issue by malxsant** [fman-community/fman#889]
There are load times up to 2+ minutes when accessing files on a large (23+ TB) network drive. Issue is also exacerbated when accessing a file in a drive that is itself also somewhat large (100+ GB). Any update or indication that this file manager is still being worked on in 2024/2025 would be greatly appreciated. 

**As there have been no responses to other issues opened as late as August 2023, anyone seeing this issue with no response on or later than February 2025 can assume that this project is no longer being worked on, *and I would strongly advise you to NOT purchase a license.***

**Comment by mherrmann** [comment]
I'm still here and use fman every day without performance issues. No need to tell others in bold and all-caps not to buy a license. There's a free trial for everyone who wants to see how well it works.

Closing this.
